---
title: "`r paste0(maxyr, ' Northern Bering Sea Groundfish and Crab Trawl Survey Highlights')`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
output:
  pdf_document:
    citation_package: biblatex
    latex_engine: xelatex
  officedown::rdocx_document: 
    reference_docx: styles_reference.docx   
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
link-citations: true
keywords:
  - Bering Sea
  - Alaska
  - fisheries
  - NOAA
  - groundfish
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ". --", 
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ", 
  fig.cap.sep = ". -- ", 
  fig.align = 'center')
```

```{r introduction, child = paste0(dir_code, "c1_introduction.Rmd"), results='asis'}
```

```{r survey-design, child = paste0(dir_code, "c2_survey_design.Rmd"), results='asis'}
```

```{r survey-snapshot-compare, child = paste0(dir_code, "c3_survey_snapshot_compare.Rmd"), results='asis'}
```

<!-- \pagebreak -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "", 
  tab.cap.sep = "", 
  fig.cap.style = "Image Caption",
  fig.cap.pre = "", 
  fig.cap.sep = "", 
  fig.align = 'center')
```

```{r results-spp, echo=FALSE, results='asis'}
src <- c()
comb <- report_spp1 %>% dplyr::filter(!is.na(order)) %>% dplyr::select(file_name) %>% unlist() %>% unique()
for (jj in 1:length(comb)) {
  a <- report_spp1[which(report_spp1$file_name == comb[jj]), ]
  spp_code <- a$species_code
  aa <- catch_haul_cruises %>% 
    dplyr::filter(species_code %in% spp_code & year == maxyr)
  if (nrow(aa)>0) {
  src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
  }
}
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

```{r sci_profile}
# str0 <- officer::read_docx(path = paste0(dir_out_rawdata, "0-survey-team-bios.docx"))
# `r str0`
```

```{r survey-team-bios-insert-text, child=paste0(dir_out_rawdata, "/0-survey-team-bios.Rmd"), eval = FALSE}
```

```{r endmatter, child = paste0(dir_code, "10_endmatter.Rmd"), results='asis'}
```

