---
title: "`r paste0(params$maxyr, ' Northern Bering Sea Groundfish and Crab Trawl Survey Highlights')`"
# subtitle: The subtitle
params:
  # maxyr: 2022
  # compareyr: 2021
  # compareyr0: 2019
  maxyr: 2023
  compareyr: 2022
  compareyr0: 2021
  dir_googledrive: "https://drive.google.com/drive/folders/1gJYWYWzU8Iwi7gQmoSpCFVfxsoV20P2v"
  ref_compareyr: "@2021NEBS2022"
  ref_compareyr_nbs: "@RN909"
  strat_yr: 2022
  SRVY: "NEBS"
---

```{r setup}
report_title <- "community"
access_to_internet  <- TRUE # redownload google drive tables and docs?
quarto <- TRUE
showtext::showtext_auto()

maxyr <- params$maxyr
compareyr <- params$compareyr
compareyr0 <- params$compareyr0
dir_googledrive <- params$dir_googledrive
ref_compareyr <- params$ref_compareyr
ref_compareyr_nbs <- params$ref_compareyr_nbs
strat_yr <- params$strat_yr
SRVY <- params$SRVY

googledrive::drive_deauth()
googledrive::drive_auth()
2
```

```{r setup-functions, include=FALSE}
#| file: functions.R
```

```{r setup-data, include=FALSE}
#| file: data.R
```

```{r setup-files}
#| eval: false

a <- c(paste0(here::here("code"), "/", 
              c("c1-introduction", "c2-survey-design",
                "c3-survey-snapshot-compare", "06_results_spp", "10_endmatter",
                "_child_report_figtab"#, "_child_report_fig", "_child_report_tab"
                ), ".Rmd")#,
       # list.files(path = dir_out_rawdata, pattern = ".Rmd", full.names = TRUE)
       )
for (i in 1:length(a)) {
  b <- readLines(con = a[i])
  b <- gsub(pattern = ".Rmd", replacement = ".qmd", x = b)
  b <- gsub(pattern = "\\\\@ref(fig:", replacement = "(#", x = b, fixed = TRUE)
  b <- gsub(pattern = "\\\\@ref(tab:", replacement = "(#", x = b, fixed = TRUE)
  b <- gsub(pattern = "\\@ref(fig:", replacement = "(#", x = b, fixed = TRUE)
  b <- gsub(pattern = "\\@ref(tab:", replacement = "(#", x = b, fixed = TRUE)
  b <- gsub(pattern = "@ref(fig:", replacement = "(#", x = b, fixed = TRUE)
  b <- gsub(pattern = "@ref(tab:", replacement = "(#", x = b, fixed = TRUE)
  writeLines(text = b, con = gsub(pattern = ".Rmd", replacement = ".qmd", x = a[i]), sep = "\n")
}
```

```{r introduction, child = paste0(dir_code, "c1-introduction.qmd"), results='asis'}
```

```{r survey-design, child = paste0(dir_code, "c2-survey-design.qmd"), results='asis'}
```

```{r survey-snapshot-compare, child = paste0(dir_code, "c3-survey-snapshot-compare.qmd"), results='asis'}
```

<!-- \pagebreak -->

```{r results-spp, echo=FALSE, results='asis'}
src <- c()
comb <- report_spp1 %>% dplyr::filter(!is.na(order)) %>% dplyr::select(file_name) %>% unlist() %>% unique()
for (jj in 1:length(comb)) {
  a <- report_spp1[which(report_spp1$file_name == comb[jj]), ]
  spp_code <- a$species_code
  aa <- catch_haul_cruises %>% 
    dplyr::filter(species_code %in% spp_code & year == maxyr)
  if (nrow(aa)>0) {
    src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.qmd'))
  }
}
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

```{r endmatter, child = paste0(dir_code, "10_endmatter.qmd"), results='asis'}
```

