---
title: "`r paste0('Results of the ', maxyr, ' eastern ', ifelse(srvy == 'NEBS', 'and northern ', '') ,'Bering Sea continental shelf bottom trawl survey of groundfish and invertebrate fauna')`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
output:
  pdf_document:
    citation_package: biblatex
    biblatex: ["sortcites=true"]
    latex_engine: xelatex
  officedown::rdocx_document: 
    reference_docx: styles_reference.docx   
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
link-citations: true
keywords:
  - Bering Sea
  - Alaska
  - fisheries
  - NOAA
  - groundfish
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ". --", 
  tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ", 
  fig.cap.sep = ". -- ", 
  fig.align = 'left')
```

```{r abstract, child = paste0(dir_code, "01_abstract.Rmd"), results='asis'}
```

```{r introduction, child = paste0(dir_code, "02_introduction.Rmd"), results='asis'}
```

```{r methods, child = paste0(dir_code, "04_methods.Rmd"), results='asis'}
```

```{r results, child = paste0(dir_code, "05_results.Rmd"), results='asis'}
```

```{r results-spp, echo=FALSE, results='asis'}
src <- c()
comb <- sort(report_spp1|> dplyr::filter(!is.na(order))|> dplyr::select(file_name)|> unlist()|> unique())

for (jj in comb) {
  a <- report_spp1[which(report_spp1$file_name == jj), ]
  spp_code <- a$species_code
  aa <- catch_haul_cruises|> 
    dplyr::filter(species_code %in% spp_code & year == maxyr)
  if (nrow(aa)>0) {
  src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
  }
}
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

```{r endmatter, child = paste0(dir_code, "10_endmatter.Rmd"), results='asis'}
```

<!-- Appendix -->

\pagebreak

```{r, include=FALSE}
str0 <- ""

list_app <- function(nickname, dir_out_figtab, abcd, descr_short, descr_frag) {

  a <- list.files(path = dir_out_figtab, 
                  pattern = nickname, 
                  full.names = FALSE)
  
  nickname0 <- gsub(pattern = ".rdata",  
                    replacement = "", 
                    x = a[grepl(pattern = ".rdata", x = a)], 
                    ignore.case = TRUE)
  
  captions <- data.frame()
  for (i in 1:length(nickname0)) {
    a <- readtext(paste0(dir_out_figtab, nickname0[i], ".txt"))
    captions <- dplyr::bind_rows(
      captions, 
      data.frame(
        "id" = nickname0[i], 
        "capt" = a$text))
  }
    # # (APPENDIX) Appendix {-}
    str0 <- paste0(
    ifelse(abcd == "A", 
'

', 
'\\pagebreak

'),

'## Appendix ',abcd,': List of ', descr_short,' 

Appendix ',abcd, " ", descr_frag, '

**List of Tables**

',
text_list(paste0("\n\n - Appendix **", abcd, "** \\@ref(tab:", captions$id, "): ", captions$capt),
                 # sapply(list_tables00, #[grepl(x = names(list_tables00), pattern = "tab_app_taxa_encountered_")], "[[","header")), 
          sep = " ", sep_last = " ", sep_last2 = " "),
'

\\pagebreak

' )
    return(str0)
}

# https://support.authorea.com/en-us/article/how-to-create-an-appendix-section-or-supplementary-information-1g25i5a/
```

```{r tab-app-taxa-found-EBS}

abcd <- "A"

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')

nickname <- "tab-app-taxa-found-EBS"
str0 <- list_app(nickname = nickname, 
                 dir_out_figtab = dir_out_figtab, 
                 abcd = abcd, 
                 descr_short = "taxa encountered in the eastern Bering Sea shelf", 
                 descr_frag = paste0("lists all fish and invertebrate taxa encountered during the eastern Bering Sea shelf bottom trawl survey."))
sep0 <- "\\pagebreak"
```

`r str0 `

```{r tab-special-projects-EBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (abcd == "A")}
```

\pagebreak

```{r tab-app-taxa-found-NBS}
str0 <- ""
if(srvy == "NEBS"){
abcd <- "B"

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')

nickname <- "tab-app-taxa-found-NBS"
str0 <- list_app(nickname = nickname, 
                 dir_out_figtab = dir_out_figtab, 
                 abcd = abcd, 
                 descr_short = "taxa encountered in the northern Bering Sea shelf", 
                 descr_frag = paste0("lists all fish and invertebrate taxa encountered during the northern Bering Sea shelf bottom trawl survey."))
sep0 <- "\\pagebreak"
}
```

`r str0 `

```{r tab-special-projects-NBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (abcd == "B" & srvy == "NEBS")}
```

`r ifelse((abcd == "B" & srvy == "NEBS"), "\\pagebreak", "")`

```{r tab-app-fish-EBS-}

abcd <- ifelse(srvy == "NEBS", "C", "B")

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')

nickname <- "tab-app-fish-EBS-"
str0 <- list_app(nickname = nickname, 
                 dir_out_figtab = dir_out_figtab, 
                 abcd = abcd, 
                 descr_short = "population estimates by sex and size group for principal fish species in the eastern Bering Sea shelf", 
                 descr_frag = paste0("presents population estimates by sex and size group from the ", 
                                     maxyr,
                                     " eastern Bering Sea shelf bottom trawl survey for principal fish species."))
sep0 <- "\\pagebreak"
```

`r str0 `

```{r tab-app-fish-EBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (abcd == "C" & srvy == "NEBS" | abcd == "B" & srvy == "EBS")}
```

\pagebreak

```{r tab-app-fish-NBS-}
str0 <- ""
if(srvy == "NEBS"){
abcd <- "D"

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')

nickname <- "tab-app-fish-NBS-"
str0 <- list_app(nickname = nickname, 
                 dir_out_figtab = dir_out_figtab, 
                 abcd = abcd, 
                 descr_short = "population estimates by sex and size group for principal fish species in the northern Bering Sea shelf", 
                 descr_frag = paste0("presents population estimates by sex and length from the ", 
                                     maxyr,
                                     " northern Bering Sea shelf bottom trawl survey for principal fish species."))
sep0 <- "\\pagebreak"
}
```

`r str0 `

```{r tab-app-fish-NBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (abcd == "D" & srvy == "NEBS")}
```

`r ifelse((abcd == "D" & srvy == "NEBS"), "\\pagebreak", "")`

```{r app-data-change}
abcd <- ifelse(srvy == "NEBS", "E", "C")
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')
```

\pagebreak

<!---BLOCK_LANDSCAPE_START--->

## Appendix `r paste0(abcd)`: Survey participants. 

```{r tab-participants0}
nickname <- "tab-participants"
abcd <- ifelse(srvy == "NEBS", "F", "D")
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = paste0("Appendix Table ", abcd), 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = paste0("Appendix Figure ", abcd, " "),
  fig.cap.sep = ".-- ",
  fig.align = 'center')
```

```{r tab-participantss-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

<!---BLOCK_LANDSCAPE_STOP--->

\pagebreak

```{r app-data-changes, child=paste0(dir_out_rawdata, "0-data-changes.Rmd")}
```



