---
output:
  pdf_document:
    citation_package: biblatex
    latex_engine: xelatex
  officedown::rdocx_document: 
    reference_docx: styles_reference.docx   
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "https://raw.githubusercontent.com/afsc-gap-products/citations/main/cite/bibliography.bib"
link-citations: true
keywords:
  - Bering Sea
  - Alaska
  - fisheries
  - NOAA
  - groundfish
---

```{r setup, include=FALSE}
    # page_margins:
    #   bottom: 1
    #   top: 1
    #   right: 1
    #   left: 1 

# "https://github.com/afsc-gap-products/citations/blob/main/cite/bibliography.bib"
    # sansfont: Arial Narrow
    # fontsize: 11pt
    # geometry: margin=1in

knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ". --", 
  # tab.cap.align = "left", 
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ", 
  fig.cap.sep = ". -- ", 
  fig.align = 'center')
# plots:
#   caption:
#     style: Image Caption
#     pre: 'Fig. '
#     sep: '-- '
# tables:
#   caption:
#     style: Table Caption
#     pre: 'Table '
#     sep: '.-- '
# "--lua-filter", "figure_caption_patch.lua", 
```

```{r results-spp, echo=FALSE, results='asis'}
src <- c()
comb <- report_spp1 %>% dplyr::filter(!is.na(order)) %>% dplyr::select(file_name) %>% unlist() %>% unique()
for (jj in 1:length(comb)) {
# for (jj in 1:1) {
  src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
}
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

```{r endmatter, child = paste0(dir_code, "10_endmatter.Rmd"), results='asis'}
```

