---
title: "`r paste0('Results of the ', maxyr, ' eastern ', ifelse(SRVY == 'NEBS', 'and northern ', '') ,'Bering Sea continental shelf bottom trawl survey of groundfish and invertebrate fauna')`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
output:
  officedown::rdocx_document: 
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: styles_reference.docx
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ".-- ", 
  # tab.cap.align = "left", 
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Fig. ", 
  fig.cap.sep = ".-- ", 
  fig.align = 'center')

# plots:
#   caption:
#     style: Image Caption
#     pre: 'Fig. '
#     sep: '-- '
# tables:
#   caption:
#     style: Table Caption
#     pre: 'Table '
#     sep: '.-- '

# "--lua-filter", "figure_caption_patch.lua", 
```


```{r abstract, child = paste0(dir_code, "01_abstract.Rmd"), results='asis'}
```

```{r introduction, child = paste0(dir_code, "02_introduction.Rmd"), results='asis'}
```

```{r methods, child = paste0(dir_code, "04_methods.Rmd"), results='asis'}
```

```{r results, child = paste0(dir_code, "05_results.Rmd"), results='asis'}
```

```{r results_spp, echo=FALSE, results='asis'}
src <- list()
for (jj in 1:length( unique(report_spp1$file_name)[!is.na(unique(report_spp1$file_name))] )) {
  print(jj)
  src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
}
# You can also do it using lapply (I wanted the for loop though because I'm setting a bunch of params)
# src <- lapply(cyl.vec, function(cylcode){
#   knitr::knit_expand(here::here('markdown','Template.Rmd'))
# })
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```


```{r endmatter, child = paste0(dir_code, "10_endmatter.Rmd"), results='asis'}
```

```{r appendix, child = paste0(dir_code, "09_appendix.Rmd"), results='asis'}
```

