---
title: "`r paste0('Results of the ', maxyr, ' eastern ', paste0(SRVY == 'NEBS', 'and northern ', '') ,'Bering Sea continental shelf bottom trawl survey of groundfish and invertebrate fauna')`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
format: 
  docx: 
    reference-doc: styles_reference.docx
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography.bib"
execute:
  echo: false
  warning: false
  error: false
  message: false
  fig.align: center
---

```{r abstract, child = paste0(dir_code, "01_abstract.qmd"), results='asis'}
```


```{r introduction, child = paste0(dir_code, "02_introduction.Rmd"), results='asis'}
```

```{r survey_design, child = paste0(dir_code, "04_methods.Rmd"), results='asis'}
```

```{r results, child = paste0(dir_code, "05_results.Rmd"), results='asis'}
```

```{r results_spp, echo=FALSE, results='asis'}
src <- list()

for (jj in 1:length( unique(report_spp1$file_name)[!is.na(unique(report_spp1$file_name))] )) {
  print(paste0(jj, " of ", length(unique(report_spp1$file_name)), ": ", unique(report_spp1$file_name)[jj]))
  src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
}

# You can also do it using lapply (I wanted the for loop though because I'm setting a bunch of params)
# src <- lapply(cyl.vec, function(cylcode){
#   knitr::knit_expand(here::here('markdown','Template.Rmd'))
# })

res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```

```{r endmatter, child = paste0(dir_code, "10_endmatter.Rmd"), results='asis'}
```

