---
title: "`r paste0('Results of the ', maxyr, ' eastern ', ifelse(srvy == 'NEBS', 'and northern ', '') ,'Bering Sea continental shelf bottom trawl survey of groundfish and invertebrate fauna')`"
date: "`r paste0('DRAFT: ', format(Sys.time(), '%B %d, %Y'))`"
output:
  pdf_document:
    citation_package: biblatex
    biblatex: ["sortcites=true"]
    latex_engine: xelatex
  officedown::rdocx_document: 
    reference_docx: styles_reference.docx   
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, error = FALSE, message = FALSE, 
  tab.cap.style = "Table Caption", 
  tab.cap.pre = "Table", 
  tab.cap.sep = ". --", 
  tab.cap.align = "left",
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ", 
  fig.cap.sep = ". -- ", 
  fig.align = 'left')
```

<!---BLOCK_LANDSCAPE_START--->

```{r tab-age-samples-pres-0}
nickname <- "tab-age-samples-pres"
```

```{r tab-age-samples-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

```{r tab-stomach-samples-pres-0, eval = FALSE}
nickname <- "tab-stomach-samples-pres"
```

```{r tab-stomach-samples-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = FALSE}
```

```{r tab-length-samples-pres-0, eval = FALSE}
nickname <- "tab-length-samples-pres"
```

```{r tab-length-samples-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = FALSE}
```

```{r tab-biomass-pchange-pres-0}
nickname <- "tab-biomass-pchange-pres"
```

```{r tab-biomass-pchange-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```


```{r tab-biomass-pchange-alt-pres-0}
nickname <- "tab-biomass-pchange-alt-pres"
```

```{r tab-biomass-pchange-alt-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

```{r tab-special-projects-pres-0}
nickname <- "tab-special-projects-pres"
```

```{r tab-special-projects-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

```{r fig-biomass-topspecies-ebs-pres-0}
nickname <- "fig-biomass-topspecies-ebs-pres"
```

```{r fig-biomass-topspecies-ebs-pres-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```



<!---BLOCK_LANDSCAPE_STOP--->
