
\pagebreak

```{r res-spp-vars-{{jj}} }
a <- report_spp1[which(report_spp1$file_name == "{{jj}}"), ]

spp_sci <- text_list(unique(a$species_name))
spp_print <- a$print_name[1]
spp_file <- a$file_name[1]
# spp_taxon <- a$taxon[1]

# report_title == "community"
spp_plot_sizecomp <- a$plot_sizecomp[1]
# spp_plot_agecomp <- a$plot_agecomp[1]
spp_plot_agecomp <- (nrow(agecomp|>
                            dplyr::filter(species_code %in% spp_code)|>
                            dplyr::filter(year %in% analysisyrs) ) >0)
spp_plot_idw <- a$plot_idw[1]
dataTcommF <- FALSE
spp_table_cpue <- FALSE
spp_text <- TRUE

if (report_title == "data") {
  dataTcommF <- TRUE
  spp_table_cpue <- a$table_cpue[1]
  spp_text <- a$text_spp[1]
}

land_start <- "" #felse(spp_table_cpue & report_title == "data", "<!---BLOCK_LANDSCAPE_START--->", "")
land_end <- "" # ifelse(spp_table_cpue & report_title == "data", "<!---BLOCK_LANDSCAPE_STOP--->", "")
show <- FALSE
pagebreak <- ifelse(report_title == "community" & !spp_table_cpue, "", "\\pagebreak")
str0_lang <- ""
```

```{r prep-cite-{{jj}}}

if (report_title == "community") {
  fig_comb <- paste0("\\@ref(fig:", "fig-combined-", spp_file, "-comm)")
}

if (spp_plot_idw) {
  fig_dist <- paste0("\\@ref(fig:", "fig-dist-", spp_file, ifelse(report_title == "data", "-data", "-comm"), ")")
}

if (spp_plot_agecomp) {
  fig_agecomp <- paste0("\\@ref(fig:fig-agecomp-", spp_file, ifelse(report_title == "data", "-data", "-comm"), ")")
} 

if (spp_plot_sizecomp) {
  fig_sizecomp <- paste0("\\@ref(fig:fig-sizecomp-", spp_file, ifelse(report_title == "data", "-data", "-comm"), ")")
} 

if (spp_table_cpue) {
  tab_wt <- paste0("\\@ref(tab:tab-est-", spp_file, "-wt)")
  tab_no <- paste0("\\@ref(tab:tab-est-", spp_file, "-num)")
}

fig_bt <- paste0("\\@ref(fig:fig-temperature-bt-1-", 
                 ifelse(report_title == "data", "data", "comm"),
                 ") and \\@ref(fig:fig-temperature-bt-2-", 
                 ifelse(report_title == "data", "data", "comm"),
                 ")")
fig_st <- "\\@ref(fig:fig-temperature-st-1) and \\@ref(fig:fig-temperature-st-2)"

if (report_title == "community") {
  tab_majorspp_bio <- tab_majortaxa_pchange <- c("\\@ref(tab-majortaxa-pchange-NBS)")
} else if (report_title == "data") {
  tab_majorspp_bio_EBS <- "\\@ref(tab:tab-majortaxa-pchange-EBS)"
  tab_majorspp_bio_NBS <- "\\@ref(tab:tab-majortaxa-pchange-NBS)"
}

# if (report_title == "community") {
tab_stat <- paste0("\\@ref(tab:tab-stats-", spp_file, ")")
# fig_bio <- paste0("\\@ref(fig:fig-biomass-", spp_file, ifelse((report_title %in% c("community")), "-comm", "-data"), ")")
# fig_pop <- paste0("\\@ref(fig:fig-population-", spp_file, ")")
fig_biopop <- fig_timeseries <- paste0("\\@ref(fig:fig-timeseries-", spp_file, ifelse((report_title %in% c("community")), "-comm", "-data"), ")")
# }

str0 <- ""

ref_sap_report <- paste0("[@SAPcrab",maxyr,"]")
```

### `r stringr::str_to_title(spp_print)` `r ifelse(is.na(spp_sci), "", paste0("(",spp_sci,")")) `{#`r spp_file`}

```{r spp-text-0-{{jj}}}
img <- magick::image_read(path = paste0(dir_img, spp_file, "-crop.png")) # read the image using the magic library
fig_width <- 4
fig_height <- (image_info(img)$height * fig_width) / image_info(img)$width
```

```{r spp-text-1-{{jj}}, eval = (report_title %in% "community"), fig.width = fig_width, fig.height = fig_height}
if (fig_height > 4) {
  fig_height <- 3
  fig_width <- (image_info(img)$width * fig_height) / image_info(img)$height
}
cowplot::ggdraw() +
  cowplot::draw_image(readPNG(paste0(dir_img, spp_file, "-crop.png")) )
```

```{r res-spp-lang-{{jj}}}
# Native Languages Names 
temp <- readr::read_csv(file = paste0(dir_out_rawdata, "/species-local-names.csv"), 
                        skip = 1, 
                        show_col_types = FALSE)|>
  dplyr::filter(print_name == spp_print) #|>
# dplyr::select(dplyr::starts_with("lang_"))|>
# dplyr::select_if(~sum(!is.na(.)) > 0)

temp0 <- readr::read_csv(file = paste0(dir_out_rawdata, "/species-local-names.csv"), 
                         show_col_types = FALSE)|>
  # dplyr::select_if(~sum(!is.na(.)) > 0)|>
  head(1)

temp0 <- temp0[which(!is.na(temp))]
temp <- temp[which(!is.na(temp))]

if (report_title == "data") {
  # in data reports, only publish prev sci and common names
  which0 <- which(names(temp) %in% c("lang_scientific_name_prev", "lang_common_name_prev", "lang_common_name_alt"))
} else {
  which0 <- which(grepl(pattern = "lang_", x = names(temp)))
}

temp <- temp[,which0]
names(temp) <- unlist(names(temp0[,which0]))

str0_lang <- ""
if (ncol(temp)>0) {
  str0_lang <- paste0("**", names(temp), "**: ", 
                      ifelse(names(temp) == "Previous scientific name", paste0("*", temp, "*"), temp), 
                      collapse = "\n\n")
  # str0_lang <- paste0(names(temp), ": ", temp, collapse = "\n\n")
}
```

`r str0_lang `

```{r bio-pop-txt-1-{{jj}}, eval = FALSE}
str0 <- ""
```

```{r bio-pop-txt-{{jj}}}
# , eval = (spp_text & (report_title == "data"))
if (report_title == "data") {
cite_bio <- paste0(" (Table",ifelse(spp_table_cpue, "s ", " "), tab_stat,
                   ifelse(spp_table_cpue, paste0(" and ", tab_wt), ""),
                   "; Figs. ", fig_biopop, 
                   ifelse(spp_plot_idw, paste0(" and ", fig_dist), ""), ")")
cite_pop <- paste0(" (Table",ifelse(spp_table_cpue, "s ", " "), 
                   tab_stat,
                   ifelse(spp_table_cpue, paste0(" and ", tab_no), ""),# " and ", tab_no, 
                   "; Fig. ", fig_biopop,")")
} else if (report_title == "community") {
  cite_bio <- paste0(" (Table ", tab_stat, "; Fig. ", fig_comb, ")")
  cite_pop <- paste0(" (Table ", tab_stat, "; Fig. ", fig_comb, ")")
}


load(file = paste0(dir_out_figtab, "tab-stats-", spp_file, ".rdata"))
temp <- obj$raw

str0 <- paste0(#"Between ", compareyr," and ", maxyr, ", ", 
               ifelse(grepl(pattern = "*", x = spp_sci, fixed = TRUE), # is this a group of fishes/organisms?
                      paste0("The estimated biomass of ", spp_print, " "), # true, e.g., 'snailfishes'
                      paste0("The ", spp_print, " biomass estimate "))) # false

if ("EBS" %in% temp$srvy) {
  temp0 <- temp[temp$srvy == "EBS", ]
  
  case <- dplyr::case_when(
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "Not caught") ~ 
      paste0("was ", temp0$`Biomass\n(t)`, " t"), 
    temp0$catch_min < 100 ~ 
      paste0(tolower(strsplit(x = temp0$`Survey Catch Totals`, split = " ", fixed = TRUE)[[1]][1]), 
             " to ", temp0$`Biomass\n(t)`, " t, extrapolated from ", 
             gsub(pattern = paste0(" in ", maxyr), 
                  replacement = " caught", 
                  x = strsplit(x = temp0$`Survey Catch Totals`, split = " to ", TRUE)[[1]][2]) ), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "decrease") ~ 
      paste0("decreased by ", strsplit(split = " ", x = temp0$`Percent Change\nin Biomass`)[[1]][1]), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "increase") ~ 
      paste0("increased by ", strsplit(split = " ", x = temp0$`Percent Change\nin Biomass`)[[1]][1]),
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "no change") ~ 
      "did not notably change"
  )
  
  case_transition_ebs <- dplyr::case_when(
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "Not caught") ~ paste0(""), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "decrease") ~ paste0("decrease"), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "increase") ~ paste0("increase"),
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "no change") ~ "no change"
  )
  
  str0 <- paste0(str0, 
                 case, 
                 " on the ", maxyr, " eastern Bering Sea Shelf survey from ", compareyr[names(compareyr) == "EBS"], cite_bio, 
                 " and the population was estimated at ",
                 temp0$Population," individuals",cite_pop,". ")
}

if ("NBS" %in% temp$srvy) {
  temp0 <- temp[temp$srvy == "NBS", ]
  
  case <- dplyr::case_when(
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "Not caught") ~ 
      paste0("was ", temp0$`Biomass\n(t)`, " t"), 
    temp0$catch_min < 100 ~ 
      paste0(tolower(strsplit(x = temp0$`Survey Catch Totals`, split = " ", fixed = TRUE)[[1]][1]), 
             " to ", temp0$`Biomass\n(t)`, " t, extrapolated from ", 
             gsub(pattern = paste0(" in ", maxyr), 
                  replacement = " caught", 
                  x = strsplit(x = temp0$`Survey Catch Totals`, split = " to ", TRUE)[[1]][2]) ), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "decrease") ~ 
      paste0("decreased by ", strsplit(split = " ", x = temp0$`Percent Change\nin Biomass`)[[1]][1]), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "increase") ~ 
      paste0("increased by ", strsplit(split = " ", x = temp0$`Percent Change\nin Biomass`)[[1]][1]),
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "no change") ~ 
      "did not notably change"
  )
  
  case_transition_nbs <- dplyr::case_when(
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "Not caught") ~ paste0(""), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "decrease") ~ paste0("decrease"), 
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "increase") ~ paste0("increase"),
    grepl(x = temp0$`Percent Change\nin Biomass`, pattern = "no change") ~ "no change"
  )
  
  if (!("EBS" %in% temp$srvy)) { # if there is no EBS data and therefore nothing to 'transition' to, = ""
    str0_transition <- ""
  } else if (case_transition_nbs == case_transition_ebs) {
    str0_transition <- "Similarly, the "
    cite_bio <- ""
    cite_pop <- ""
  } else {
    str0_transition <- "The " # "However, "
    cite_bio <- ""
    cite_pop <- ""
  }
  
  str0 <- paste0(str0, str0_transition, 
                 "biomass estimate ", case,  
                 " on the ", maxyr, " northern Bering Sea Shelf survey from ", compareyr[names(compareyr) == "NBS"], cite_bio, 
                 " and the population was estimated at ",
                 temp0$Population," individuals", cite_pop,". ")
}

if (nrow(temp) == 1 & length(srvy11)==2) { # temp$srvy_long %in% stringr::str_to_title(srvy11)
  str0 <- paste0(str0, 
                 "No ", spp_print, " were observed in the ", 
                 srvy11[!(stringr::str_to_title(srvy11) %in% temp$srvy_long)], 
                 " in ",maxyr,"  (Fig. ", fig_dist,"). ")
}
```

`r str0`

```{r spp-text-{{jj}}, child = paste0(dir_out_rawdata, spp_file,".Rmd"), eval=(spp_text), results='asis'}
```

```{r tab-stats-{{jj}}}
nickname <- paste0("tab-stats-", spp_file)
```

```{r tab-stats-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

<!-- `r pagebreak` -->

```{r fig-timeseries-{{jj}}}
nickname <- paste0("fig-timeseries-", spp_file, ifelse(report_title == "data", "-data", "-comm"))
```

```{r fig-timeseries-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (report_title %in% "data")}
```

```{r fig-dist-{{jj}}}
nickname <- paste0("fig-dist-", spp_file, ifelse(report_title == "data", "-data", "-comm"))
```

```{r fig-dist-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (report_title %in% "data" & spp_plot_idw)}
```

<!-- `r pagebreak` -->

```{r fig-sizecomp-{{jj}}}
nickname <- paste0("fig-sizecomp-", spp_file, ifelse(report_title == "data", "-data", "-comm"))
```

```{r fig-sizecomp-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (report_title %in% "data" & spp_plot_sizecomp) }
```

```{r}
# keeping for later if we choose to use the age comp figures

# <!-- `r pagebreak` -->
#
# ```{r fig-agecomp-{{jj}}}
# nickname <- paste0("fig-agecomp-", spp_file, ifelse(report_title == "data", "-data", "-comm"))
# ```
# 
# ```{r fig-agecomp-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = spp_plot_agecomp}
# ```
```

```{r fig-combined-{{jj}}}
nickname <- paste0("fig-combined-", spp_file, "-comm")
```

```{r fig-combined-{{jj}}-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = (report_title %in% "community") }
```

<!-- `r land_start ` -->

`r ifelse(spp_table_cpue, "\\pagebreak", "")`

```{r tab-est-{{jj}}-wt}
nickname <- paste0("tab-est-", spp_file, "-wt")
```

```{r tab-est-{{jj}}-wt-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = spp_table_cpue}
```

`r ifelse(spp_table_cpue, "<br>", "")`

```{r tab-est-{{jj}}-num}
nickname <- paste0("tab-est-",spp_file, "-num")
```

```{r tab-est-{{jj}}-num-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval = spp_table_cpue}
```

<!-- `r land_end ` -->
