
\pagebreak

# Appendices

# (APPENDIX) Appendices {-}

<!-- https://stackoverflow.com/questions/51335125/adding-figures-and-tables-after-bibliography-in-rmarkdown -->

```{r}
## Appendix A: Station and catch data
# 
# Appendix A contains station data by vessel for the `r text_list(paste0(haul_cruises_maxyr$stations_avail, " standard survey stations that were successfully completed in the ",haul_cruises_maxyr$SRVY))`. When using the tables, the following parameters should be noted:
# 
#    - Time represents the nearest hour and minute at the start of the haul in Alaska Daylight Time (ADT)
#    
#    - Haul numbers are not always sequential because unsatisfactory hauls were omitted.
#    
#    - All start and end longitudes and latitudes for each haul are displayed as degrees and decimal minutes.
#    
#    - Net measured codes are as follows: Y = Net width was measured by net mensuration gear. N = Net width was estimated from a function of inverse scope (wire out) and net height.
#    
#    - Catch weights are displayed in total kilograms.
# 
# **List of Tables**
# 
# `r text_list(paste0("\n\n - A ", sapply(list_tables[grepl(x = names(list_tables), pattern = "tab_app_hauls_catch_")],"[[","header")), oxford = FALSE, sep = " ", sep_last = " ") `
# 
# <!---BLOCK_LANDSCAPE_START--->
# 
# `r NMFSReports::crossref(list_obj = list_tables, nickname = "tab_app_hauls_catch_", sublist = "res", exact = FALSE) `
# 
# <!---BLOCK_LANDSCAPE_STOP--->
# 
# ## Appendix A: List of taxa encountered
# 
# Appendix A lists all fish and invertebrate taxa taken during the AFSC’s `r text_list(paste0(haul_cruises_maxyr$SRVY)) ` bottom trawl survey.
# 
# **List of Tables**
# 
# `r text_list(paste0("\n\n - Appendix B ", sapply(list_tables[grepl(x = names(list_tables), pattern = "tab_app_taxa_encountered_")],"[[","header")), oxford = FALSE, sep = " ", sep_last = " ") `
# 
# `r NMFSReports::crossref(list_obj = list_tables, nickname = "tab_app_taxa_encountered_", sublist = "res", exact = FALSE) `
# 
# ## Appendix B: List of taxa encountered
# 
# Appendix A lists all fish and invertebrate taxa taken during the AFSC’s `r text_list(paste0(haul_cruises_maxyr$SRVY)) ` bottom trawl survey.
# 
# **List of Tables**
# 
# `r text_list(paste0("\n\n - Appendix B ", sapply(list_tables[grepl(x = names(list_tables), pattern = "tab_app_taxa_encountered_")],"[[","header")), oxford = FALSE, sep = " ", sep_last = " ") `
# 
# `r NMFSReports::crossref(list_obj = list_tables, nickname = "tab_app_taxa_encountered_", sublist = "res", exact = FALSE) `
# 
# 
# ## Appendix C: Population estimates by sex and size group for principal fish species
# 
# Appendix C presents population estimates by sex and size group from the `r maxyr` `r text_list(paste0(haul_cruises_maxyr$SRVY))` survey`r ifelse(length(haul_cruises_maxyr$SRVY)>1, "s", "")` for principal fish species.
# 
# **List of Tables**
# 
# `r text_list(paste0("\n\n - Appendix C ", sapply(list_tables[grepl(x = names(list_tables), pattern = "tab_app_principal_fish_")],"[[","header")), oxford = FALSE, sep = " ", sep_last = " ") `
# 
# `r NMFSReports::crossref(list_obj = list_tables, nickname = "tab_app_principal_fish_", sublist = "res", exact = FALSE) `
# 
```


```{r list_app_function}
counter_letters <- 0

list_app <- function(nickname, dir_out_tables, abcd, srvy, descr_short, descr_frag) {
  
  a <- list.files(path = dir_out_tables, 
                  pattern = nickname, 
                  full.names = FALSE)
  
  nickname0 <- gsub(pattern = ".rdata",  
                    replacement = "", 
                    x = a[grepl(pattern = ".rdata", x = a)], 
                    ignore.case = TRUE)
  
  captions <- data.frame()
  for (i in 1:length(nickname0)) {
    a <- readtext(paste0(dir_out_tables, nickname0[i], ".txt"))
    captions <- dplyr::bind_rows(
      captions, 
      data.frame(
        "id" = nickname0[i], 
        "capt" = a$text))
  }
  
#   src <- list()
# for (jj in 1:length( unique(report_spp1$file_name)[!is.na(unique(report_spp1$file_name))] )) {
#   print(jj)
#   src[[jj]] <- knitr::knit_expand(paste0(dir_code, '06_results_spp.Rmd'))
# }
# # You can also do it using lapply (I wanted the for loop though because I'm setting a bunch of params)
# # src <- lapply(cyl.vec, function(cylcode){
# #   knitr::knit_expand(here::here('markdown','Template.Rmd'))
# # })
# res = knitr::knit_child(text = unlist(src), quiet = TRUE)
# cat(res, sep = '\n')
  
  # list_tables0 <- list_tables[grepl(x = names(list_tables), pattern = nickname0)]
  # srvy <- unlist(unique(lapply(X = strsplit(x =
  #                                             gsub(pattern = nickname,
  #                                                  replacement = "",
  #                                                  x = nickname0), split = "-"),
  #                              `[[`, 1)))
  
  # abcd <- unique(gsub(pattern = "[0-9]+", 
  #                     replacement = "", 
  #                     x = unlist(lapply(list_tables0, `[[`, "number"))))
  
  # str0 <- ""
  
  # for (i in 1:length(abcd)) {
    
    # nickname00 <- nickname0[grepl(x = nickname0, pattern = srvy[i])]
    # unlist(lapply(list_tables0, `[[`, "number"))
    
    str0 <- paste0(#ifelse(str0 == "", "", "\\pagebreak"), 
                   '## Appendix ',abcd,': List of ', descr_short,'

Appendix ',abcd, " ", descr_frag, '

**List of Tables**

',
text_list(paste0("\n\n - Appendix ", "\\@ref(tab:", captions$id, "): ", captions$capt),
                 # sapply(list_tables00, #[grepl(x = names(list_tables00), pattern = "tab_app_taxa_encountered_")], "[[","header")), 
          oxford = FALSE, sep = " ", sep_last = " "),
'
\n\n\n
'#, 
# NMFSReports::crossref(list_obj = list_tables00, 
#                       nickname = "", 
#                       sublist = "res", exact = FALSE),
# '
# \n\n\n
# '
    )
  # }
}
```

```{r tab-app-taxa-encountered-EBS}
nickname <- "tab-app-taxa-encountered-EBS"
str0 <- list_app(nickname = nickname, 
                 dir_out_tables = dir_out_tables, 
                 abcd = "A", 
                 descr_short = "taxa encountered in the eastern Bering Sea", 
                 descr_frag = paste0("lists all fish and invertebrate taxa taken during the AFSC’s eastern Bering Sea bottom trawl survey."))
```

`r str0 `

```{r setup1, include=FALSE}
knitr::opts_chunk$set(tab.cap.pre = abcd)
```

```{r tab-special-projects-EBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

\pagebreak

```{r tab-app-taxa-encountered-NBS}
if (SRVY == "NEBS") {
  evalTF <- TRUE
  nickname <- "tab-app-taxa-encountered-NBS"
abcd <- LETTERS[counter_letters + 1]
str0 <- list_app(nickname = nickname, 
                 dir_out_tables = dir_out_tables, 
                 abcd = abcd, 
                 descr_short = "taxa encountered in the northern Bering Sea", 
                 descr_frag = paste0("lists all fish and invertebrate taxa taken during the AFSC’s northern Bering Sea bottom trawl survey."))
}
```

`r str0 `

```{r tab-special-projects-NBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval=evalTF}
```

\pagebreak

```{r tab-app-principal-fish-EBS-}
nickname <- "tab-app-principal-fish-EBS-"
abcd <- LETTERS[counter_letters + 1]
str0 <- list_app(nickname = nickname, 
                 dir_out_tables = dir_out_tables, 
                 abcd = abcd, 
                 descr_short = "population estimates by sex and size group for principal fish species in the eastern Bering Sea", 
                 descr_frag = paste0("presents population estimates by sex and size group from the ", 
                                     maxyr,
                                     " eastern Bering Sea bottom trawl survey for principal fish species."))
```

`r str0 `

```{r tab-app-principal-fish-EBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd")}
```

\pagebreak

```{r tab-app-principal-fish-NBS-}
if (SRVY == "NEBS") {
  evalTF <- TRUE
nickname <- "tab-app-principal-fish-NBS-"
abcd <- LETTERS[counter_letters + 1]
str0 <- list_app(nickname = nickname, 
                 dir_out_tables = dir_out_tables, 
                 abcd = abcd, 
                 descr_short = "population estimates by sex and size group for principal fish species in the northern Bering Sea", 
                 descr_frag = paste0("presents population estimates by sex and size group from the ", 
                                     maxyr,
                                     " northern Bering Sea bottom trawl survey for principal fish species."))
}
```

`r str0 `

```{r tab-app-principal-fish-NBS-child, child = paste0(dir_code, "_child_report_figtab.Rmd"), eval=evalTF}
```

\pagebreak

```{r tab_app_principal_fish_}
# nickname0 <- "tab_app_principal_fish_"
# 
# list_tables0 <- list_tables[grepl(x = names(list_tables), pattern = nickname0)]
# srvy <- unlist(unique(lapply(X = strsplit(x =
#                                             gsub(pattern = nickname0,
#                                                  replacement = "",
#                                                  x = names(list_tables0)), split = "_"),
#                              `[[`, 1)))
# abcd <- unique(gsub(pattern = "[0-9]+", 
#                     replacement = "", 
#                     x = unlist(lapply(list_tables0, `[[`, "number"))))
# 
# str0 <- ""
# 
# for (i in 1:length(abcd)) {
#   
#   list_tables00 <- list_tables0[grepl(x = names(list_tables0), pattern = srvy[i])]
#   
#   str0 <- paste0(str0, ifelse(str0 == "", "", "\\pagebreak"), 
#                  '## Appendix',abcd[i],
#                  ': Population estimates by sex and size group for principal fish species in the ', srvy[i], '
# 
# Appendix ',abcd[i],' presents population estimates by sex and size group from the ', maxyr,' ',
# srvy[i] , ' bottom trawl survey for principal fish species. 
# 
# **List of Tables**
# 
# ',
# text_list(paste0("\n\n - Appendix ",#abcd[i]," ", 
#                  sapply(list_tables00, #[grepl(x = names(list_tables00), pattern = "tab_app_taxa_encountered_")],
#                         "[[","header")), 
#           oxford = FALSE, sep = " ", sep_last = " "),
# '
# \n\n\n
# '#, 
# # NMFSReports::crossref(list_obj = list_tables00, 
# #                       nickname = "", 
# #                       sublist = "res", exact = FALSE),
# # '
# # \n\n\n
# # '
#   )
# }

```
