---
output:
  word_document:
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: styles_reference.docx
    df_print: kable
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

#### Biomass, Abundance, Distribution and CPUE of Other Fish Taxa

Total biomass and population size were estimated for an additional 24 fish species that were common in either the `r SRVY ` and NBS or both (Tables 18 to 19). For each of the 24 species, there is a corresponding map showing the geographic distribution and relative abundance (Figures 29 to 53). 

#### Spatial Distribution of Selected Invertebrates

Plots of the broad spatial distribution patterns for eight major invertebrates on the combined `r SRVY ` and NBS continental shelf are presented in Figures 54 to 61. The purple sea star, (Asterias amurensis), is common in the Bering and Chukchi Seas (Hamizaki et al. 2005, Feder et al. 2005) and it was the invertebrate taxon with the highest ranked catch rate by weight in both the `r SRVY ` and NBS. Catch rates for the purple sea star were highest in the middle shelf between the Pribilof Islands and Nunivak Island and along the inner shelf from Bristol Bay to the Bering Strait (Figure 61). 

Figures 54 to 57 show the shelf-wide distributions of the four major commercial crab species: blue king crab, red king crab, snow crab (Chionoecetes opilio), and Tanner crab (Chionoecetes bairdi). Commercial crab stocks are managed by the ADF&G with federal oversight by NMFS. For more detailed information on BT survey results for commercial crab refer to Chilton et al. (2011), and for the most recent modeling data on the status of these commercial crab stocks, refer to the annual Stock Assessment and Fishery Evaluation report prepared by the NPFMC. 





> From NBS report, for Ocean Conditions section

Bottom temperature is a major environmental driver that can affect the distribution of fishes, crabs, and other invertebrates on the shelf (Figures `r crossref(list_obj = list_figures, nickname = 'fig_mean_temperature', sublist = 'number')` and `r crossref(list_obj = list_figures, nickname = 'fig_cold_pool_area', sublist = 'number')`). Using the long-term time series of bottom temperatures from the EBS shelf survey as reference, the years 2006-2013 were colder than average ("cold stanza") and the years 2002-2005 and 2014-2019 were warmer than average ("warm stanza"). During the `r haul_cruises_maxyr$yrofsurvey[haul_cruises_maxyr$SRVY == "EBS"] `-year time series (1982–`r maxyr`) of the annual EBS shelf bottom trawl survey, mean summer bottom temperatures were variable, ranging from `r round(min(temps_avg_yr$bt), digits = 1)`°C (`r round(c2f(min(temps_avg_yr$bt)), digits = 1)`°F) to `r round(max(temps_avg_yr$bt), digits = 1)`°C (`r round(c2f(max(temps_avg_yr$bt)), digits = 1)`°F), with a grand mean for all years of `r round(temps_avg_yr$bt_mean[1], digits = 1)`°C  (`r round(c2f(temps_avg_yr$bt_mean[1]), digits = 1)`°F) (Figure `r crossref(list_obj = list_figures, nickname = 'fig_mean_temperature', sublist = 'number')`).

`r list_figures$fig_mean_temperature$res`

`r list_figures$fig_cold_pool_area$res`
