---
output:
  word_document:
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: styles_reference.docx
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography_RPack.bib"
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

</br>

## Acknowlegements

Recognition and appreciation is extended to the captains and crew of the *FV Alaska Knight* and *FV Vesteraalen*. Without their expertise, goodwill, and sacrifice, this survey would not be possible. Thank you to the United States Seafoods and Vesteraalen LLC for making the vessels available and always maintaining safety as a top priority. Great appreciation is also extended to all the scientists, researchers, contractors, interns, and volunteers who worked tirelessly aboard each vessel to complete the survey in a safe and successful manner. Thanks also to Norton Sound Economic Development Corporation and Kawerak, Inc. The survey would not have been possible without the major contributions from other AFSC groups including the Net Shed, Research Survey Support Team, Data Management Group, and the Administrative team. Finally, appreciation is extended to the reviewers of this document whose excellent comments and suggestions greatly improved it. 


</br>

## ORCID

> First Last (ORCID#)



\newpage


## Works Cited

</br>

### Recent Technical Memorandums
  
  @RN946 <!-- An evaluation of methods used to predict commercial fishing effort in Alaska -->
  
  @RN964 <!-- Alternative sampling designs for the 2019 Annual Deployment Plan of the North Pacific Observer Program -->
  
  @RN948 <!-- Alaska marine mammal stock assessments, 2019 -->
  
  @RN970 <!-- 3Human-caused mortality and injury of NMFS-managed Alaska marine mammal stocks 2013-2017 -->
  
  @RN951 <!-- Genetic stock composition analysis of the Chinook salmon bycatch samples from the 2017 Bering Sea trawl fisheries -->
  
  @RN961 <!-- Genetic stock composition analysis of Chinook salmon bycatch samples from the 2018 Gulf of Alaska trawl fisheries -->
  
  @RN952 <!-- Assessment and Catalog of Benthic Marine Algae from the Alaska Peninsula May 2016 -->
  
  @RN953 <!-- Freshwater Input to the Bering Sea, 1950–2017, 46 p. NTIS No. PB2019100329. -->
  
  @RN955 <!-- Report on the 2018 International Sablefish Workshop, 107 p. NTIS No. PB2019-100329. -->
  
  @RN908 <!-- The 2018 eastern Bering Sea continental shelf and northern Bering Sea trawl surveys: Results for commercial crab species. -->
  
  @RN957 <!-- Abundance and seasonality of Dall’s porpoise (Phocoenoides dalli) in Southeast Alaska -->

</br>

### R Packages

<div id="refs"></div>

</br>


### Works Cited

<!-- Note that when the report is compiled, all of the citations from the rest of the report will naturally come to the end of this page.  -->
