---
title: "`r maxyr` Fisheries Survey: What did they find?"
subtitle: "`r str `"
author: 
- affiliation: Resource Assessment & Conservation Engineering Division
  description: Groundfish Assessment Program
  email: Duane.Stevenson@noaa.gov
  name: Duane Stevenson
bibliography: "../cite/bibliography.bib"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  powerpoint_presentation:
    reference_doc: styles_reference.pptx
    slide_level : 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  message = FALSE,
  #   dev = "svg",
  fig.width = 12,
  fig.height = 12
  # fig.retina = 3
)
```



```{r}
i<-0
```

## `r names(list_tables)[i+1] `

```{r}
i<-i+1
list_tables[i][[1]]$print
```


## `r names(list_tables)[i+1] `

```{r}
i<-i+1
list_tables[i][[1]]$print
```

## `r names(list_tables)[i+1] `

```{r}
i<-i+1
list_tables[i][[1]]$print
```

## `r names(list_tables)[i+1] `

```{r}
i<-i+1
list_tables[i][[1]]$print
```



```{r print_fig}

list_figures1 <- data.frame(nickname = 
                              gsub(pattern = "_", replacement = " ", 
                                   gsub(pattern = "fig_", replacement = "", x = names(list_figures), 
                                        fixed = TRUE), fixed = TRUE), 
                            header = as.character(lapply(list_figures, `[[`, 'header')), 
                            filename = paste0(dir_out_figures, lapply(list_figures, `[[`, 'filename'), '.png'))

list_figures1$title <- stringr::str_to_title(gsub(pattern = "idw ", replacement = "", x = 
                                                    gsub(pattern = "size dist ", replacement = "", 
                                                         x = list_figures1$nickname)))


insert <- c()
for (i in 1:nrow(list_figures1)){
  insert <- paste0(insert, 
                     paste(paste0("## ", list_figures1$title[i], 
                     "\n\n![*", list_figures1$header[i], "*](",
                     list_figures1$filename[i], ")\n\n", collpase = ""),
              sep = "", collapse = ""))
}

```

`r insert `


```{r print_spp_img}
insert <- c()
aa<-report_spp1$file_name[report_spp1$plot_idw_coldwarm == TRUE | report_spp1$plot_idw == TRUE ]
for (i in 1:length(unique( aa ))){
      insert <- paste0(insert, 
                     paste(paste0("## ", stringr::str_to_sentence(report_spp$print_name[i]), 
                     "\n\n![*", report_spp$print_name[i], "*](",
                     paste0(dir_img, report_spp$file_name[i], ".png"), ")\n\n", collpase = ""),
              sep = "", collapse = ""))
}

```

`r insert `



