
# Introduction

```{r}
# use haul_cruises_maxyr TOLEDO 

temp <- haul_cruises_maxyr %>%
  dplyr::filter(SRVY == "EBS") #%>% 
  # dplyr::mutate(start_mo_long = format(x = as.POSIXlt(x = start_date_haul ), format="%B")) %>%
  # dplyr::mutate(end_mo_long = format(x = as.POSIXlt(x = end_date_haul ), format="%B")) #%>%
  # dplyr::select(start_mo_long, end_mo_long)

nbs_insert <- ifelse(SRVY == "NEBS", 
                      #NBS
                      paste0("In addition, the ", maxyr, 
                             " survey coverage was expanded to include the northern Bering Sea. This is only the ", 
                             NMFSReports::numbers2words_th(
                               haul_cruises_maxyr %>% 
                                 dplyr::filter(SRVY == "NBS") %>%
                                 dplyr::select(yrofsurvey )),
                             " time since 2010 that the northern Bering Sea survey was done. The expanded study area covered the entire Bering Sea continental shelf (hereafter referred to as the “northern Bering Sea”) from 20 m (",
                             round(20/divmforft, 1),
                             " ft) to 200 m (",
                             round(200/divmforft, 1),
                             " ft) bottom depth to the U.S.-Russia Maritime Boundary between the Alaska Peninsula and the Bering Strait, including Norton Sound."), 
                             # EBS
                             "The study area covered the eastern Bering Sea continental shelf from 20 to 200 m bottom depth to the U.S.-Russia Maritime Boundary between the Alaska Peninsula and to approximately the latitude of St. Matthew Island (60° 50' N).")


if (sum(haul_cruises_maxyr$stations_avail == haul_cruises_maxyr$stations_completed) == 1) { # diff answers or only 1 srvy
  temp_insert <- CapFirst(NMFSReports::text_list(
    paste0(ifelse(haul_cruises_maxyr$stations_avail ==
                    haul_cruises_maxyr$stations_completed, "all", "most"), 
           " survey stations in the ", 
           haul_cruises_maxyr$SRVY, 
           " were sampled successfully")))
} else { # answers both "Most" or "All"
  temp_insert <- paste0(unique(ifelse(haul_cruises_maxyr$stations_avail ==
                    haul_cruises_maxyr$stations_completed, "All", "Most")), 
           " survey stations in the ",
           NMFSReports::text_list(haul_cruises_maxyr$SRVY), 
           " were sampled successfully")
} 
```

In `r maxyr`, NOAA Fisheries' Alaska Fisheries Science Center conducted two surveys within U.S. territorial waters of the Bering Sea: the eastern Bering Sea shelf bottom trawl survey and the northern Bering Sea bottom trawl survey. This is the `r haul_cruises_maxyr$yrofsurvey[haul_cruises_maxyr$SRVY == "EBS"] ``r haul_cruises_maxyr$stndth[haul_cruises_maxyr$SRVY == "EBS"] ` year of the eastern Bering Sea shelf survey and the `r NMFSReports::numbers2words_th(haul_cruises_maxyr$yrofsurvey[haul_cruises_maxyr$SRVY == "NBS"]) ` year of northern Bering Sea survey using standardized sampling protocols. A rapid response survey for the northern Bering Sea region was also conducted in 2018 using a modified spatial extent and sampling procedure and will not be covered here. The northern Bering Sea survey region contains `r haul_cruises_maxyr$stations_avail[haul_cruises_maxyr$SRVY == "NBS"] ` stations in an area bounded by the Bering Strait, Norton Sound, and the U.S.–Russia Maritime Boundary (Fig. `r NMFSReports::crossref(list_obj = list_figures, nickname = "fig_sample_grid", sublist = "number") `).

This region is a fundamental part of the Alaska Fisheries Science Center Loss of Sea Ice (LOSI) research plan, the primary purpose of which is to study the impacts of diminished sea ice on the marine ecosystem. In the NOAA LOSI research plan, the northern Bering Sea was identified as a region of critical importance for increased scientific monitoring because this marine ecosystem may be rapidly altered by the changing climate. This survey represents one component of a multi-faceted research plan to create a long-term time series designed to track environmental and ecological change throughout the Bering Sea. Beyond the potential impacts of climate change, the scale and extent of fish and crab movements may also vary from year to year in response to a variety of biological or environmental processes. These movements cause changes in distribution and abundance that extend beyond the traditional survey boundaries. 

Here, we provide some of the results of the `r maxyr` northern Bering Sea survey and compare these to observations from the `r NMFSReports::text_list(nbsyr[nbsyr != maxyr])` surveys. Continuation of the survey effort for a combined eastern Bering Sea and northern Bering Sea bottom trawl survey will provide more comprehensive information to investigate how fishes, crabs, and other bottom dwellers respond to biological and environmental changes on a large spatial scale over a multi-year time period. 

`r list_figures$fig_sample_grid$res `

