---
output:
  officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r vars}
a <- report_spp1[which(report_spp1$file_name == comb[jj]), ]

spp_file <- a$file_name[1]
spp_sci <- text_list(unique(a$species_name))
spp_sci <- ifelse(spp_file == "tunicates", "Tunicata", text_list(unique(a$species_name))) # TOLEDO

spp_print <- a$print_name[1]
spp_taxon <- a$taxon[1]
spp_code <- a$species_code

# report_title == "community"
spp_plot_sizecomp <- (nrow(sizecomp |> 
                             dplyr::filter(species_code %in% spp_code) |> 
                             dplyr::filter(year %in% analysisyrs) ) >0)
spp_plot_agecomp <- (nrow(agecomp |>
                            dplyr::filter(species_code %in% spp_code) |>
                            dplyr::filter(year %in% analysisyrs) ) >0)
spp_plot_idw <- a$plot_idw[1]
spp_table_cpue <- a$table_cpue[1]

spp_bin <- eval(expr = parse(text = a$dist_bin))
```

```{r fig-spp}
header <- spp_file
nickname <- paste0("fig-icon-", spp_file, "-pres")
height <- width <- 5

pres_spp <- figure_print <- 
  cowplot::ggdraw() +
  cowplot::draw_image(readPNG(paste0(dir_img, spp_file, "-crop.png")) )

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-dist-[spp]-prep}

dist_plot <- function(yrs, height, row0, nickname, report_title0, spp_print, spp_code) {
  
  width <- full_page_portrait_width # 6.5  
  case_yr0 <- 1
  place_labels <- FALSE
  viridis_palette_option <- "mako"
  
  yrs <- sort(yrs, decreasing = TRUE)
  if (report_title0 == "pres") {
    key.title <- 'CPUE (kg/km²)'
  } else {
    key.title <- paste0(stringr::str_to_title(spp_print),
                        '\n', 
                        'CPUE (kg/km²)')
  }
  # Select data ------------------------------------------------------------------
  if (length(spp_code) > 1) {
    table_raw <- cpue |>
      dplyr::filter(common_name %in% spp_print)
  } else {
    table_raw <- cpue |>
      dplyr::filter(species_code %in% spp_code)
  }
  
  table_raw <- table_raw |> 
    dplyr::mutate(cpue_kgkm2 = ifelse(is.na(cpue_kgkm2), 0, cpue_kgkm2)#,
                  # HAUL = NA
    ) |>
    dplyr::filter(
      srvy %in% srvy1 &
        year %in% yrs) |> 
    dplyr::arrange(desc(year)) |>
    dplyr::select(survey_definition_id, 
                  srvy,
                  LATITUDE = latitude_dd_start,
                  LONGITUDE = longitude_dd_start,
                  CPUE_KGHA = cpue_kgkm2, 
                  YEAR = year) |> 
    dplyr::mutate(COMMON_NAME = spp_print) |> 
    dplyr::ungroup() |> 
    data.frame()
  
  # is one of the areas zero-filled that for this subset, doesn't need to be?
  # needs to be clean here so the downstream code picks the right map.area extent
  temp <- table_raw |> 
    dplyr::group_by(srvy) |> 
    dplyr::summarise(maxcpue = max(CPUE_KGHA, na.rm = TRUE))
  
  if (0 %in% temp$maxcpue) {
    table_raw <- table_raw |> 
      dplyr::filter(!(srvy %in% temp$srvy[temp$maxcpue == 0]))
  }
  
  # Find set.breaks --------------------------------------------------------------
  if (!(NA %in% spp_bin) ) {
    # if (spp_bin[1] > max(table_raw$CPUE_KGHA)) {
    #   set.breaks <- c(0, max(table_raw$CPUE_KGHA))
    # } else {
    spp_bin <- spp_bin[!(spp_bin > max(table_raw$CPUE_KGHA))]
    if (length(spp_bin)>0) {
      set.breaks <- c(0, spp_bin, max(table_raw$CPUE_KGHA))
    } else {
      set.breaks <- c(0, max(table_raw$CPUE_KGHA))
    }
    # }
  } else {
    set.breaks <- akgfmaps::eval_plot_breaks(CPUE = table_raw$CPUE_KGHA, n.breaks = 5)
    set.breaks <- as.vector(unlist(set.breaks[set.breaks$style == "pretty", -1]))
  }
  
  set.breaks_pretty0 <- formatC(x = set.breaks, big.mark = ",", format = "f", digits = 0)
  set.breaks_pretty <- set.breaks_pretty0
  set.breaks_pretty[1] <- "No catch"
  for (i in 2:length(set.breaks_pretty)) {
    set.breaks_pretty[i] <- paste0(">", set.breaks_pretty0[i-1], "-", set.breaks_pretty0[i])
  }
  
  # find appropriate map.area0 ---------------------------------------------------
  # only if both species are only found in prt of the region, change the extrp.box
  map.area0 <- map.area
  reg_dat0 <- reg_dat
  if (length(unique(table_raw$srvy))==1 & srvy == "NEBS") { # is this species in only 1 of the 2 survey areas (when srvy == NEBS)?
    map.area0 <- ifelse(unique(table_raw$srvy) == "EBS", "bs.south", "bs.north")
    reg_dat0 <- report_types[[unique(table_raw$srvy)]]$reg_dat
    if (report_title0 != "pres") {
      height <- ifelse(reg_dat0$survey.area$srvy == "EBS" & 
                         report_title0 == "data", height, height-1)
    }
  }
  
  # The figure is too small for too many details like this
  if (report_title0 == "pres") {
    # reg_dat0$lon.breaks <- as.character(reg_dat0$lon.breaks)
    reg_dat0$lon.breaks <- reg_dat0$lon.breaks[which(reg_dat0$lon.breaks %% 10 != 5)] 
  }
  
  # Write header for figure_print ------------------------------------------------------
  missing_from_one_but_not_both_surveys <- ""
  if (srvy == "NEBS") {
    if (length(unique(table_raw$srvy)) == 1) {
      missing_from_one_but_not_both_surveys <- paste0("This species was not encountered in the ", 
                                                      range_text(yrs), " ",
                                                      haul_cruises_maxyr$srvy_long[haul_cruises_maxyr$srvy !=
                                                                                     unique(table_raw$srvy)], 
                                                      " survey", ifelse(length(yrs)>1, "s", ""), 
                                                      ". ")
    }
  }
  header <- paste0("CPUE (kg/km^2^) distribution of ", 
                   spp_print, 
                   # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
                   " from the ",
                   range_text(yrs), " ", 
                   SURVEY, 
                   " survey", 
                   ifelse(length(unique(table_raw$srvy))>1, "s", ""), ". ", 
                   missing_from_one_but_not_both_surveys
  )
  
  # find which years need to be prepared with which region # crude, but here we are
  a <- table_raw |>
    dplyr::select(YEAR, survey_definition_id) |>
    dplyr::distinct()  |>
    dplyr::mutate(survey_definition_id = dplyr::case_when(
      survey_definition_id == 98 ~ "EBS",
      survey_definition_id == 143 ~ "NBS")) |>
    tidyr::pivot_wider(id_cols = YEAR,
                       names_from = survey_definition_id,
                       values_from = survey_definition_id)
  if (ncol(a)<3) {
    a$case <- unlist(a[,2])
  } else {
    a <- a |> 
      dplyr::mutate(
        case = dplyr::case_when(
          !is.na(EBS) & !is.na(NBS) ~ "both", 
          !is.na(EBS) ~ "EBS", 
          !is.na(NBS) ~ "NBS"
        ))
  }
  
  # dummy empty data
  temp <- table_raw |> 
    dplyr::filter(YEAR == max(nbsyr)) |> 
    dplyr::mutate(CPUE_KGHA = 0, 
                  CPUE_NOKM2 = 0)
  
  if (map.area0 == "bs.all") {
    if ("NBS" %in% a$case) {
      for (i in which(a$case %in% "NBS")){
        table_raw <- table_raw |> 
          dplyr::bind_rows(temp |> 
                             dplyr::filter(srvy == "EBS") |> 
                             dplyr::mutate(YEAR = a$YEAR[i]))
      }}
    
    if ("EBS" %in% a$case) {
      for (i in which(a$case %in% "EBS")){
        table_raw <- table_raw |> 
          dplyr::bind_rows(temp |> 
                             dplyr::filter(srvy == "NBS") |> 
                             dplyr::mutate(YEAR = a$YEAR[i]))
      }}
  }
  
  # Create shapefile of species IDW ----------------------------------------------
  
  idw <- make_idw_stack(
    x = table_raw,
    region = map.area0, 
    grouping.vars = "YEAR", 
    set.breaks = set.breaks,
    out.crs = out.crs, 
    extrapolation.grid.type = "sf")
  
  # remove predictions from areas that were not surveyed
  if (map.area0 == "bs.all") {
    if ("NBS" %in% a$case) {
      idw$extrapolation.stack <- dplyr::bind_rows(
        idw$extrapolation.stack |>
          dplyr::filter(YEAR %in% a$YEAR[a$case != "NBS"]),
        idw$extrapolation.stack |> 
          dplyr::filter(YEAR %in% a$YEAR[a$case == "NBS"]) |> 
          sf::st_difference(y = reg_dat$survey.area[reg_dat$survey.area$survey_definition_id == 98,]) )
    }
    
    if ("EBS" %in% a$case) {
      idw$extrapolation.stack <- dplyr::bind_rows(
        idw$extrapolation.stack |>
          dplyr::filter(YEAR %in% a$YEAR[a$case != "EBS"]),
        idw$extrapolation.stack |> 
          dplyr::filter(YEAR %in% a$YEAR[a$case == "EBS"]) |> 
          sf::st_difference(y = reg_dat$survey.area[reg_dat$survey.area$survey_definition_id == 143,]) )
    }
  }
  
  idw$extrapolation.stack$var1.pred <- 
    factor(x = idw$extrapolation.stack$var1.pred, 
           levels = levels(idw$extrapolation.stack$var1.pred), 
           labels = set.breaks_pretty,
           ordered = TRUE)
  
  
  if (report_title0 != "gif") {
    # Plot -------------------------------------------------------------------------
    for (case_yr in case_yr0) {
      # if (length(case_yr0)>1) {
      if (case_yr == 1) {
        yrs0 <- yrs[1:(length(yrs)/2)]
      } else if (case_yr == 2) {
        yrs0 <- yrs[((length(yrs)/2)+1):length(yrs)]
      }
      # }
      
      figure_print <- ggplot() +
        ggplot2::geom_sf(data = reg_dat0$akland,
                         color = NA,
                         fill = "grey70")  +
        ggplot2::geom_sf(data = reg_dat0$graticule,
                         color = "grey80",
                         alpha = 0.2) +
        ggplot2::scale_y_continuous(name = "", #"Latitude",
                                    expand = c(0, 0),
                                    limits = reg_dat0$plot.boundary$y,
                                    breaks = reg_dat0$lat.breaks) +
        ggplot2::scale_x_continuous(name = "", #"Longitude",
                                    limits = reg_dat0$plot.boundary$x,
                                    breaks = reg_dat0$lon.breaks) + 
        ggplot2::geom_sf(data = idw$extrapolation.stack,
                         mapping = aes(fill = var1.pred),
                         na.rm = FALSE,
                         show.legend = TRUE, 
                         color = NA) +
        ggplot2::facet_wrap( ~ YEAR, nrow = row0) + 
        ggplot2::scale_fill_manual(
          # labels = scales::label_comma(),
          # labels = function(x) format(x, big.mark = ",", scientific = FALSE), 
          name = key.title,
          values =  c("gray90",
                      viridis::viridis(
                        option = viridis_palette_option,
                        direction = -1,
                        n = length(set.breaks)-1,
                        begin = 0.20,
                        end = 0.80)),
          na.translate = FALSE, # Don't use NA
          drop = FALSE) + 
        ggplot2::geom_sf(
          data = reg_dat0$survey.area, 
          mapping = aes(color = SURVEY, 
                        geometry = geometry), 
          fill = "transparent", 
          linewidth = .75, # ifelse(row0 > 2, 1.5, 1), 
          show.legend = FALSE) +
        ggplot2::scale_color_manual(
          name = " ", 
          values = reg_dat0$survey.area$color,
          breaks = reg_dat0$survey.areasrvy_long,
          labels = reg_dat0$survey.area$srvy) + 
        ggplot2::guides(
          fill = guide_legend(
            order = 1,
            title.position = "top",
            label.position = "bottom",
            title.hjust = 0.5,
            override.aes = list(color = NA),
            nrow = 1),
          color = "none")  +
        ggplot2::coord_sf(expand = FALSE) + # coord_sf() + 
        ggplot2::theme( 
          panel.background = element_rect(fill = "white", colour = NA), 
          panel.border = element_rect(fill = NA, colour = "grey20"), 
          axis.text = element_text(size = ifelse(length(yrs0)>4 & row0 == 1, 6, 8)),
          
          strip.background = element_blank(), 
          strip.text = element_text(size = 10, face = "bold"), 
          legend.text = element_text(size = 9),
          legend.background = element_rect(colour = "transparent", 
                                           fill = "transparent"),
          legend.key = element_rect(colour = "transparent", 
                                    fill = "transparent"),
          legend.position = "bottom", 
          legend.box = "horizontal",
          legend.box.spacing = unit(0, "pt"), # reduce space between legend & plot
          legend.margin=margin(0, 0, 0, 0) ) 
      
      if (report_title0 == "pres") {
        figure_print <- figure_print +
          ggplot2::theme(legend.title=element_blank() ) +
          ggplot2::ggtitle(key.title) 
      }
      
      # if (report_title0 %in% c("nbspres")) {
      #   
      #   figure_print <- figure_print + 
      #     ggplot2::geom_sf_text(
      #       data = data.frame(y = 64.500126, x = -165.408402) |> 
      #         sf::st_as_sf(coords=c("x","y"), crs="+proj=longlat") |> 
      #         sf::st_transform(crs = "EPSG:3338") |>
      #         dplyr::mutate(label = "Nome"), 
      #       mapping = aes(label = label), 
      #       fontface = "italic", 
      #       size = 4) +
      #     geom_text(data = subset(reg_dat0$place.labels, 
      #                             type == "mainland"), 
      #               aes(x = x, y = y, label = lab), 
      #               size = 7, group = 99) + 
      #     geom_shadowtext(data = subset(reg_dat0$place.labels, 
      #                                   type == "peninsula"), 
      #                     aes(x = x, y = y, label = lab), size = 3, angle = 3, 
      #                     bg.color = "white", color = "black", group = 99) + 
      #     geom_shadowtext(
      #       data = subset(reg_dat0$place.labels, 
      #                     type %in% c("bathymetry", "islands")),
      #       aes(x = x, y = y, label = lab), 
      #       bg.color = "white", color = "black", 
      #       size = 2, group = 99)
      # }  
    }
    if (report_title0 %in% c("community")) {
      figure_print <-
        cowplot::ggdraw(figure_print +
                          ggplot2::theme( plot.margin = margin(1.8, 0, 0, 0, "cm") ) ) +
        cowplot::draw_image(image = readPNG(paste0(dir_img, spp_file, ".png")),
                            x = .77, y = .42, # top right
                            # x = 0.09, y = -.35, # lower left
                            hjust = 0, vjust = 0,
                            width = .18)
    }
  } else {
    # file.create(paste0(dir_out_figtab, "/gif", spp_print, "/"))
    for (ii in 1:length(unique(idw$extrapolation.stack$YEAR))) {
      
      yr0 <- unique(idw$extrapolation.stack$YEAR)[ii]
      
      gg <- ggplot() +
        ggplot2::geom_sf(data = reg_dat0$akland,
                         color = NA,
                         fill = "grey7s0")  +
        ggplot2::geom_sf(data = reg_dat0$graticule,
                         color = "grey80",
                         alpha = 0.2) +
        ggplot2::scale_y_continuous(name = "", #"Latitude",
                                    expand = c(0, 0),
                                    limits = reg_dat0$plot.boundary$y,
                                    breaks = reg_dat0$lat.breaks) +
        ggplot2::scale_x_continuous(name = "", #"Longitude",
                                    limits = reg_dat0$plot.boundary$x,
                                    breaks = reg_dat0$lon.breaks) + 
        ggplot2::geom_sf(data = idw$extrapolation.stack[idw$extrapolation.stack$YEAR == yr0,],
                         mapping = aes(fill = var1.pred),
                         na.rm = FALSE,
                         show.legend = TRUE, 
                         color = NA) +
        # ggplot2::facet_wrap( ~ YEAR, nrow = row0) + 
        ggplot2::scale_fill_manual(
          name = paste0(yr0, " ", key.title),
          values =  c("gray90",
                      viridis::viridis(
                        option = viridis_palette_option,
                        direction = -1,
                        n = length(set.breaks)-1,
                        begin = 0.20,
                        end = 0.80)),
          na.translate = FALSE, # Don't use NA
          drop = FALSE) + 
        ggplot2::geom_sf(
          data = reg_dat0$survey.area, 
          mapping = aes(color = SURVEY, 
                        geometry = geometry), 
          fill = "transparent", 
          linewidth = 1, # ifelse(row0 > 2, 1.5, 1), 
          show.legend = FALSE) +
        ggplot2::scale_color_manual(
          name = " ", 
          values = reg_dat0$survey.area$color,
          breaks = reg_dat0$survey.areasrvy_long,
          labels = reg_dat0$survey.area$srvy) + 
        ggplot2::guides(
          fill = guide_legend(
            order = 1,
            title.position = "top",
            label.position = "bottom",
            title.hjust = 0.5,
            override.aes = list(color = NA),
            nrow = 1),
          color = "none")  +
        ggplot2::coord_sf(expand = FALSE) + # coord_sf() + 
        ggplot2::theme( 
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 16, face = "bold"),
          panel.background = element_rect(fill = "white", colour = NA), 
          panel.border = element_rect(fill = NA, colour = "grey20"), 
          axis.text = element_text(size = 12),
          
          strip.background = element_blank(), 
          # strip.text = element_text(size = 20, face = "bold"),
          legend.background = element_rect(colour = "transparent", 
                                           fill = "transparent"),
          legend.key = element_rect(colour = "transparent", 
                                    fill = "transparent"),
          legend.position = "bottom", 
          legend.box = "horizontal",
          legend.box.spacing = unit(0, "pt"), # reduce space between legend & plot
          legend.margin=margin(0, 0, 0, 0) ) # +
      # ggtitle(#label = spp_print, 
      #   subtitle = yr0)
      
      ggsave(filename = paste0(nickname, "-", yr0, '.png'), 
             path = paste0(dir_out_figtab, "gif/"),
             height = height, 
             width = width,
             plot = gg, 
             dpi = 300,
             bg = "white", 
             device = "png") 
      
    }
    
    # prepare animation ----------------------------------------------------------
    img_gif <- sort(list.files(path = paste0(dir_out_figtab, "gif/"), 
                               pattern = paste0(nickname, "-"), 
                               full.names = TRUE) )
    
    img_gif <- lapply(img_gif, 
                      magick::image_read)
    
    img_gif <- lapply(img_gif, 
                      image_resize, 
                      geometry = "1280")
    
    ## join the images together
    img_gif <- magick::image_join(img_gif)
    
    ## animate at 2 frames per second
    figure_print <- magick::image_animate(img_gif, 
                                          fps = 2)
    
    ## view animated image
    # figure_print
    
    ## save to disk
    magick::image_write(
      image = figure_print, 
      path = paste0(paste0(dir_out_figtab, "gif/"), nickname, ".gif") )
    
    # magick::image_write(
    #   image = figure_print,
    #   path = paste0(paste0(dir_out_figtab, "gif/"), nickname, ".mp4"),
    #   format = "mp4")
    
  }
  
  return(list("figure_print" = figure_print, 
              "header" = header, 
              "height" = height, 
              "width" = width, 
              "nickname" = nickname))
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
  
}

```

```{r fig-dist-[spp]-data, eval = FALSE}
yrs <- c(maxyr, compareyr) # analysisyrs

# if (spp_file == "greenland-turbot") {
#   yrs <- c(2022, 2023, 2024)
# }
width <- full_page_portrait_width # 6.5  
height <- 3.5 # full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
row0 <- 1 # 3
nickname <- paste0("fig-dist-", spp_file, "-data")
report_title0 <- "data"

temp <- dist_plot(yrs, height, row0, nickname, report_title0, spp_print, spp_code)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-dist-[spp]-comm}
nickname <- paste0("fig-dist-", spp_file, "-comm")
yrs <- c(compareyr, maxyr)
height <- ifelse(srvy == "NEBS", 5, 4)
width <- 5
width <- 5
row0 <- 1
report_title0 <- "pres"

temp <- dist_plot(yrs, height, row0, nickname, report_title0, spp_print, spp_code) 
comm_dist <- temp$figure_print  + 
  ggplot2::ggtitle(NULL) + 
  ggplot2::theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))

comm_dist_txt <- temp$header
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand(file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-dist-[spp]-pres}
nickname <- paste0("fig-dist-", spp_file, "-pres")
yrs <- c(maxyr-1, maxyr)
height <- ifelse(srvy == "NEBS", 5, 4)
width <- 5
width <- 5
row0 <- 1
report_title0 <- "pres"

temp <- dist_plot(yrs, height, row0, nickname, report_title0, spp_print, spp_code) 
pres_dist <- temp$figure_print  + 
  ggplot2::ggtitle(NULL) + 
  ggplot2::theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))

pres_dist_txt <- temp$header
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand(file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-dist-[spp]-gif, eval = FALSE}
yrs <- unique(cpue$year[cpue$species_code %in% unlist(a$species_code)]) # 1982:maxyr

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
row0 <- 1
nickname <- paste0("fig-dist-", spp_file, "-gif")
report_title0 <- "gif"

temp <- dist_plot(yrs, height, row0, nickname, report_title0, spp_print, spp_code)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-sizecomp-[spp]-prep, eval = spp_plot_sizecomp}
width <- full_page_portrait_width # 6.5  
header <- pres_size_txt <- ""
legend_font_size <- 12

size_plot <- function(srvy, yrs, lengths, sizecomp, print_n, height, width, nickname, legend_font_size, report_title0) {
  
  lengths0 <- lengths |>
    dplyr::filter(species_code %in% spp_code &
                    srvy %in% srvy &
                    year %in% yrs)
  
  type <- unique(lengths0$sentancefrag)
  
  # if (length(spp_code) > 1) {
  #   table_raw <- sizecomp |>
  #     dplyr::filter(group %in% spp_print)
  # } else {
  table_raw <- sizecomp |>
    dplyr::filter(species_code %in% spp_code) 
  
  if (srvy != "NEBS") {
    table_raw <- table_raw |> 
      dplyr::filter(srvy == srvy1)
  }
  # }
  
  if (grepl(x = spp_print, pattern = "crab")) { # c("Unsexed", "Males", "Females", "Immature females", "Mature females")
    factor0 <- c("Males", "Immature females", "Mature females") # check
  } else {
    factor0 <- c("Unsexed", "Males", "Females")
  }
  
  # srvy_ <- srvy
  table_raw <- table_raw  |>
    dplyr::filter(srvy %in% srvy1) |>
    dplyr::filter(year %in% yrs) |> 
    dplyr::mutate(sex = str_to_sentence(sex), 
                  sex = factor(sex, 
                               levels = factor0, 
                               labels = factor0,
                               ordered = TRUE), 
                  srvy_long = dplyr::case_when(
                    srvy == "EBS" ~ "eastern Bering Sea", 
                    srvy == "NBS" ~ "northern Bering Sea") ) |> 
    dplyr::arrange(sex) 
  
  if (!(nrow(table_raw) == 0)) {
    
    if (report_title0 %in% c("community", "data", "gif")) {
      if (report_title0 == "community") {
        
        dat0 <- table_raw
        dat0$srvy_long <- dat0$srvy
        
        header <- paste0("Total population estimates at length for ",
                         spp_print, 
                         # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")),
                         " calculated from ",
                         range_text(yrs)," ",
                         text_list(paste0(unique(table_raw$srvy_long))), 
                         " survey", 
                         ifelse(length(unique(table_raw$srvy))==1 & length(unique(table_raw$year))==1, "", "s"),
                         ". ",
                         ifelse(print_n, 
                                "Total number of individuals measured during the survey is indicated in the upper right corner of each plot.", ""))
        
      } else if (report_title0 %in% c("data", "gif")) {
        
        if (srvy == "NEBS" & length(unique(table_raw$srvy))>1) {
          
          table_raw <- dplyr::bind_rows(
            table_raw, 
            table_raw |>
              dplyr::filter(species_code %in% spp_code &
                              # srvy %in% srvy1 &
                              year %in% yrs) |> 
              dplyr::group_by(year, taxon, species_code, sex, length_mm) |> 
              dplyr::summarise(population_count = sum(population_count, na.rm = TRUE)) |> 
              dplyr::mutate(
                # srvy = factor(x = srvy, levels = c("EBS", "NBS", "EBS and NBS"), ordered = TRUE), 
                srvy = "EBS and NBS", 
                srvy_long = paste0("combined ", SURVEY)))
        }
        
        header <- paste0("Total abundance-at-length estimates of ",
                         spp_print, 
                         # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
                         " by sex (",text_list(tolower(unique(table_raw$sex))),
                         ") in ",
                         ifelse(!grepl(pattern = " crab", x = spp_print, ignore.case = TRUE), 
                                "centimeters (cm)", "millimeters (mm)"),
                         " encountered during the ",
                         min(yrs, na.rm = TRUE), "-", max(yrs, na.rm = TRUE), # range_text(yrs)
                         " ",
                         text_list(paste0(unique(table_raw$srvy_long))), 
                         " survey", 
                         ifelse(length(unique(table_raw$srvy))==1 & length(unique(table_raw$year))==1, "", "s"),
                         ". ",
                         ifelse(length(setdiff(srvy1, unique(table_raw$srvy)))>0,
                                paste0("There were no lengths collected for this species in the ", 
                                       min(yrs, na.rm = TRUE), "-", max(yrs, na.rm = TRUE), # range_text(yrs)
                                       " ",
                                       haul_cruises_maxyr$srvy_long[haul_cruises_maxyr$srvy != unique(table_raw$srvy)],
                                       " trawl survey",ifelse(length(yrs)>1, "s", ""),". "), 
                                ""),
                         
                         "Length distributions are scaled to the total estimated population size. ", 
                         ifelse(print_n, 
                                "Total number of individuals measured during the survey is indicated in the upper right corner of each plot.", ""))
        
        dat0 <- table_raw |> 
          dplyr::mutate(
            srvy_long = gsub(replacement = "", x = srvy_long, pattern = SURVEY), 
            srvy_long = trimws(stringr::str_to_title(srvy_long)))        
        
      }
      
      
      if (report_title0 == "gif") {
        
        table_raw0 <- dat0 |>
          dplyr::arrange(year, srvy, sex, length_mm) 
        
        # find appropriate units
        a <- find_units(unit = "", unt = "", dat = max(table_raw0$population_count, na.rm = TRUE))
        for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
        pop_unit <- divby
        pop_unit_word <- unit_word        
        len_unit_word0 <- ifelse(!grepl(pattern = " crab", x = spp_print, ignore.case = TRUE),  "cm", "mm")
        
        table_raw0 <- table_raw0 |>
          dplyr::mutate(population_count = population_count/pop_unit) |> # , 
          # length_mm = round(
          #   x = length_mm/ifelse(len_unit_word0 == "mm", 1, 10), digits = 0)) |>
          dplyr::ungroup()
        
        for (ii in 1:length(unique(dat0$year))) {
          yr0<- sort(unique(dat0$year))[ii]
          
          gg <- plot_sizecomp(
            sizecomp0 = table_raw0 |> 
              dplyr::filter(year == yr0),
            lengths0 = lengths0[1:3,] |> 
              dplyr::mutate(year = yr0, 
                            frequency = 0, 
                            srvy = unique(dat0$srvy)),
            spp_code = spp_code,
            spp_print = paste0(yr0, " ", stringr::str_to_title(spp_print)),
            type = type,
            print_n = print_n, 
            unit0 = , 
            ridgeline = FALSE, 
            divscale = FALSE)  +
            ggplot2::scale_y_continuous(
              name = paste0("Population", pop_unit_word),
              expand = c(0, 0),
              limits = c(0, max(table_raw0$population_count)+max(table_raw0$population_count)*.1)) +
            ggplot2::scale_x_continuous(
              name = stringr::str_to_sentence(paste0(type," (", len_unit_word0, ")")), 
              limits = c(0, max(table_raw0$length_mm)/ifelse(!grepl(pattern = " crab", x = spp_print, ignore.case = TRUE),  10, 1)), 
              labels = scales::label_number(
                accuracy = ifelse(max(table_raw0$length_mm) < 9, 1, 10), big.mark = ",")) +
            ggplot2::scale_fill_manual(
              values = viridis::mako(n = length(levels(table_raw0$sex)), begin = .2, end = .6, direction = -1),
              breaks = levels(table_raw0$sex),
              labels = levels(table_raw0$sex),
              drop = FALSE)   #+
          # ggplot2::labs(fill = spp_print) +
          # ggplot2::guides(
          #   fill = guide_legend(title.position = "top",
          #                       title.hjust = 0.5,
          #                       title.vjust = -0.5))
          
          ggsave(filename = paste0(nickname, "-", yr0, '.png'), 
                 path = paste0(dir_out_figtab, "gif/"),
                 height = height, 
                 width = width,
                 plot = gg, 
                 dpi = 300,
                 bg = "white", 
                 device = "png") 
          
        }
        
        # prepare animation ----------------------------------------------------------
        img_gif <- sort(list.files(path = paste0(dir_out_figtab, "gif/"), 
                                   pattern = paste0(nickname, "-"), 
                                   full.names = TRUE) )
        
        img_gif <- lapply(img_gif, 
                          magick::image_read)
        
        img_gif <- lapply(img_gif, 
                          image_resize, 
                          geometry = "1280")
        
        ## join the images together
        img_gif <- magick::image_join(img_gif)
        
        ## animate at 2 frames per second
        figure_print <- magick::image_animate(img_gif, 
                                              fps = 2)
        
        ## view animated image
        # figure_print
        
        ## save to disk
        magick::image_write(
          image = figure_print, 
          path = paste0(paste0(dir_out_figtab, "gif/"), nickname, ".gif") )
        
        
      } else {
        figure_print <- plot_sizecomp(
          sizecomp0 = dat0,
          lengths0 = lengths0,
          spp_code = spp_code,
          spp_print = stringr::str_to_title(spp_print),
          type = type,
          print_n = print_n, 
          ridgeline = FALSE)
      }
      
    } else if (report_title0 == "pres") {
      
      header <- ""
      if ("EBS" %in% table_raw$srvy & srvy %in% c("NEBS", "EBS")) {
        figure1 <- figure_print <- plot_sizecomp(
          sizecomp0 = table_raw |> 
            dplyr::filter(srvy == "EBS") |> 
            dplyr::mutate(srvy_long = stringr::str_to_title(srvy_long)),
          lengths0 = lengths0,
          spp_code = spp_code,
          spp_print = stringr::str_to_sentence(spp_print),
          type = type,
          print_n = print_n, 
          ridgeline = FALSE) + 
          ggplot2::ggtitle(paste0(maxyr," EBS"))
      }
      if ("NBS" %in% table_raw$srvy & srvy %in% c("NEBS", "NBS")) {
        figure2 <- figure_print <- plot_sizecomp(
          sizecomp0 = table_raw |> 
            dplyr::filter(srvy == "NBS") |> 
            dplyr::mutate(srvy_long = stringr::str_to_title(srvy_long)),
          lengths0 = lengths0,
          spp_code = spp_code,
          spp_print = stringr::str_to_sentence(spp_print),
          type = type,
          print_n = print_n, 
          ridgeline = FALSE) + 
          ggplot2::ggtitle(paste0(maxyr," NBS"))
      }
      if (sum(unique(table_raw$srvy) %in% c("NBS", "EBS")) == 2 & srvy %in% c("NEBS")) {
        figure_print <- cowplot::plot_grid(
          figure2 + 
            ggplot2::theme(#axis.title.y = element_blank(),
              plot.title = element_text(size = 10, face = "bold"), 
              legend.title = element_blank(), 
              legend.title.position = "none",
              legend.position = "none", 
              plot.margin=grid::unit(c(.1,.1,.1,.1), "mm") ),  
          figure1 + 
            ggplot2::theme(#axis.title.y = element_blank(),
              plot.title = element_text(size = 10, face = "bold"), 
              legend.title = element_blank(), 
              legend.title.position = "none",
              legend.position = "none", 
              plot.margin=grid::unit(c(.1,.1,.1,.1), "mm") ), 
          cowplot::get_legend(figure1 + 
                                ggplot2::labs(fill = NULL)) , 
          nrow = 3, 
          ncol = 1, 
          rel_heights = c(.3, .3, .05))
      }
    }
    
    figure_print <- figure_print +
      ggplot2::theme(strip.text = element_text(size = legend_font_size, face = "bold"))
    
    # if (report_title0 %in% c("community")) { 
    #   figure_print <-
    #     cowplot::ggdraw(figure_print + 
    #                       ggplot2::theme( plot.margin = margin(1.2, 0, 0, 0, "cm") ) ) +
    #     cowplot::draw_image(image = readPNG(paste0(dir_img, spp_file, ".png")),
    #                         x = .78, y = .44, # top right
    #                         # x = 0.07, y = -.42, # lower left
    #                         hjust = 0, vjust = 0,
    #                         width = .18)
    # }
    
  } else {
    header <- ""
    figure_print <- ggplot(data = data.frame(x = 1, y = 1, 
                                             label = "There are no data for this year and species"), 
                           mapping = aes(y=y, x=x)) +
      geom_text(mapping = aes(label = label))
  }
  
  return(list("figure_print" = figure_print, 
              "header" = header, 
              "height" = height, 
              "width" = width, 
              "nickname" = nickname))
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```


```{r fig-sizecomp-[spp]-data, eval = FALSE}
# eval = spp_plot_sizecomp
yrs <- c(maxyr, compareyr) # analysisyrs
height <- 4
print_n <- FALSE
# srvy <- srvy1
nickname <- paste0("fig-sizecomp-", spp_file, "-data")
legend_font_size <- 10
report_title0 <- "data"

temp <- size_plot(srvy, yrs, lengths, sizecomp, print_n, height, width, nickname, legend_font_size, report_title0) 
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-sizecomp-[spp]-comm, eval = spp_plot_sizecomp}
nickname <- paste0("fig-sizecomp-", spp_file, "-comm")
print_n <- FALSE
height <- 4.5
width <- 5
report_title0 <- "community"
legend_font_size <- 8
yrs <- c(maxyr, compareyr) # [names(compareyr) == "NBS"]

temp <- size_plot(srvy, yrs, lengths, sizecomp, # |> dplyr::filter(srvy == "NBS"), 
                  print_n, height, width, nickname, legend_font_size, report_title0) 
comm_size <- figure_print <- 
  temp$figure_print +
  ggplot2::labs(fill = NULL) +
  ggplot2::theme(
    plot.title = element_blank(), 
    axis.title.x = element_blank(), 
    # legend.title = element_blank(), 
    plot.margin=grid::unit(c(.1,.1,.1,.1), "mm") )
header <- ""

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-sizecomp-[spp]-pres, eval = spp_plot_sizecomp}
nickname <- paste0("fig-sizecomp-", spp_file, "-pres")
print_n <- FALSE
height <- 4.5
width <- 5
report_title0 <- "pres"
legend_font_size <- 12
yrs <- maxyr

temp <- size_plot(srvy, yrs, lengths, sizecomp, # |> dplyr::filter(srvy == "NBS"), 
                  print_n, height, width, nickname, legend_font_size, report_title0) 
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
pres_size <- temp$figure_print

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-sizecomp-[spp]-gif, eval = FALSE}
# eval - spp_plot_sizecomp
yrs <- unique(cpue$year[cpue$species_code %in% unlist(a$species_code)]) # 1982:maxyr

width <- full_page_landscape_width # 6.5  
height <- 5
print_n <- FALSE
nickname <- paste0("fig-sizecomp-", spp_file, "-gif")
report_title0 <- "gif"

temp <- size_plot(srvy, yrs, lengths, sizecomp, print_n, height, width, nickname, legend_font_size, report_title0) 
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-agecomp-[spp]-prep, eval = spp_plot_agecomp}
width <- full_page_portrait_width # 6.5  
header <- ""
legend_font_size <- 12

age_plot <- function(srvy, yrs, agecomp, height, width, nickname, legend_font_size, report_title0) {
  
  if (length(spp_code) > 1) {
    table_raw <- agecomp |>
      dplyr::filter(group %in% spp_print)
  } else {
    table_raw <- agecomp |>
      dplyr::filter(species_code %in% spp_code)
  }
  
  # find appropriate units
  a <- find_units(unit = "", unt = " years", dat = max(table_raw$population_count, na.rm = TRUE))
  for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
  pop_unit <- divby
  pop_unit_word <- unit_word
  
  # len_unit_axis <- ifelse(max(table_raw$length_mm)-min(table_raw$length_mm)>150, 50, 
  #                         ifelse(max(table_raw$length_mm)-min(table_raw$length_mm)>45, 10, 5))
  
  table_raw <- table_raw  |>
    dplyr::filter(srvy %in% srvy &
                    year %in% yrs) |> 
    dplyr::mutate(sex = str_to_sentence(sex), 
                  sex = factor(sex, 
                               levels = c("Unsexed", "Males", "Females"), 
                               labels = c("Unsexed", "Males", "Females"),
                               ordered = TRUE), 
                  srvy_long = dplyr::case_when(
                    srvy == "EBS" ~ "eastern Bering Sea", 
                    srvy == "NBS" ~ "northern Bering Sea"), 
                  population_count = population_count/pop_unit
    ) |> 
    dplyr::arrange(sex) |> 
    dplyr::filter(sex != "Unsexed")
  
  if (srvy == "NEBS" & length(unique(table_raw$srvy))>1) {
    table_raw <- dplyr::bind_rows(
      table_raw, 
      table_raw |>
        dplyr::filter(species_code %in% spp_code &
                        srvy %in% srvy &
                        year %in% yrs) |> 
        dplyr::group_by(year, species_code, sex, population_count) |> 
        dplyr::summarise(age) |> 
        dplyr::mutate(
          srvy = factor(x = srvy, levels = c("EBS", "NBS", "EBS and NBS"), ordered = TRUE), 
          srvy = "EBS and NBS", 
          srvy_long = paste0("combined ", SURVEY)))
  }
  
  header <- paste0("Total abundance-at-age estimates of ",
                   spp_print, 
                   # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
                   " by sex (",text_list(tolower(unique(table_raw$sex))),
                   ") encountered during the ",
                   
                   min(yrs, na.rm = TRUE), "-", max(yrs, na.rm = TRUE), # range_text(sort(unique(table_raw$year))),
                   " ",
                   text_list(paste0(unique(table_raw$srvy_long))), 
                   " survey", 
                   ifelse(length(unique(table_raw$srvy))==1 & length(unique(table_raw$year))==1, "", "s"),
                   ". ",
                   ifelse(length(setdiff(srvy1, unique(table_raw$srvy)))>0,
                          paste0("There were no ages collected for this species in the ", 
                                 min(yrs, na.rm = TRUE), "-", max(yrs, na.rm = TRUE), # range_text(sort(unique(table_raw$year))), # range_text(yrs), 
                                 " ",
                                 haul_cruises_maxyr$srvy_long[haul_cruises_maxyr$srvy != unique(table_raw$srvy)],
                                 " trawl survey",ifelse(length(yrs)>1, "s", ""),". "), 
                          ""),
                   
                   "Age distributions are scaled up to the total estimated population size. Note that unexed otoliths were removed for figure legibility and that otoliths are not collected for each species each year and require years to process after collection. ")
  
  figure_print <- ggplot2::ggplot(
    data = table_raw |> 
      # dplyr::filter(sex %in% c(1,2)) |>
      dplyr::mutate(
        population_count = # change male population to negative
          ifelse(sex=="Males", population_count*(-1), population_count*1)) , # /1e9
    mapping = 
      aes(x = age,
          y = population_count, 
          fill = sex)) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::coord_flip() +
    # ggplot2::ggtitle(label = "2023 EBS (Standard Area + NW) walleye pollock Age Composition")  + 
    ggplot2::guides(fill = guide_legend(title = ""))  +
    scale_fill_viridis_d(option = "G", begin = .3, end = .7) +
    scale_x_continuous(name = "Age bin", 
                       breaks = function(age) unique(floor(pretty(seq(0, (max(age) + 1) * 1.1))))) +
    scale_y_continuous(name = paste0(spp_print, " population across years", unit_word),
                       expand = c(0, 0),
                       labels = abs) + 
    ggplot2::facet_grid(rows = vars(year), cols = vars(srvy_long)) +
    ggplot2::theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.box.spacing = unit(0, "pt"),
      # legend.position = c(.95, .95),
      # legend.justification = c("right", "top"),
      # legend.box.just = "right",
      # legend.margin = margin(6, 6, 6, 6), 
      #legend.position = "none", 
      panel.grid.major.x = element_line(colour = "grey80"),
      panel.background = element_rect(fill = "white"),
      panel.grid.major.y = element_line(colour = "grey80"),
      panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.border = element_rect(fill = NA,
                                  colour = "grey20"),
      strip.background = element_blank(),
      strip.text = element_text(size = legend_font_size, face = "bold"),
      legend.text = element_text(size = 9),
      legend.key = element_rect(colour = "transparent",
                                fill = "transparent"),
      axis.title = element_text(size = legend_font_size, face = "bold"),
      axis.text = element_text(size = legend_font_size))
  
  if (report_title0 %in% c("community")) { 
    figure_print <-
      cowplot::ggdraw(figure_print + 
                        ggplot2::theme( plot.margin = margin(1.2, 0, 0, 0, "cm") ) ) +
      cowplot::draw_image(image = readPNG(paste0(dir_img, spp_file, ".png")),
                          x = .78, y = .44, # top right
                          # x = 0.07, y = -.42, # lower left
                          hjust = 0, vjust = 0,
                          width = .18)
  }
  
  # } else {
  #   header <- ""
  #   figure_print <- ggplot(data = data.frame(x = 1, y = 1, label = "There are no data for this year and species"), mapping = aes(y=y, x=x)) +
  #     geom_text(mapping = aes(label = label))
  # }
  
  if (plural_surveys == "") {
    figure_print <- figure_print + 
      # ggplot2::ggtitle("") + 
      # ggplot2::guides(fill=guide_legend(title=""))  +
      ggplot2::theme(legend.title=element_blank(), 
                     strip.text.x = element_blank(),
                     strip.background = element_blank())
  }
  
  
  return(list("figure_print" = figure_print, 
              "header" = header, 
              "height" = height, 
              "width" = width, 
              "nickname" = nickname))
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r fig-agecomp-[spp]-data, eval = spp_plot_agecomp}
# yrs <- analysisyrs
# height <- full_page_portrait_height-1
# print_n <- FALSE
# srvy <- srvy1
# nickname <- paste0("fig-agecomp-", spp_file, "-data")
# legend_font_size <- 10
# report_title0 <- "data"
# 
# temp <- age_plot(srvy, yrs, agecomp, height, width, nickname, legend_font_size, report_title0) 
# for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-agecomp-[spp]-comm, eval = spp_plot_agecomp}
# yrs <- nbsyr
# height <- full_page_portrait_height 
# print_n <- FALSE
# srvy <- srvy1
# nickname <- paste0("fig-agecomp-", spp_file, "-comm")
# legend_font_size <- 10
# report_title0 <- "community"
# srvy <-"NBS"
# 
# temp <- age_plot(srvy, yrs, agecomp, height, width, nickname, legend_font_size, report_title0) 
# for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-agecomp-[spp]-pres, eval = spp_plot_agecomp}
# srvy <- srvy1
# nickname <- paste0("fig-agecomp-", spp_file, "-pres")
# yrs <- c(maxyr, compareyr)
# print_n <- FALSE
# height <- 4.5
# width <- 5
# legend_font_size <- 12
# report_title0 <- "pres"
# 
# temp <- age_plot(srvy, yrs, agecomp, height, width, nickname, legend_font_size, report_title0) 
# pres_size <- temp$figure_print
# for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```



```{r tab-stats-[spp])}
nickname <- paste0("tab-stats-", spp_file)
### Stats table ----------------------------------------------------------------
haul0 <- catch_haul_cruises |> 
  dplyr::select("station", "stratum", "latitude_dd_start", "longitude_dd_start", 
                "depth_m", "bottom_temperature_c" ,"surface_temperature_c", 
                "survey_name", "srvy", "year", "species_code", 
                "weight_kg", "count", "hauljoin")

temp_stat <- dplyr::left_join(
  x = haul0 |> 
    dplyr::filter(year == maxyr) |> 
    dplyr::select(station, srvy) |> 
    dplyr::distinct() |> 
    dplyr::select(srvy) |> 
    table() |> 
    data.frame() |> 
    dplyr::rename(tot = Freq), 
  y = catch_haul_cruises_maxyr |> # haul0 |> 
    dplyr::filter(species_code %in% spp_code & year == maxyr) |> 
    dplyr::select(station, srvy) |> 
    dplyr::distinct() |> 
    dplyr::select(srvy) |> 
    table() |> 
    data.frame() |> 
    dplyr::rename(spp = Freq), 
  by = "srvy") |> 
  dplyr::mutate(str = paste0(spp, " of ", tot, 
                             "\n(", formatC(spp/tot*100, digits = 1, format = "f", big.mark = ","), "%)")) |> 
  dplyr::filter(!is.na(spp))

### Env table ------------------------------------------------------------------

temp_env <- haul0 |> 
  dplyr::filter(srvy %in% srvy1 & 
                  year == maxyr & 
                  species_code %in% spp_code) |> 
  dplyr::select(srvy, 
                # "Latitude (°N)" = latitude_dd_start, 
                # "Longitude (°W)" = longitude_dd_start, 
                "Bottom\nDepth" = depth_m, 
                "Bottom Temperature" = bottom_temperature_c, 
                "Surface Temperature" = surface_temperature_c) |> 
  dplyr::group_by(srvy) |> 
  dplyr::summarise(across(where(is.numeric), 
                          .fns = 
                            list(Min = min,
                                 Max = max), 
                          na.rm = TRUE)) |>
  tidyr::pivot_longer(is.numeric,
                      names_sep='_',
                      names_to=c('variable', '.value')) |>
  dplyr::mutate(
    dplyr::across(dplyr::ends_with("Temperature"), 
                  formatC, big.mark = ",", digits = 1, format = "f"), 
    val = ifelse(Min == Max, Min, paste0(Min, " — ", Max)), 
    dplyr::across(dplyr::ends_with("Depth"), 
                  formatC, big.mark = ",", digits = 0, format = "f"), 
    val = ifelse(Min == Max, Min, paste0(Min, " — ", Max)))  |>
  dplyr::relocate(variable, dplyr::ends_with(srvy1[1])) |> 
  dplyr::select(-Min, -Max) |> 
  tidyr::pivot_wider(id_cols = "srvy",
                     names_from = "variable",
                     values_from = "val") |> 
  dplyr::mutate(
    dplyr::across(dplyr::ends_with("Temperature"),
                  ~paste0(.x, " °C")), 
    dplyr::across(dplyr::ends_with("Depth"),
                  ~paste0(.x, " m")), 
  )

### Biomass table --------------------------------------------------------------

# yrs <- c(maxyr, compareyr)

if (length(spp_code) == 1) {
  temp_bio <- biomass |> dplyr::filter(species_code %in% spp_code)
} else {
  temp_bio <- biomass |> dplyr::filter(common_name %in% spp_print)
}
temp_bio <- dplyr::right_join(
  x = total_biomass |>
    #       dplyr::right_join(data.frame(srvy = c(names(compareyr), names(compareyr)), 
    #                                year = c(compareyr, maxyr, maxyr))) |>   
    dplyr::group_by(srvy, year) |> 
    dplyr::summarise(total = sum(total, na.rm = TRUE)), 
  y = temp_bio |> 
    dplyr::filter(#year %in% yrs & 
      area_id > 999) |>
    
    dplyr::select(srvy, year, biomass_mt, population_count, 
                  cpue_kgkm2_mean, cpue_nokm2_mean) |> 
    dplyr::filter((biomass_mt !=0)), 
  by = c("year", "srvy")) |> 
  dplyr::right_join(data.frame(srvy = c(names(compareyr), names(compareyr)), 
                               year = c(compareyr, maxyr, maxyr))) |>     # dplyr::filter(year %in% yrs) |> 
  dplyr::group_by(srvy, year, total) |> 
  dplyr::summarise(biomass_mt = sum(biomass_mt, na.rm = TRUE),  
                   population_count = sum(population_count, na.rm = TRUE),  
                   cpue_kgkm2_mean = sum(cpue_kgkm2_mean, na.rm = TRUE),  
                   cpue_nokm2_mean = sum(cpue_nokm2_mean, na.rm = TRUE)) |> 
  dplyr::ungroup() |> 
  dplyr::mutate(print_name = spp_print)

if (sum(is.na(temp_bio$print_name[temp_bio$srvy == "NBS"])) == 
    nrow(temp_bio[temp_bio$srvy == "NBS",])) {
  temp_bio <- temp_bio |> 
    dplyr::filter(srvy != "NBS")
}

if (sum(is.na(temp_bio$print_name[temp_bio$srvy == "EBS"])) == 
    nrow(temp_bio[temp_bio$srvy == "EBS",])) {
  temp_bio <- temp_bio |> 
    dplyr::filter(srvy != "EBS")
}

temp_bio1 <- data.frame()
for (i in 1:nrow(temp_bio)) {
  
  temp <- temp_bio |> dplyr::filter(srvy == srvy[i])
  
  compareyr0 <- ifelse(temp_bio$year[i] == min(temp$year), min(temp$year), max(temp$year[temp$year < temp_bio$year[i]]))
  srvy0 <- temp_bio$srvy[i]
  temp_bio0 <- ifelse(temp_bio$year[i] == min(temp$year), NA, 
                      temp_bio$biomass_mt[temp_bio$srvy == srvy0 & temp_bio$year == compareyr0])
  
  temp_bio1  <- dplyr::bind_rows(
    temp_bio1, 
    c(
      srvy = temp_bio$srvy[i], 
      year = temp_bio$year[i], 
      "Population" = ifelse(is.na(temp_bio$population_count[i]),
                            "-",
                            xunits(temp_bio$population_count[i])),
      "Biomass" = ifelse(is.na(temp_bio$biomass_mt[i]),
                         "-",
                         paste0(xunits(temp_bio$biomass_mt[i],
                                       val_under_x_words = NULL), " t")),
      "Population; Biomass" = paste0(
        ifelse(is.na(temp_bio$population_count[i]), 
               "-", 
               xunits(temp_bio$population_count[i])), 
        "; ", 
        ifelse(is.na(temp_bio$biomass_mt[i]), 
               "-", 
               paste0(xunits(temp_bio$biomass_mt[i], 
                             val_under_x_words = NULL))), 
        " t" ), 
      "% of Total Biomass" = dplyr::case_when(
        is.na(temp_bio$biomass_mt[i]) ~ "-", 
        paste0(formatC(x = (temp_bio$biomass_mt[i]/temp_bio$total[i])*100, 
                       digits = 1, format = "f", big.mark = ","), "%") == "0.0%" ~ "<0.01%", 
        TRUE ~ paste0(formatC(x = (temp_bio$biomass_mt[i]/temp_bio$total[i])*100, 
                              digits = 1, format = "f", big.mark = ","), "%") ), 
      "% Change\nin Biomass" = unique(dplyr::case_when(
        temp_bio$year[i] == min(temp$year) ~ "-",
        is.na(temp_bio$biomass_mt[i]) ~ "-", #paste0("none caught in ", temp_bio$year[i]), 
        is.na(temp_bio0) ~ "-", #paste0("none caught in ", compareyr0), 
        temp_bio0 == 0 ~ paste0("Not caught in ", compareyr0),
        abs(pchange(start = temp$biomass_mt[i], end = temp$biomass_mt[-i], value_only = TRUE)) < 1 ~ "no change",
        TRUE ~ sub(replacement = "", pattern = "an ", 
                   x = gsub(pattern = "a ", replacement = "", 
                            x = paste0(pchange(end = temp_bio$biomass_mt[i], 
                                               start = temp_bio0), 
                                       "\nfrom ", compareyr0)) ) )))
  )
}

### Catch ----------------------------------------------------------------------

temp_catch <- catch_haul_cruises |> 
  dplyr::filter(species_code %in% spp_code) |> 
  dplyr::right_join(data.frame(srvy = c(names(compareyr), names(compareyr)), 
                               year = c(compareyr, maxyr, maxyr))) |> 
  dplyr::select(species_code, srvy, year, weight_kg, count) 

if (spp_print == "tunicates") {
  temp_catch <- temp_catch |> 
    dplyr::mutate(count = weight_kg)
}

temp_catch <- temp_catch |> 
  dplyr::group_by(srvy, year) |> 
  dplyr::mutate(year = ifelse(year %in% compareyr, 1111, year)) |> 
  dplyr::summarise(count = sum(count, na.rm = TRUE)) |> 
  tidyr::pivot_wider(id_cols = srvy, names_from = year, values_from = count, names_prefix = "yr_") |> 
  dplyr::left_join(data.frame(srvy = c(names(compareyr)), 
                              compareyr = c(compareyr))) |> 
  dplyr::relocate(srvy, compareyr)
# temp_catch$catch_min <- min(c(unlist(temp_catch[paste0("yr_", compareyr)]), unlist(temp_catch[,paste0("yr_", maxyr)])), na.rm = TRUE)
# temp_catch <- temp_catch |> 
#   dplyr::mutate(catch_min = min())

# aaa <- setdiff(paste0("yr_", c(compareyr, maxyr)), names(temp_catch) )
aaa <- setdiff(paste0("yr_", c(1111, maxyr)), names(temp_catch) )
if (length(aaa)>0) {
  temp_catch$temp <- 0
  names(temp_catch)[3] <- aaa
}

catch_min <- c()
for (i in 1:nrow(temp_catch)){
  catch_min[i] <- (min(temp_catch[i,c(-1, -2)], na.rm = TRUE))
}
temp_catch$catch_min <- catch_min

# temp_catch$str <- paste0(
#   ifelse(temp_catch[paste0("yr_1111")] < temp_catch[,paste0("yr_", maxyr)], "Increased", "Decreased"),
#   " from ",
#   temp_catch[,paste0("yr_1111")],
#   " to ",
#   temp_catch[,paste0("yr_", maxyr)],
#   " ",ifelse(spp_print == "tunicates", "kg", "individuals")," in ",
#   maxyr)

temp_catch$str <- paste0(
  ifelse(temp_catch[,paste0("yr_1111")] < temp_catch[,paste0("yr_", maxyr)],
         # ifelse(temp_catch[,paste0("yr_", compareyr)] < temp_catch[,paste0("yr_", maxyr)],
         "Increased", "Decreased"), 
  " from ", 
  formatC(x = unlist(temp_catch[,paste0("yr_1111")]), big.mark = ",", format = "f", digits = 0), 
  ifelse(spp_print == "tunicates", " kg", ""), " in ", 
  temp_catch$compareyr,
  # unlist(temp_catch[,paste0("yr_", compareyr)]), 
  " to ", 
  formatC(x = unlist(temp_catch[,paste0("yr_", maxyr)]), big.mark = ",", format = "f", digits = 0),
  # " individuals in ", 
  " ",ifelse(spp_print == "tunicates", "kg", "individuals")," in ",
  
  maxyr)
# if (spp_print == "tunicates") { # can't be counted!
#   temp_catch$str <- ""
# }
### Combine temp tables --------------------------------------------------------

table_raw <- temp_stat |> 
  dplyr::select(srvy, "Stations\nPresent" = str) |> 
  dplyr::left_join(temp_env) |> 
  dplyr::left_join(temp_bio1 |> 
                     dplyr::filter(year == maxyr) |> 
                     dplyr::select(-year)) |> 
  dplyr::left_join(data.frame(srvy = srvy1, 
                              srvy_long = stringr::str_to_title(srvy11), 
                              Survey = gsub(" .*$", "", stringr::str_to_title(srvy11)))) |> 
  dplyr::left_join(temp_catch |> 
                     dplyr::select(srvy, `Observed Catch Totals` = str, catch_min)) |>
  # dplyr::select(-srvy) |> 
  dplyr::relocate(Survey) |> 
  dplyr::arrange(Survey) |> 
  dplyr::rename("Bering Sea\nSurvey" = Survey)

if (sum(table_raw$`Biomass\n% of Total` == "0.0%") == nrow(table_raw)) {
  table_raw <- table_raw |> 
    dplyr::select(-`Biomass\n% of Total`)
}

### Print table ----------------------------------------------------------------

header <- paste0("Summary of ",maxyr," catch presence, temperature ranges, and extrapolated biomass and population estimates for ", 
                 spp_print, 
                 # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
                 " in the ", 
                 ifelse(length(table_raw$`Bering Sea\nSurvey`) == 1, paste0(tolower(table_raw$`Bering Sea\nSurvey`), " Bering Sea"), SURVEY), 
                 " survey", plural_surveys, ". ")

table_raw0 <- table_raw |> 
  dplyr::select(-srvy) |> 
  dplyr::select(-srvy_long)
table_print0 <- data.frame("var" = rownames(t(table_raw0))[-1], 
                           data.frame(t(table_raw0)[-1,]))  
names(table_print0) <- c("var", stringr::str_to_title(table_raw$srvy_long))
rownames(table_print0) <- NULL
table_print0[,1] <- gsub(x = table_print0[,1], pattern = "\n", replacement = " ")
table_print0[,2] <- gsub(x = table_print0[,2], pattern = "\n", replacement = " ")
if (ncol(table_print0) > 2) {
  table_print0[,3] <- gsub(x = table_print0[,3], pattern = "\n", replacement = " ")
}

# remove rows if there are less than 99 individuals 
if (sum(table_raw$catch_min > 99) == length(srvy1)) {
  table_print0 <- table_print0[table_print0$var != "Observed Catch Totals",]
} else {
  table_print0 <- table_print0[table_print0$var != "% Change in Biomass",]
  table_print0 <- table_print0[table_print0$var != "% of Total Biomass",]
  header <- paste0(header, 
                   "Too few organisms were observed on the survey to share meaningful percent change to percent of total biomass values, so observed values are shared instead. ")
}

# # null cells if there are less than 99 individuals
# for (i in 1:length(srvy)) {
#   if (table_raw$catch_min > 99) {
#     # table_print0[table_print0$var != "Observed Catch Totals", i] <- ""
#   } else {
#     table_print0[table_print0$var != "Percent Change in Biomass", i] <- "Catch was too low to assess"
#   }
# }

table_print0 <- table_print0[table_print0$var != "catch_min", ]

if (spp_print == "tunicates") {
  table_print0 <- table_print0[table_print0$var != "Population",]
  table_print0 <- table_print0[table_print0$var != "Population; Biomass",]
} else {
  table_print0 <- table_print0[table_print0$var != "Population",]
  table_print0 <- table_print0[table_print0$var != "Biomass",]  
}

flextable_color_range <- function(ft, dat0, var0, rnge = -9:9) {
  
  if (grepl(pattern = "o change", x = dat0[nrow(dat0), var0]) | 
      strsplit(x = dat0[nrow(dat0), var0], split = "%")[[1]][1] %in% rnge ) {
    color0 <- neutral
  } else if (grepl(x = dat0[nrow(dat0), var0], pattern = "increase")) {
    color0 <- positive
  } else if (grepl(x = dat0[nrow(dat0), var0], pattern = "decrease")) {
    color0 <- negative
  } else {
    color0 <- 'white'
  }
  
  flextable::bg(
    x  = ft,
    bg = color0,
    i  = nrow(dat0),
    j  = var0 )
}

table_print <- table_print0 |> 
  flextable::flextable()  |> 
  theme_flextable_nmfstm(row_lines = FALSE, 
                         pgwidth = full_page_portrait_width)  |>
  flextable::bold(j = 1, part = "body") |> 
  flextable::theme_zebra() |> 
  flextable::vline(border = fp_border(color="grey70")) |> 
  flextable::set_header_labels("var" = "")   |>
  # theme_flextable_nmfstm(row_lines = FALSE,
  #                        pgwidth = full_page_portrait_width) |>
  flextable::width(width = 2.25) |>
  flextable::width(j = 1, width = 2) |>
  flextable_color_range(dat0 = table_print0, var0 = names(table_print0)[2]) 
# eval(parse(text = flextable_color_range(dat0 = table_print0, var0 = names(table_print0)[2]) ))

if (ncol(table_print0) > 2) {
  table_print <- table_print |>
    flextable_color_range(dat0 = table_print0, var0 = names(table_print0)[3]) 
}

pres_stats <- table_raw
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-est-[spp]-[wt or num], eval = ((report_title == "data") & spp_table_cpue)}
nickname0 <- paste0("tab-est-", spp_file, "-")

if (length(spp_code) > 1) {
  table_raw <- biomass |>
    dplyr::filter(common_name %in% spp_print)
} else {
  table_raw <- biomass |>
    dplyr::filter(species_code %in% spp_code)
}

temp <- table_raw |>
  dplyr::filter(year == maxyr &
                  area_id %in% strat0) |>
  dplyr::select(srvy, stratum, cpue_kgkm2_mean, cpue_kgkm2_sd,
                biomass_mt, biomass_sd, biomass_dw, biomass_up,
                cpue_nokm2_mean, cpue_nokm2_sd,
                population_count, population_sd, population_dw, population_up,
                n_weight, n_count, n_length)  |>
  dplyr::right_join(biomass |>
                      dplyr::filter(year == maxyr &
                                      stratum %in% strat0) |>
                      dplyr::select(srvy, stratum) |>
                      dplyr::distinct()) |>
  dplyr::left_join(data.frame(srvy = srvy1,
                              srvy_long = stringr::str_to_title(srvy11))) |>
  dplyr::mutate(stratum = as.character(stratum)) |>
  dplyr::arrange(stratum) |>
  dplyr::arrange(srvy) |>
  dplyr::mutate(stratum = ifelse(stratum == 999, "Total", stratum))

if (sum(is.na(temp$cpue_kgkm2_mean[temp$srvy == "NBS"])) ==
    nrow(temp[temp$srvy == "NBS",])) {
  temp <- temp |>
    dplyr::filter(srvy != "NBS")
}

if (sum(is.na(temp$cpue_kgkm2_mean[temp$srvy == "EBS"])) ==
    nrow(temp[temp$srvy == "EBS",])) {
  temp <- temp |>
    dplyr::filter(srvy != "EBS")
}

# Were lengths taken for this taxon? If not, we wont include the n_length column in the table and optomize for space
# include_n_length <- !(sum(temp$n_length[temp$stratum == "Total"] %in% 0) ==
#                         length(temp$n_length[temp$stratum == "Total"]))
include_n_length <- FALSE

if (sum(temp$biomass_mt[temp$stratum == "Total"] != 0, na.rm = TRUE) > 0) {
  
  if (sum(temp$biomass_mt [temp$stratum == "Total"] %in% 0, na.rm = TRUE)>0) {
    
    temp <- temp |>
      dplyr::filter(srvy == temp$srvy[temp$stratum == "Total" &
                                        temp$biomass_mt  != 0])
  }
  
  haul_cruises_maxyr0 <- haul_cruises_maxyr |>
    dplyr::filter(srvy %in% unique(temp$srvy))
  
  for (i in 1:2) {
    # table_raw <- data.frame()
    
    if (i == 1) { # CPUE (WT/km²) and BIOMASS
      nickname <- paste0(nickname0, "wt")
      
      table_raw <- temp |>
        dplyr::select(srvy, srvy_long, stratum,
                      cpue_kgkm2_mean, cpue_kgkm2_sd,
                      biomass_mt, biomass_sd, biomass_dw, biomass_up,
                      n_weight)
      
      # if (!include_n_length) {
      #   table_raw <- table_raw |>
      #     dplyr::select(-n_length)
      # }
      
      if (nrow(table_raw) != 0) { # if none were caught, don't do any of this
        
        cpue_kgkm2_mean0<-find_units(unit = "kg/km²", unt = "kg/km²", dat = table_raw$cpue_kgkm2_mean[table_raw$cpue_kgkm2_mean != 0])
        cpue_kgkm2_sd0 <- find_units(unit = "kg/km²", unt = "kg/km²", table_raw$cpue_kgkm2_sd[table_raw$cpue_kgkm2_sd != 0])
        biomass_mt0 <- find_units(unit = "t", unt = "t", table_raw$biomass_mt [table_raw$biomass_mt  != 0])
        biomass_sd0 <- find_units(unit = "t", unt = "t", table_raw$biomass_sd[table_raw$biomass_sd != 0])
        
        header <- paste0("Mean CPUE",cpue_kgkm2_mean0$unit_word,
                         " with standard deviation (SD;",
                         gsub("[()]", "", cpue_kgkm2_sd0$unit_word), ")",
                         ", estimated biomass", biomass_mt0$unit_word,
                         " with SD", biomass_sd0$unit_word,
                         ", 95% lower (LCL;", gsub("[()]", "", biomass_mt0$unit_word),
                         ") and upper (UCL;", gsub("[()]", "", biomass_mt0$unit_word),
                         ") confidence limits, and number of hauls in which ",
                         spp_print,
                         # ifelse(is.na(spp_sci), "", paste0(" (", spp_sci, ")")),
                         " were weighed")
        
        table_print0 <- table_raw |>
          dplyr::mutate(
            cpue_kgkm2_mean = formatC(x = cpue_kgkm2_mean/cpue_kgkm2_mean0$divby,
                                      digits = 2,
                                      format = "f", big.mark = ","),
            cpue_kgkm2_sd = formatC(x = cpue_kgkm2_sd/cpue_kgkm2_sd0$divby,
                                    digits = 2,
                                    format = "f", big.mark = ","),
            biomass_mt = formatC(x = biomass_mt/biomass_mt0$divby,
                                 digits = ifelse(biomass_mt0$divby>1, 2, 0),
                                 format = "f", big.mark = ",") ,
            biomass_up = formatC(x = biomass_up/biomass_mt0$divby,
                                 digits = ifelse(biomass_mt0$divby>1, 2, 0),
                                 format = "f", big.mark = ",") ,
            biomass_dw = formatC(x = biomass_dw/biomass_mt0$divby,
                                 digits = ifelse(biomass_mt0$divby>1, 2, 0),
                                 format = "f", big.mark = ",") ,
            biomass_sd = formatC(x = biomass_sd/biomass_sd0$divby,
                                 digits = ifelse(biomass_sd0$divby>1, 2, 0),
                                 format = "f", big.mark = ","))
        table_print0[is.na(table_print0)] <- 0
        table_print0[table_print0 == " NA"] <- "-"
        table_print0[table_print0 == "NA"] <- "-"
        table_print0$n_weight[table_print0$n_weight == 0] <- "-"
        
        table_print <- table_print0 |>
          dplyr::select(-srvy) |>
          flextable::as_grouped_data(groups = c("srvy_long"), columns = NULL)  |>
          flextable::as_flextable(hide_grouplabel = TRUE) |>
          flextable::set_header_labels(
            cpue_kgkm2_mean = paste0("CPUE mean ", ifelse(cpue_kgkm2_mean0$unit_wrd=="", "", paste0("\n(",cpue_kgkm2_mean0$unit_wrd, ")"))),
            cpue_kgkm2_sd = paste0("CPUE SD ", ifelse(cpue_kgkm2_sd0$unit_wrd=="", "", paste0("\n(",cpue_kgkm2_sd0$unit_wrd, ")"))),
            biomass_mt = paste0("Biomass", ifelse(biomass_mt0$unit_wrd=="", "", paste0("\n(",biomass_mt0$unit_wrd, ")"))),
            biomass_sd = paste0("Biomass SD ", ifelse(biomass_sd0$unit_wrd=="", "", paste0("\n(",biomass_sd0$unit_wrd, ")"))),
            biomass_dw = paste0("95% LCL", ifelse(biomass_mt0$unit_wrd=="", "", paste0("\n(",biomass_mt0$unit_wrd, ")"))),
            biomass_up = paste0("95% UCL", ifelse(biomass_mt0$unit_wrd=="", "", paste0("\n(",biomass_mt0$unit_wrd, ")"))),
            n_weight = "Hauls w/ weights"
          )
      }
    } else { # CPUE No/km² and population_count
      
      nickname <- paste0(nickname0, "num")
      
      table_raw <- temp |>
        dplyr::select(srvy_long, srvy, stratum,
                      cpue_nokm2_mean, cpue_nokm2_sd, population_dw, population_up,
                      population_count, population_sd, n_count, n_length)
      
      if (!include_n_length) {
        table_raw <- table_raw |>
          dplyr::select(-n_length)
      }
      
      if (nrow(table_raw) != 0) { # if none were caught, don't do any of this
        
        cpue_nokm2_mean0 <- find_units(unit = "no/km²", unt = "no/km²", dat = table_raw$cpue_nokm2_mean[table_raw$cpue_nokm2_mean != 0])
        cpue_nokm2_sd0 <- find_units(unit = "no/km²", unt = "no/km²", table_raw$cpue_nokm2_sd[table_raw$cpue_nokm2_sd != 0])
        population_count0 <- find_units(unit = "", unt = "", table_raw$population_count[table_raw$population_count != 0])
        population_sd0 <- find_units(unit = "", unt = "", table_raw$population_sd[table_raw$population_sd != 0])
        
        header <- paste0("Mean CPUE", cpue_nokm2_mean0$unit_word,
                         " with standard deviation (SD;",
                         gsub("[()]", "", cpue_nokm2_sd0$unit_word), ")",
                         ", estimated population", population_count0$unit_word,
                         " with SD", population_sd0$unit_word,
                         ", 95% lower (LCL;", gsub("[()]", "", population_count0$unit_word),
                         ") and upper (UCL;", gsub("[()]", "", population_count0$unit_word),
                         ") confidence limits, and number of hauls in which ",
                         spp_print,
                         # ifelse(is.na(spp_sci), "", paste0(" (", spp_sci, ")")),
                         " were encountered")
        
        table_print0 <- table_raw |>
          dplyr::mutate(
            cpue_nokm2_mean = formatC(x = cpue_nokm2_mean/cpue_nokm2_mean0$divby,
                                      digits = 2,
                                      format = "f", big.mark = ","),
            cpue_nokm2_sd = formatC(x = cpue_nokm2_sd/cpue_nokm2_sd0$divby,
                                    digits = 2,
                                    format = "f", big.mark = ","),
            population_count = formatC(x = population_count/population_count0$divby,
                                       digits = ifelse(population_count0$divby>1, 2, 0),
                                       format = "f", big.mark = ",") ,
            population_up = formatC(x = population_up/population_count0$divby,
                                    digits = ifelse(population_count0$divby>1, 2, 0),
                                    format = "f", big.mark = ",") ,
            population_dw = formatC(x = population_dw/population_count0$divby,
                                    digits = ifelse(population_count0$divby>1, 2, 0),
                                    format = "f", big.mark = ",") ,
            population_sd = formatC(x = population_sd/population_sd0$divby,
                                    digits = ifelse(population_sd0$divby>1, 2, 0),
                                    format = "f", big.mark = ","))
        table_print0[is.na(table_print0)] <- 0
        table_print0[table_print0 == " NA"] <- "-"
        table_print0[table_print0 == "NA"] <- "-"
        table_print0$n_count[table_print0$n_count == 0] <- "-"
        
        table_print <- table_print0 |>
          dplyr::select(-srvy) |>
          flextable::as_grouped_data(groups = c("srvy_long"), columns = NULL)  |>
          flextable::as_flextable(hide_grouplabel = TRUE) |>
          flextable::set_header_labels(
            cpue_nokm2_mean = paste0("CPUE mean", ifelse(cpue_nokm2_mean0$unit_wrd=="", "", paste0("\n(", cpue_nokm2_mean0$unit_wrd, ")"))),
            cpue_nokm2_sd = paste0("CPUE SD ", ifelse(cpue_nokm2_sd0$unit_wrd=="", "", paste0("\n(", cpue_nokm2_sd0$unit_wrd, ")"))),
            population_count = paste0("Population",
                                      ifelse(population_count0$unit_wrd=="", "", paste0("\n(", population_count0$unit_wrd, ")"))),
            population_sd = paste0("Population SD", ifelse(population_sd0$unit_wrd=="", "", paste0("\n(", population_sd0$unit_wrd, ")"))),
            population_dw = paste0("95% LCL", ifelse(population_count0$unit_wrd=="", "", paste0("\n(", population_count0$unit_wrd, ")"))),
            population_up = paste0("95% UCL", ifelse(population_count0$unit_wrd=="", "", paste0("\n(", population_count0$unit_wrd, ")"))),
            n_count = "Hauls w/ counts"
          )
      }
    }
    
    header <- paste0(header,
                     # spp_print,
                     # ifelse(is.na(spp_sci), "", paste0(" (", spp_sci, ")")),
                     # " were encountered and weighed ",
                     " during the ",
                     maxyr," ", SURVEY,
                     " survey",plural_surveys,". ",
                     ifelse(length(setdiff(srvy1, unique(table_raw$srvy)))>0,
                            paste0("This taxon was not encountered in the ",
                                   maxyr, " ",
                                   haul_cruises_maxyr$srvy_long[haul_cruises_maxyr$srvy != unique(table_raw$srvy)],
                                   " survey. "),
                            ""))# ifelse(!include_n_length, "No lengths were collected for this taxon. ", ""))
    
    table_print <- table_print |>
      flextable::bold(i = ~ (stratum == "Total") ) |>
      flextable::valign(valign = "top") |>
      flextable::set_header_labels(stratum = "Stratum")  |>
      theme_flextable_nmfstm(row_lines = FALSE,
                             body_size = 10,
                             header_size = 10,
                             pgwidth = full_page_portrait_width)  |>
      flextable::width(width = ((full_page_portrait_width-.6-.9)/6), unit = "in") |> # need to not account for the srvy_long column
      flextable::width(j = 1, width = .6, unit = "in") |>
      flextable::width(j = 2, width = .9, unit = "in") |>
      
      # flextable::width(j = (ncol(table_print0)-1), width = .9, unit = "in") |>
      # flextable::width(width = ((full_page_portrait_width-.4)/(ncol(table_print0)-1)), unit = "in") |>
      # flextable::width(width = .4, unit = "in", j = c("stratum")) |>
      flextable::align(align = "right", part = "all") |>
      flextable::align(align = "center", part = "body", j = "stratum") |>
      flextable::merge_v(j = 1:2, part = "header")
    
    if (include_n_length) { # if lengths were collected, include the column
      table_print <- table_print |>
        flextable::set_header_labels(
          n_length = "Hauls w/ lengths") |>
        flextable::width(width = .5, unit = "in", j = "n_length")
    }
    
    # if (length(unique(table_raw$srvy)) > 1) {
    table_print <- table_print |>
      flextable::align(j = 1, i = ~ !is.na(srvy_long), align = "left") |>
      flextable::bold(j = 1, i = ~ !is.na(srvy_long) ) |>
      flextable::padding(j = 1, i = ~ is.na(srvy_long),
                         padding.left = 7) |>
      flextable::hline(i = ~ (stratum == "Total"), part = "body")
    # }
    
    res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
  }
}
```

```{r fig-timeseries-[spp]-prep, eval = TRUE}
pcol <- viridis::mako(n = 2, begin = .2, end = .6, direction = -1)

if (length(spp_code) > 1) {
  table_raw <- biomass |>
    dplyr::filter(common_name %in% spp_print)
} else {
  table_raw <- biomass |>
    dplyr::filter(species_code %in% spp_code)
}

table_raw <- table_raw |>
  dplyr::filter(stratum == 999) |> 
  dplyr::select(srvy, year, 
                biomass_mt, population_count, 
                biomass_up, population_up, 
                biomass_dw, population_dw) |> 
  tidyr::pivot_longer(cols = c(biomass_mt, population_count, 
                               biomass_up, population_up, 
                               biomass_dw, population_dw), 
                      names_to = "var", 
                      values_to = "val") |> 
  dplyr::mutate(coll = dplyr::case_when(
    var == "biomass_mt" ~ "val", 
    var == "population_count" ~ "val", 
    var == "biomass_up" ~ "ci_up", 
    var == "population_up" ~ "ci_up", 
    var == "biomass_dw" ~ "ci_dw", 
    var == "population_dw" ~ "ci_dw"
  ), 
  var = dplyr::case_when(
    grepl(x = var, pattern = "biomass") ~ "biomass_mt", 
    grepl(x = var, pattern = "population") ~ "population_count")) |> 
  tidyr::pivot_wider(id_cols = c(srvy, year, var), 
                     names_from = coll, 
                     values_from = val) |>   
  dplyr::left_join(y = haul_cruises |> 
                     dplyr::select(srvy, srvy_long) |> 
                     dplyr::distinct(),
                   by = "srvy") |>
  dplyr::mutate(
    print_name = spp_print, 
    srvy_long0 = srvy_long, 
    srvy_long = stringr::str_to_title(srvy_long), 
    y_long = dplyr::case_when(
      grepl(x = var, pattern = "biomass") ~ "Biomass", 
      grepl(x = var, pattern = "population") ~ "Population"
    ) ) |> 
  dplyr::ungroup() 

# find missing years in timeseries and re-enter them so plot breaks for missing years
yr_missing <- data.frame()
for (i in 1:length(unique(table_raw$srvy_long))){
  temp <- table_raw[table_raw$srvy_long %in% unique(table_raw$srvy_long)[i], ]
  
  yr_missing <- yr_missing |> 
    dplyr::bind_rows(tidyr::crossing(year = setdiff((min(temp$year):max(temp$year)),
                                                    unique(temp$year)),
                                     y_long = unique(table_raw$y_long), 
                                     # var = unique(table_raw$var), 
                                     srvy_long = unique(table_raw$srvy_long)[i]) ) # |> 
  # dplyr::mutate(var = dplyr::case_when(
  #   y_long == "Biomass" ~ "biomass_mt",
  #   y_long == "Population" ~ "population_count"
  # ))
  
}

yr_missing <- yr_missing |>
  dplyr::left_join(y = haul_cruises |> 
                     dplyr::select(srvy, srvy_long) |> 
                     dplyr::distinct() |> 
                     dplyr::mutate(srvy_long0 = srvy_long, 
                                   srvy_long = stringr::str_to_title(srvy_long)),
                   by = "srvy_long")

a_bio <- find_units(unit = "t", 
                    unt = "t", 
                    dat = max(table_raw$val[table_raw$y_long == "Biomass"])) 

a_pop <- find_units(unit = "", 
                    unt = "", 
                    dat = max(table_raw$val[table_raw$y_long == "Population"])) 

table_raw <- table_raw |> 
  dplyr::bind_rows(yr_missing) |> 
  # dplyr::bind_rows(yr_missing |> dplyr::mutate(var = "population_count")) |> 
  dplyr::mutate(
    species_name = spp_print, 
    common_name = spp_print, 
    print_name = spp_print, 
    taxon = spp_taxon, 
    col = dplyr::case_when(
      srvy_long == "Eastern Bering Sea" ~ pcol[1],
      srvy_long == "Northern Bering Sea" ~ pcol[2]), 
    var_ = dplyr::case_when(
      y_long == "Biomass" ~ 
        paste0("Biomass", 
               # if no bio divby or pop divby (bc then would stay on same line)
               ifelse(a_bio$unit_word == " (t)" & a_pop$unit_word == "", 
                      "", "\n"), a_bio$unit_word), 
      y_long == "Population" ~ 
        paste0("Population", ifelse(a_pop$unit_word == "", "", "\n"), a_pop$unit_word)        
    ), 
    divby = dplyr::case_when(
      y_long == "Biomass" ~ a_bio$divby, 
      y_long == "Population" ~ a_pop$divby        
    ),
    unit_wrd = dplyr::case_when(
      y_long == "Biomass" ~ a_bio$unit_wrd, 
      y_long == "Population" ~ a_pop$unit_wrd        
    ),
    unit_word = dplyr::case_when(
      y_long == "Biomass" ~ a_bio$unit_word, 
      y_long == "Population" ~ a_pop$unit_word        
    ),
    y = val/divby, 
    y_ci_dw = ci_dw/divby, 
    y_ci_up = ci_up/divby, 
    group = paste0(srvy, "_", y_long)) |> 
  dplyr::relocate(srvy, year, var, val, y) |>
  dplyr::arrange(desc(year))  |> 
  dplyr::ungroup() |> 
  dplyr::mutate(var = dplyr::case_when(
    y_long == "Biomass" ~ "biomass_mt",
    y_long == "Population" ~ "population_count", 
  ))

table_raw1 <- table_raw


# find mean for mean line
table_raw_mean <- table_raw |> 
  dplyr::group_by(srvy_long, srvy, y_long, group, var_) |> 
  dplyr::summarise(y_mean = mean(y, na.rm = TRUE), 
                   val_mean = mean(val, na.rm = TRUE)) |> 
  dplyr::filter(!is.na(y_mean))  |> 
  dplyr::ungroup() |> 
  dplyr::left_join(
    biomass |>
      dplyr::filter(stratum == 999 &
                      year >= min(table_raw$year, na.rm = TRUE) # 1987
      ) |> 
      dplyr::group_by(survey_definition_id) |> 
      dplyr::summarise(minyr = min(year, na.rm = TRUE), 
                       maxyr = max(year, na.rm = TRUE)) |> 
      dplyr::left_join(y = haul_cruises |> 
                         dplyr::select(survey_definition_id, srvy_long) |> 
                         dplyr::distinct()) |> 
      dplyr::select(-survey_definition_id) |> 
      dplyr::mutate(srvy_long = stringr::str_to_title(srvy_long)) |> 
      dplyr::ungroup())

timeseries_plot <- function(table_raw, table_raw_mean, nickname, height, width, legend_font_size = 10) {
  
  # if (length(unique(table_raw$var_)) == 1) {
  #   table_raw$var_ <- gsub(x = table_raw$var_, replacement = "", pattern = "\n", fixed = TRUE)
  #   table_raw$var_ <- gsub(x = table_raw$var_, replacement = " ", pattern = "  ", fixed = TRUE)
  # }
  
  
  # anno<-NA
  # temp<-setdiff(x = unique(table_raw$srvy), 
  #               y = unique(table_raw_mean$srvy))
  # if (length(temp) != 0) {
  #   anno <- paste0("Data for this species in the\n", 
  #                  temp, 
  #                  " is too limited to plot.")
  #   
  #   col_anno <- table_raw$col[which(unique(table_raw$srvy)==temp)]
  #   col <- table_raw$col[which(unique(table_raw$srvy)!=temp)]
  # }
  
  figure_print <-
    # general plotting aesthetics
    ggplot2::ggplot(data = table_raw,
                    mapping = aes(x = year, 
                                  y = y, 
                                  group = group,
                                  color = srvy_long)) +
    # plot mean line 
    ggplot2::geom_segment(
      data = table_raw_mean,
      mapping = aes(x = minyr, 
                    xend = maxyr, 
                    y = y_mean, 
                    yend = y_mean),
      alpha = .5,
      linetype = "dashed", 
      linewidth = 1.5) +
    # plot points and lines
    ggplot2::geom_line(linewidth = .5) +
    ggplot2::geom_point(size = 1.5, mapping = aes(shape = srvy_long)) + 
    # axis aesthetics 
    # ggplot2::ggtitle(spp_print) +  # No title
    ggplot2::scale_x_continuous(
      name = "", # "Year", 
      # limits = range(yrs_plotted, na.rm = TRUE), 
      labels = scales::label_number(accuracy = 1, big.mark = ""))  +
    ggplot2::scale_y_continuous(
      name = "", # spp_print, 
      expand = c(0, 0),
      breaks = breaks_pretty(), 
      labels = scales::label_number(big.mark = ","), # accuracy = 1, 
      limits = c(0, NA)) +
    # survey area color aesthetics
    ggplot2::scale_color_manual(values = pcol) +
    # plot error bars
    ggplot2::geom_errorbar(mapping = aes(ymin = y_ci_dw, ymax = y_ci_up), 
                           width = .2,
                           alpha = 0.5) + 
    # Set y axis minimum to always be 0 & remove resulting "y" label
    # ylim(0, NA) +
    # ylab(" ") +
    
    # aesthetics
    # Create & position legend title
    ggplot2::labs(color = stringr::str_to_title(spp_print)) +  # force title case
    ggplot2::labs(shape = stringr::str_to_title(spp_print)) +
    ggplot2::guides(color = guide_legend(title.position = "top",
                                         title.hjust = 0.5,
                                         title.vjust = -0.5),
                    shape = guide_legend(title.position = "top",
                                         title.hjust = 0.5,
                                         title.vjust = -0.5)) +
    ggplot2::theme( 
      strip.placement = "outside",
      strip.background = element_blank(), 
      strip.text = element_text(size = 10, face = "bold"), 
      panel.background = element_rect(fill = "white"),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.x = element_line(colour = "grey95"),
      panel.border = element_rect(fill = NA, colour = "grey20"),
      legend.text = element_text(size = legend_font_size),
      legend.background = element_rect(colour = "transparent", 
                                       fill = "transparent"),
      legend.key = element_rect(colour = "transparent",
                                fill = "transparent"),
      axis.title = element_text(size = legend_font_size, face = "bold"),
      axis.text = element_text(size = legend_font_size),
      legend.position = "bottom", 
      legend.box = "horizontal",
      legend.box.spacing = unit(0, "pt"),
      legend.margin=margin(0, 0, 0, 0)) + 
    ggplot2::facet_grid(rows = vars(var_), 
                        scales = "free", 
                        switch = "both") 
  # if (!is.na(anno[1])) {
  #   figure_print <- figure_print +
  #     ggplot2::geom_text(x = Inf, 
  #                        y = -Inf, 
  #                        hjust = 1.2, 
  #                        vjust = -.3, 
  #                        label = anno, 
  #                        show.legend = FALSE, 
  #                        size = 4, 
  #                        fontface = "italic",
  #                        color = col_anno)
  # }
  # If there's only one survey, remove legend with color guide.
  if (length(unique(table_raw$srvy_long)) == 1) {
    figure_print <- figure_print + ggplot2::theme(legend.position = "none")
  }
  
  temp <- table_raw |> 
    dplyr::select(y_long, unit_word, unit_wrd) |> 
    unique() |> 
    dplyr::mutate(str0 = paste0(
      tolower(y_long),
      paste0(ifelse(unit_wrd == "", "", unit_word))))
  
  header <- paste0("Time series of ", 
                   spp_print,
                   # ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
                   " ",
                   text_list(temp$str0), 
                   " from the ", 
                   min(table_raw$year, na.rm = TRUE),"-", 
                   max(table_raw$year, na.rm = TRUE), " ", 
                   # range_text(range(table_raw$year)), " ", 
                   ifelse(length(unique(table_raw$srvy_long0)) > 1, 
                          SURVEY, 
                          unique(table_raw$srvy_long0)), 
                   " survey", 
                   ifelse(length(unique(table_raw$srvy_long0)) > 1, plural_surveys, "")," (points and solid lines). Dashed lines represent time-series average and error bars represent estimated 95% confidence intervals. ")
  
  temp <- lengths |>
    dplyr::filter(species_code %in% spp_code &
                    srvy %in% srvy)
  # if (min(table_raw$year) > 1987) {
  # header <- paste0(header, "The survey program adopted methods to reliably distinguish ",spp_print," in ", min(table_raw$year),", truncating the displayed time series. ")
  # }
  return(list("figure_print" = figure_print, 
              "table_raw" = table_raw, 
              "header" = header, 
              "height" = height, 
              "width" = width, 
              "nickname" = nickname, 
              "table_raw_mean" = table_raw_mean, 
              "unit_wrd" = unique(table_raw$unit_wrd[table_raw$var == "biomass_mt"])))
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}

```

```{r fig-timeseries-[spp]-data}
nickname <- paste0("fig-timeseries-", spp_file, "-data")
height <- 3
width <- full_page_portrait_width
legend_font_size <- 10

temp <- timeseries_plot(table_raw = table_raw1, table_raw_mean, nickname, height, width, legend_font_size = 10)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-timeseries-[spp]-comm}
nickname <- paste0("fig-timeseries-", spp_file, "-comm")
height <- 3
width <- full_page_portrait_width
legend_font_size <- 8
table_raw0 <- table_raw1 |> dplyr::filter(var == "biomass_mt")

temp <- timeseries_plot(table_raw = table_raw0, table_raw_mean, nickname, height, width, legend_font_size = legend_font_size)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-timeseries-[spp]-data-alt}
nickname <- paste0("fig-timeseries-", spp_file, "-data-alt")
height <- 3
legend_font_size <- 12

temp <- timeseries_plot(
  table_raw = table_raw1 |> dplyr::mutate(srvy_long = srvy), 
  table_raw_mean = table_raw_mean |> dplyr::mutate(srvy_long = srvy), 
  nickname, height, width, legend_font_size = 10)
data_timeseries <- temp$figure_print + 
  ggplot2::theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))
data_timeseries_mean <- temp$table_raw_mean
data_timeseries_unit_wrd <- temp$unit_wrd
data_timeseries_txt <- temp$header
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-timeseries-[spp]-pres}
nickname <- paste0("fig-timeseries-", spp_file, "-pres")
height <- 3
legend_font_size <- 12
table_raw0 <- table_raw1 |> dplyr::filter(var == "biomass_mt") |> dplyr::mutate(srvy_long = srvy)

temp <- timeseries_plot(table_raw = table_raw0, table_raw_mean, nickname, height, width, legend_font_size = 10)
pres_timeseries <- temp$figure_print + 
  ggplot2::theme(plot.margin=grid::unit(c(0,0,0,0), "mm"))
pres_timeseries_mean <- temp$table_raw_mean
pres_timeseries_unit_wrd <- temp$unit_wrd
pres_timeseries_txt <- temp$header
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-combined-[spp]-data}

nickname <- paste0("fig-combined-", spp_file, "-data")
height <- 4 # full_page_portrait_height-2.5
width <- full_page_portrait_width

comm_dist1 <- comm_dist  +
  ggplot2::guides(
    fill = guide_legend(
      title.position = NULL, # "left",
      label.position = "right",
      # nrow = 1,
      override.aes = list(color = NA)),
    color = "none")  +
  ggplot2::theme(
    plot.title = element_blank(),
    legend.title = element_blank(), #element_text(size = 8, face = "bold"),
    legend.text = element_text(size = 8),
    axis.text = element_text(size = 8),
    axis.title = element_blank(),
    strip.text = element_text(size = 8, face = "bold"),
    plot.margin = grid::unit(c(0,0,0,0), "mm"),
    legend.key.width = unit(0.4, "cm"),
    legend.key.height = unit(0.15, "cm") ) # Make them shorter

pres_timeseries1 <- data_timeseries + 
  ggplot2::guides(fill = "none") +
  ggplot2::labs(color = "") + 
  ggplot2::labs(shape = "") +
  ggplot2::guides(
    color = guide_legend(title.position = NULL, nrow = 1),
    shape = guide_legend(title.position = NULL, nrow = 1))  +
  ggplot2::theme(
    plot.title = element_blank(), 
    legend.text = element_text(size = 8), 
    strip.text = element_text(size = 8, face = "bold"), 
    axis.title.y = element_text(size = 8), 
    axis.title.x = element_blank(), 
    axis.text = element_text(size = 8), 
    plot.margin = grid::unit(c(0,0,0,0), "mm"),
    legend.position = c(0.25, 0.98))

if (exists("comm_size")) {
  comm_size1 <- comm_size + 
    ggplot2::theme(
      plot.title = element_blank(), 
      legend.text = element_text(size = 8), 
      axis.text = element_text(size = 8),
      axis.title.y = element_text(size = 8),
      axis.title.x = element_blank(),
      strip.text = element_text(size = 8, face = "bold"), 
      plot.margin = grid::unit(c(0,0,0,0), "mm"), 
      legend.box.background = element_rect(color = "white", fill = "white", linewidth = 1), # Box border and fill
      legend.key.height = unit(0.15, "cm"),
      legend.key.width = unit(0.4, "cm"),
      legend.position = c(.77, 0.5)) # Make them shorter
  
} else {
  pres_size_txt <- "There are no sizecomps for this species. "
  comm_size1 <- NULL
  
  comm_dist1 <- comm_dist  +
    ggplot2::guides(
      fill = guide_legend(
        # order = 1,
        title.position = NULL, # "left",
        label.position = "right",
        # nrow = 2,
        # title.hjust = 0.5,
        override.aes = list(color = NA)),
      color = "none")  +
    ggplot2::theme(
      legend.position = "right",
      plot.title = element_blank(),
      legend.title = element_blank(), #element_text(size = 8, face = "bold"),
      legend.text = element_text(size = 8),
      axis.text = element_text(size = 8),
      axis.title = element_blank(),
      strip.text = element_text(size = 8, face = "bold"),
      plot.margin = grid::unit(c(0,0,0,0), "mm"),
      # axis.text.x = element_text(angle = 45, hjust = .8),  #, vjust = 0.05, hjust = 1),
      legend.box.spacing = unit(.2, "cm"), # Increase the space to 1 cm
      legend.key.height = unit(0.15, "cm"),
      legend.key.width = unit(0.6, "cm") ) # Make them shorter
}

temp1 <- cowplot::plot_grid(
  comm_dist1,
  pres_timeseries1, 
  nrow = 2, 
  align = "v",   # Align vertically
  axis = "l",     # Align by the left axis
  rel_heights = c(.5,.5)) 

# figure_print <- cowplot::plot_grid(
#   temp1, 
#   NULL,
#   comm_size1, 
#   ncol = 3, 
#   rel_widths = c(.55,.05,.4),
#   align = "v",   # Align vertically
#   axis = "l")     # Align by the left axis
#   
if (exists("comm_size")) {
  figure_print <- cowplot::plot_grid(
    temp1, 
    NULL,
    comm_size1, 
    ncol = 3, 
    rel_widths = c(.6,.025,.4),
    align = "v",   # Align vertically
    axis = "l")     # Align by the left axis
} else {
  figure_print <- temp1
}

# Then use ggdraw() to add a custom label on top of the combined plot
figure_print <- cowplot::ggdraw(figure_print) +
  cowplot::draw_label("A", 
                      x = ifelse(exists("comm_size"), 0.06, 0.01), 
                      y = 0.94, hjust = 0, vjust = 0, size = 16) +
  cowplot::draw_label(ifelse((exists("comm_size")), "C", "B"), 
                      x = ifelse(exists("comm_size"), 0.06, 0.01), 
                      y = 0.5, hjust = 0, vjust = 0, size = 16) #+
# cowplot::draw_label(ifelse((exists("comm_size")), "D", "C"), x = 0.77, y = 0.32, hjust = 0, vjust = 0, size = 16)

if (exists("comm_size")) {
  figure_print <- cowplot::ggdraw(figure_print) +
    cowplot::draw_label("B", x = 0.6, y = 0.94, hjust = 0, vjust = 0, size = 16)
}

fig_srvy <- paste0(paste0(tolower(pres_stats[,1]), collapse = " and "), 
                   " Bering Sea ")
fig_srvy_plural <- ifelse(nrow(pres_stats)>1, "s", "")

temp <- data_timeseries_mean |> 
  dplyr::mutate(unit = gsub(".*\\(([^)]+)\\).*", "\\1", var_), 
                val_mean = ifelse(val_mean <= 1, ">1", val_mean)) |>
  tidyr::pivot_wider(id_cols = srvy, names_from = y_long, values_from = c("y_mean", "val_mean", "unit"))

header <- paste0(
  toupper(substr(x = spp_print, 1, 1)), substr(x = spp_print, 2, nchar(spp_print)), #ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
  " ",
  "(A) CPUE distribution (kg/km^2^) ",
  ifelse((exists("comm_size")), "and (B) total abundance-at-length (cm) estimates by sex scaled to the total estimated population ", ""), 
  "from the ", range_text(c(compareyr, maxyr)), " ", fig_srvy, "survey", fig_srvy_plural, 
  ". (",ifelse(exists("comm_size"), "C", "B"),") Biomass and population time series estimated from the ",
  substr(x = gsub("[^0-9]", "", data_timeseries_txt), start = 1, stop = 4),"-2025 ", 
  ifelse(exists("comm_size"), "", fig_srvy), 
  "survey",fig_srvy_plural," (points and solid lines, with estimated 95% confidence intervals error bars) and time series mean (dashed lines; ",
  ifelse(spp_file == "tunicates", 
         paste0(temp$srvy, " mean: ", 
                formatC(x = temp$val_mean_Biomass, digits = 0, big.mark = ",", format = "f"), " ", 
                "t", # temp$unit_Biomass,  
                " biomass", 
                collapse = "; "),  
         paste0(temp$srvy, " mean: ", 
                formatC(x = temp$val_mean_Biomass, digits = 0, big.mark = ",", format = "f"), " ", 
                "t", # temp$unit_Biomass,  
                " biomass", 
                # ifelse(spp_file == "tunicates", "", 
                # paste0(
                ", ", 
                formatC(x = temp$val_mean_Population, digits = 0, big.mark = ",", format = "f"), 
                # " ", substr(x = temp$unit_Population, start = 1, stop = nchar(temp$unit_Population)-1), 
                " individuals", # ), 
                collapse = "; ")), 
  "). ")

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-combined-[spp]-comm, eval = FALSE}

nickname <- paste0("fig-combined-", spp_file, "-comm")
height <- 3 # full_page_portrait_height-2.5
width <- full_page_portrait_width

comm_dist1 <- comm_dist  +
  ggplot2::guides(
    fill = guide_legend(
      title.position = NULL, # "left",
      label.position = "right",
      # nrow = 1,
      override.aes = list(color = NA)),
    color = "none")  +
  ggplot2::theme(
    plot.title = element_blank(),
    legend.title = element_blank(), #element_text(size = 8, face = "bold"),
    legend.text = element_text(size = 8),
    axis.text = element_text(size = 8),
    axis.title = element_blank(),
    strip.text = element_text(size = 8, face = "bold"),
    plot.margin = grid::unit(c(0,0,0,0), "mm"),
    legend.key.width = unit(0.4, "cm"),
    legend.key.height = unit(0.15, "cm") ) # Make them shorter

pres_timeseries1 <- pres_timeseries + 
  ggplot2::guides(fill = "none") +
  ggplot2::labs(color = "") + 
  ggplot2::labs(shape = "") +
  ggplot2::guides(
    color = guide_legend(title.position = NULL, nrow = 1),
    shape = guide_legend(title.position = NULL, nrow = 1))  +
  ggplot2::theme(
    plot.title = element_blank(), 
    legend.text = element_text(size = 8), 
    strip.text = element_text(size = 8, face = "bold"), 
    axis.title.y = element_text(size = 8), 
    axis.title.x = element_blank(), 
    axis.text = element_text(size = 8), 
    plot.margin = grid::unit(c(0,0,0,0), "mm"),
    legend.position = c(0.25, 0.98))

if (exists("comm_size")) {
  comm_size1 <- comm_size + 
    ggplot2::theme(
      plot.title = element_blank(), 
      legend.text = element_text(size = 8), 
      axis.text = element_text(size = 8),
      axis.title.y = element_text(size = 8),
      axis.title.x = element_blank(),
      strip.text = element_text(size = 8, face = "bold"), 
      plot.margin = grid::unit(c(0,0,0,0), "mm"), 
      legend.box.background = element_rect(color = "white", fill = "white", linewidth = 1), # Box border and fill
      legend.key.height = unit(0.15, "cm"),
      legend.key.width = unit(0.4, "cm"),
      legend.position = c(.77, 0.5)) # Make them shorter
  
} else {
  pres_size_txt <- "There are no sizecomps for this species. "
  comm_size1 <- NULL
  
  comm_dist1 <- comm_dist  +
    ggplot2::guides(
      fill = guide_legend(
        # order = 1,
        title.position = NULL, # "left",
        label.position = "right",
        # nrow = 2,
        # title.hjust = 0.5,
        override.aes = list(color = NA)),
      color = "none")  +
    ggplot2::theme(
      legend.position = "right",
      plot.title = element_blank(),
      legend.title = element_blank(), #element_text(size = 8, face = "bold"),
      legend.text = element_text(size = 8),
      axis.text = element_text(size = 8),
      axis.title = element_blank(),
      strip.text = element_text(size = 8, face = "bold"),
      plot.margin = grid::unit(c(0,0,0,0), "mm"),
      # axis.text.x = element_text(angle = 45, hjust = .8),  #, vjust = 0.05, hjust = 1),
      legend.box.spacing = unit(.2, "cm"), # Increase the space to 1 cm
      legend.key.height = unit(0.15, "cm"),
      legend.key.width = unit(0.6, "cm") ) # Make them shorter
}

temp1 <- cowplot::plot_grid(
  comm_dist1,
  pres_timeseries1, 
  nrow = 2, 
  align = "v",   # Align vertically
  axis = "l",     # Align by the left axis
  rel_heights = c(.6,.4)) 

# figure_print <- cowplot::plot_grid(
#   temp1, 
#   NULL,
#   comm_size1, 
#   ncol = 3, 
#   rel_widths = c(.55,.05,.4),
#   align = "v",   # Align vertically
#   axis = "l")     # Align by the left axis
#   
if (exists("comm_size")) {
  figure_print <- cowplot::plot_grid(
    temp1, 
    NULL,
    comm_size1, 
    ncol = 3, 
    rel_widths = c(.6,.025,.4),
    align = "v",   # Align vertically
    axis = "l")     # Align by the left axis
} else {
  figure_print <- temp1
}

# Then use ggdraw() to add a custom label on top of the combined plot
figure_print <- cowplot::ggdraw(figure_print) +
  cowplot::draw_label("A", 
                      x = ifelse(exists("comm_size"), 0.06, 0.01), y = 0.94, hjust = 0, vjust = 0, size = 16) +
  cowplot::draw_label(ifelse((exists("comm_size")), "C", "B"), 
                      x = ifelse(exists("comm_size"), 0.06, 0.01), y = 0.32, hjust = 0, vjust = 0, size = 16) #+
# cowplot::draw_label(ifelse((exists("comm_size")), "D", "C"), x = 0.77, y = 0.32, hjust = 0, vjust = 0, size = 16)

if (exists("comm_size")) {
  figure_print <- cowplot::ggdraw(figure_print) +
    cowplot::draw_label("B", x = 0.6, y = 0.94, hjust = 0, vjust = 0, size = 16)
}

header <- paste0(
  toupper(substr(x = spp_print, 1, 1)), substr(x = spp_print, 2, nchar(spp_print)), #ifelse(is.na(spp_sci), "", paste0(" (",spp_sci,")")), 
  " ",
  "(A) CPUE distribution (kg/km^2^) ",
  ifelse((exists("comm_size")), "and (B) total abundance-at-length (cm) estimates by sex scaled to the total estimated population ", ""), 
  "from the ", range_text(c(compareyr, maxyr)), " eastern (EBS) and northern (NBS) Bering Sea survey",plural_surveys,
  ". (",ifelse((exists("comm_size")), "C", "B"),") Biomass time series during the ",
  substr(x = gsub("[^0-9]", "", pres_timeseries_txt), start = 1, stop = 4),"-2025 ", # SURVEY,
  "survey",plural_surveys," (points and solid lines", 
  ", with estimated 95% confidence intervals error bars", ") and time series mean (dashed lines). ")
# ,
#   "(",ifelse((exists("comm_size")), "D", "C"),") Photo of ", ifelse(tolower(substr(spp_print, 1, 1)) %in% c("a", "e", "i", "o", "u"), "an ", "a "), spp_print, ". ")

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-combined-[spp]-pres, eval = FALSE}
nickname <- paste0("fig-combined-", spp_file, "-pres")
height <- 7.5
width <- 10

if (exists("pres_size")) {
  temp1 <- cowplot::plot_grid(pres_dist +
                                ggplot2::guides(
                                  fill = guide_legend(title.position = "left",
                                                      title.hjust = 0.5, 
                                                      nrow = 1)) +
                                ggplot2::theme(
                                  legend.title = element_text(size = 8, face = "bold"), 
                                  legend.key.height = unit(0.3, "cm") # Make them shorter
                                ),  
                              NULL, 
                              pres_size +
                                ggplot2::theme(
                                  # legend.key.size = unit(0.5, "cm"),  # Adjust overall key size
                                  # legend.key.width = unit(0.3, "cm"), # Make them even narrower
                                  legend.key.height = unit(0.3, "cm") # Make them shorter
                                ), 
                              ncol = 3, 
                              rel_widths = c(1,.2,.8)) # 1, .1., .9 worked for presentations
} else {
  pres_size_txt <- "There are no sizecomps for this species. "
  temp1 <- cowplot::plot_grid(pres_dist, 
                              NULL, 
                              ncol = 2, 
                              rel_widths = c(1,1))
}
temp2 <- cowplot::plot_grid(pres_timeseries + 
                              ggplot2::ggtitle("") + 
                              ggplot2::guides(fill = "none") +
                              ggplot2::labs(color = "") + 
                              ggplot2::labs(shape = "") +
                              ggplot2::theme(legend.position = "none"), 
                            NULL,
                            ncol = 2, 
                            rel_widths = c(1.4, .6)) 

# then combine with the top row for final plot
figure_print <- cowplot::plot_grid(temp1, temp2, nrow = 2, rel_heights = c(1.2,.8))

temp <- dplyr::left_join(
  pres_timeseries_mean |> 
    dplyr::rename(srvy = srvy_long), 
  pres_stats)

figure_print <- ggdraw(add_sub(
  plot = figure_print, 
  size = 10, 
  label = paste0(paste0(spp_print, "\n"), 
                 paste0(temp$srvy, " Bio Mean: ", 
                        round(x = temp$y_mean, digits = 1),
                        " ", pres_timeseries_unit_wrd, " ", maxyr, ": ",
                        temp$`Biomass`," (",
                        gsub(pattern = "\n", replace = " ", 
                             x = temp$`% Change\nin Biomass`, fixed = TRUE), ")", 
                        ". \n  ", temp$`Observed Catch Totals`, ". ", 
                        collapse = "\n") )
))
# }
header <- header0 <- paste0(
  "Top right: ", pres_dist_txt, 
  "Top left: ", 
  "Total abundance-at-length estimates by sex encountered during the ", maxyr, " eastern and northern Bering Sea surveys. Length distributions are scaled to the total estimated population size. ", # pres_size_txt, 
  "Bottom right: ", pres_timeseries_txt)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r remove-odds-ends}
remove("comm_dist")
remove("comm_size")
remove("pres_dist")
remove("pres_size")
remove("pres_timeseries_mean")
remove("pres_timeseries")
remove("pres_stats")
```

