---
output:
  word_document: 
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: styles_reference.docx
    df_print: kable
csl: "../cite/citestyle.csl"
bibliography: "../cite/bibliography.bib"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
cnt_pre0 <- 0
```

# Appendix A

## tab_hauls_catch_

```{r tab_app_hauls_catch_}
# nickname0 <- "tab_app_hauls_catch_" 
# cnt_tables <- 0
# 
# temp <- tidyr::crossing(vessel_info %>% 
#                           dplyr::select(vessel_name, vessel_ital), 
#                         haul_cruises_maxyr %>% 
#                           dplyr::select(SRVY_long, SRVY))
# 
# for (iii in 1:nrow(temp)) {
#   table_raw <- catch_haul_cruises_maxyr %>% 
#     dplyr::filter(year == maxyr &
#                     SRVY == temp$SRVY[iii]) %>%
#     dplyr::left_join(
#       x = ., 
#       y = report_spp1 %>% 
#         dplyr::select(species_code, species_name, print_name), 
#       by = "species_code") %>% 
#     dplyr::filter(!is.na(print_name)) %>% 
#     dplyr::select(stationid, start_time, haul, start_latitude, start_longitude, end_latitude, end_longitude, bottom_depth, duration, distance_fished, net_width, net_measured, performance, weight, print_name) %>% 
#     dplyr::group_by(stationid, start_time, haul, start_latitude, start_longitude, end_latitude, end_longitude, bottom_depth, duration, distance_fished, net_width, net_measured, performance, print_name) %>% 
#     dplyr::summarise(weight = as.character(round(sum(weight, na.rm  = TRUE), 0))) %>% 
#     dplyr::ungroup() %>% 
#     tidyr::pivot_wider(names_from = print_name, 
#                        values_from = weight, 
#                        values_fill = "-") %>%
#     tidyr::separate(data = ., col = start_time, into = c("Date", "Time"), sep = " ", remove = TRUE) %>% 
#     dplyr::mutate(across(where(is.numeric), 
#                          formatC, big.mark=",", digits = 1, format = "f")) %>% 
#     dplyr::rename(#"Start date and time"# and time" 
#       #= start_time,
#       "Haul number" = haul,
#       "Start latitude" = start_latitude,
#       "Start longitude" = start_longitude,
#       "End latitude" = end_latitude,
#       "End longitude" = end_longitude,
#       "Bottom depth _m__" = bottom_depth,
#       "Duration (_h__)" = duration,
#       "Distance fished _km__" = distance_fished,
#       "Net width _m__" = net_width,
#       "Net measured___" = net_measured,
#       "Performance" = performance) 
#   
#   table_raw <- data.frame(t(data.frame(table_raw)))
#   names(table_raw) <- table_raw["stationid", ]
#   table_raw <- table_raw[!(rownames(table_raw) %in% "stationid"), ]
#   rownames(table_raw) <- gsub(
#     pattern = ".", 
#     replacement = " ", 
#     x = rownames(table_raw), fixed = TRUE)
#   rownames(table_raw) <- gsub(
#     pattern = "___", 
#     replacement = "?", 
#     x = rownames(table_raw), fixed = TRUE)
#   rownames(table_raw) <- gsub(
#     pattern = "__", 
#     replacement = ")", 
#     x = rownames(table_raw), fixed = TRUE)
#   rownames(table_raw) <- gsub(
#     pattern = "_", 
#     replacement = "(", 
#     x = rownames(table_raw), fixed = TRUE)  
#   
#   table_print1 <- table_raw
#   table_print1$row <- rownames(table_raw) 
#   table_raw00 <- table_raw
#   
#   table_print1 <- table_print1 %>% 
#     dplyr::relocate(row)
#   
#   c_start <- 1
#   ncol_per_page <- 15 # how many columns should go on each page
#   
#   comb <- data.frame(c_start = seq(from = 1, to = ncol(table_print1), by = ncol_per_page)+1,
#                      c_end = c(seq(from = ncol_per_page+1, to = ncol(table_print1), by = ncol_per_page), ncol(table_print1)))
#   
#   # if there are less than 3 columns in the last table, combine with table before because it looks messy 
#   if (abs(comb$c_start[nrow(comb)]-comb$c_end[nrow(comb)]) < 3) {
#     comb$c_end[nrow(comb)-1] <- comb$c_start[nrow(comb)]
#     comb<-comb[1:(nrow(comb)-1),]
#   }
#   
#   for (ii in 1:nrow(comb)) {
#     cnt_pre <- "A"
#     subobj <- TRUE
#     newobj <- ifelse(ii == 1, TRUE, FALSE)
#     table_raw <- table_raw00
#     
#     c_start <- comb$c_start[ii]
#     c_end <- comb$c_end[ii]
#     
#     nickname <- paste0(nickname0, 
#                        temp$SRVY[iii], 
#                        "_",  
#                        gsub(pattern = " ", replacement = "", perl = TRUE, 
#                             x = gsub(pattern = "F/V ", replacement = "", 
#                                      x = temp$vessel_name[iii], fixed = TRUE)), 
#                        "_", iii,"_", ii)
#     
#     table_print <- table_print1[,c(1, c_start:c_end)] %>% 
#       flextable::flextable(data = .) %>%
#       flextable::bold(x = ., j = "row") %>%
#       flextable::set_header_labels(., row = "") %>%
#       NMFSReports::theme_flextable_nmfstm(x = ., 
#                                           font0 = font0, 
#                                           row_lines = FALSE,
#                                           body_size = 7, 
#                                           header_size = 7, 
#                                           pad = 0, 
#                                           pgwidth = full_page_landscape_width)
#     
#     header <- paste0("Haul and catch data for successfully completed tows by ", 
#                      temp$vessel_ital[iii]," during the ", maxyr, " ", 
#                      temp$SRVY[iii], 
#                      " bottom trawl survey. In this table shows stations ", 
#                      names(table_print1)[c_start], " through ", 
#                      names(table_print1)[c_end], 
#                      " are shown. ")
#     
#     # save yo' stuff and do a lot of behind the scenes work
#     # alt: this does the same thing as calling "child = " in the chunk header
#     res <- knitr::knit_child(
#       text = knitr::knit_expand(
#         file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
#       quiet = TRUE
#     )
#     
#     list_tables[nickname][[1]]$res <- res
#   }
# }
```


# Appendix A and B

## tab_taxa_encountered_*_prep

```{r tab_app_taxa_encountered_*_prep}

tab_taxa_encountered_ <- function(temp, 
                                  nickname0, 
                                  cnt_pre, 
                                  maxyr, 
                                  catch_haul_cruises_maxyr, 
                                  spp_info) {
  
  list_tables0 <- list()
  
  cnt_tables <- 0
  nickname0 <- "tab_app_taxa_encountered_" 
  
  for (i in 1:nrow(temp)) {
    cnt_tables <- cnt_tables + 1
    newobj <- TRUE
    nickname <- paste0(nickname0, 
                       temp$SRVY[i], 
                       "_",  
                       temp$taxon[i])
    
    header <- paste0(stringr::str_to_sentence(temp$taxon[i]), 
                     " taxa encountered during the ", 
                     maxyr, " ", temp$SRVY_long[i], 
                     " bottom trawl survey listed alphabetically by ", 
                     ifelse(temp$taxon[i] == "fish", "family", "phylum"), ".")
    
    table_raw <- 
      dplyr::left_join(
        x = catch_haul_cruises_maxyr %>% 
          dplyr::filter(year == maxyr &
                          SRVY == temp$SRVY[i]) %>% 
          dplyr::select(stationid, start_latitude, start_longitude, bottom_depth, species_code), 
        y = spp_info %>% 
          dplyr::rename(taxon0 = ifelse(temp$taxon[i] == "fish", "family_taxon", "phylum_taxon")) %>%
          dplyr::select(species_name, common_name, taxon, species_code, taxon0), 
        by = "species_code") %>% 
      dplyr::filter(taxon == temp$taxon0[i]) %>% 
      dplyr::mutate(taxon = taxon0) %>% 
      dplyr::group_by(taxon, species_name, common_name ) %>% 
      dplyr::summarise(stations_n = n(),#count(stationid), 
                       depth_min = min(bottom_depth, na.rm = TRUE), 
                       depth_max = max(bottom_depth, na.rm = TRUE), 
                       depth_mean = mean(bottom_depth, na.rm = TRUE), 
                       lat_min = min(start_latitude, na.rm = TRUE), 
                       lat_max = max(start_latitude, na.rm = TRUE)) %>% 
      dplyr::ungroup() %>% 
      dplyr::arrange(species_name)  %>%
      dplyr::arrange(taxon)  %>%
      dplyr::mutate(stations_n = formatC(stations_n, big.mark=",", digits = 0, format = "f"))  %>%
      dplyr::mutate(across(c("lat_min", "lat_max", "depth_mean"), 
                           formatC, big.mark=",", digits = 1, format = "f"), 
                    taxon = ifelse(is.na(taxon), "Other", taxon), 
                    across(c("depth_min", "depth_max"), 
                           formatC, big.mark=",", digits = 0, format = "f"))
    
    table_print <- table_raw %>% 
      dplyr::mutate(species_name1 = species_name) %>%
      dplyr::mutate(spp = dplyr::case_when(
        grepl(pattern = "sp.", x = species_name1, fixed = TRUE) ~ "sp.", 
        grepl(pattern = "spp.", x = species_name1, fixed = TRUE) ~ "spp.", 
        grepl(pattern = "egg case", x = species_name1, fixed = TRUE) ~ "egg case", 
        grepl(pattern = "Naticidae egg", x = species_name1, fixed = TRUE) ~ "gastropod egg", 
        grepl(pattern = "gastropod egg", x = species_name1, fixed = TRUE) ~ "gastropod egg", 
        grepl(pattern = "hybrid", x = species_name1, fixed = TRUE) ~ "hybrid", 
        grepl(pattern = "Polychaete tubes", x = species_name1, fixed = TRUE) ~ "Polychaete tubes", 
        TRUE ~ "")) %>%
      dplyr::mutate(
        spacer = "",
        species_name = species_name1, 
        species_name1 = 
          gsub(pattern = " sp.", replacement = "", 
               x = species_name1, fixed = TRUE), 
        species_name1 =
          gsub(pattern = " spp.", replacement = "",
               x = species_name1, fixed = TRUE),
        species_name1 =
          gsub(pattern = " egg case", replacement = "",
               x = species_name1, fixed = TRUE),          
        species_name1 =
          gsub(pattern = "Naticidae egg", replacement = "",
               x = species_name1, fixed = TRUE),  
        species_name1 =
          gsub(pattern = "gastropod egg", replacement = "",
               x = species_name1, fixed = TRUE),          
        species_name1 =
          gsub(pattern = " hybrid", replacement = "",
               x = species_name1, fixed = TRUE),    
        species_name1 =
          gsub(pattern = "Polychaete tubes", replacement = "",
               x = species_name1, fixed = TRUE),      
        species_name2 = dplyr::case_when(
          !grepl(pattern = " ", x = species_name, fixed = TRUE) ~ species_name1), 
        species_name1 = dplyr::case_when(
          grepl(pattern = " ", x = species_name, fixed = TRUE) ~ species_name1))
    
    table_print <- table_print %>%
      flextable::flextable(data = ., 
                           col_keys = c("taxon" ,
                                        "species_name",
                                        "common_name", "stations_n", 
                                        "depth_min", "depth_max", "depth_mean", 
                                        "spacer", "lat_min", "lat_max"))  %>%
      flextable::merge_v(x = ., j = ~ taxon) %>%
      flextable::merge_h_range(x = ., i = ~ is.na(taxon), j1 = "species_name", j2 = "taxon", part = "body") %>%
      flextable::compose(j = "species_name",
                         value = as_paragraph(as_i(species_name1), species_name2, " ", spp)) %>% # https://stackoverflow.com/questions/57474647/italic-and-color-in-an-r-flextable
      # flextable::width(x = ., j = "taxon", width = 0.5, unit = "in") %>%
      flextable::set_header_labels(., 
                                   values = list(
                                     taxon = "", #ifelse(temp$taxon[i] == "fish", "Family", "Phylum"),
                                     species_name = "", #"Scientific name",
                                     common_name = "", #"Common name",
                                     stations_n = "", #"Number stations present", 
                                     depth_min = "Min.", 
                                     depth_max = "Max.", 
                                     depth_mean = "Avg.", 
                                     spacer = " ", 
                                     lat_max = "S", 
                                     lat_min = "N")) %>%
      flextable::add_header_row(x = .,
                                top = TRUE,
                                values = c(ifelse(temp$taxon[i] == "fish", "Family", "Phylum"),
                                           "Scientific name", "Common name", "Number stations present",
                                           "Bottom depth (m)", "", "Latitude range"),
                                colwidths = c(1,1,1,1,3,1,2)) %>%
      flextable::align(i = 1, align = "center", part = "header")  %>%  
      flextable::merge_at(x = ., j = c("taxon"), part = "header") %>%
      flextable::merge_at(x = ., j = c("species_name"), part = "header") %>%
      flextable::merge_at(x = ., j = c("common_name"), part = "header") %>%
      flextable::merge_at(x = ., j = c("spacer"), part = "header") %>%
      flextable::merge_at(x = ., j = c("stations_n"), part = "header") %>%
      NMFSReports::theme_flextable_nmfstm(x = ., 
                                          font0 = font0, 
                                          row_lines = TRUE, 
                                          # body_size = 8, 
                                          # header_size = 9, 
                                          pad = 0, 
                                          pgwidth = full_page_portrait_width) %>%
      # flextable::hline(x = ., part = "header") %>%
      flextable::width(x = ., width = .5, unit = "in") %>%
      # flextable::width(x = ., width = .75, j = "stations_n", unit = "in") %>%
      flextable::width(x = ., width = .1, j = c("spacer"), unit = "in") %>%
      flextable::width(x = ., width = 1, j = c("taxon", "common_name"), unit = "in") %>%
      flextable::width(x = ., width = 1.25, j = c("species_name"), unit = "in") %>%
      flextable::align(x = ., 
                       j = c("stations_n", "depth_min", "depth_max", "depth_mean", "lat_max", "lat_min"), 
                       align = "right", part = "all") %>%
      flextable::align(x = ., 
                       j = c("depth_max", "depth_min", "depth_mean", "lat_max", "lat_min"), 
                       align = "center", i = 1, part = "header") 
    
    # output from function
    list_tables0$temp <- list("table_print" = table_print, 
                              "table_raw" = table_raw, 
                              "header" = header, 
                              "nickname" = nickname, 
                              "newobj" = newobj)
    names(list_tables0)[names(list_tables0) == "temp"] <- nickname
  }
  
  return(list_tables0)
}

```


## Appendix A (EBS)

```{r tab_app_taxa_encountered_EBS}
temp <- tidyr::crossing(data.frame(taxon = c("invertebrate", "fish"), 
                                   taxon0 = c("invert", "fish")), 
                        haul_cruises_maxyr %>% 
                          dplyr::select(SRVY_long, SRVY) %>% 
                          dplyr::filter(SRVY == "EBS"))

cnt_pre0 <- cnt_pre0 + 1; cnt_pre1 <- LETTERS[cnt_pre0]
list_tables0 <- tab_taxa_encountered_(temp = temp, 
                                      cnt_pre = cnt_pre, 
                                      maxyr = maxyr, 
                                      catch_haul_cruises_maxyr = catch_haul_cruises_maxyr, 
                                      spp_info = spp_info) 
cnt_tables <- 0
for (i in 1:length(list_tables0)) {
  cnt_pre <- cnt_pre1
  a <- list_tables0[[i]]
  for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
  
  # save yo' stuff and do a lot of behind the scenes work
  # alt: this does the same thing as calling "child = " in the chunk header
  res <- knitr::knit_child(
    text = knitr::knit_expand(
      file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
    quiet = TRUE
  )
  
  list_tables[nickname][[1]]$res <- res
}

```


## Appendix B (NBS)

```{r tab_app_taxa_encountered_NBS}
if (SRVY == "NEBS") {
  temp <- tidyr::crossing(data.frame(taxon = c("invertebrate", "fish"), 
                                     taxon0 = c("invert", "fish")), 
                          haul_cruises_maxyr %>% 
                            dplyr::select(SRVY_long, SRVY) %>% 
                            dplyr::filter(SRVY == "NBS"))
  
  cnt_pre0 <- cnt_pre0 + 1; cnt_pre1 <- LETTERS[cnt_pre0]
  list_tables0 <- tab_taxa_encountered_(temp = temp, 
                                        cnt_pre = cnt_pre, 
                                        maxyr = maxyr, 
                                        catch_haul_cruises_maxyr = catch_haul_cruises_maxyr, 
                                        spp_info = spp_info) 
  
  cnt_tables <- 0
  for (i in 1:length(list_tables0)) {
    cnt_pre <- cnt_pre1
    a <- list_tables0[[i]]
    for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
    
    # save yo' stuff and do a lot of behind the scenes work
    # alt: this does the same thing as calling "child = " in the chunk header
    res <- knitr::knit_child(
      text = knitr::knit_expand(
        file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
      quiet = TRUE
    )
    
    list_tables[nickname][[1]]$res <- res
  }
  
}
```

# Appendix C and D

## tab_principal_fish_*_prep

```{r tab_app_principal_fish_*_prep}

tab_app_principal_fish_ <- function(temp, 
                                    cnt_pre, 
                                    maxyr, 
                                    haul_cruises_maxyr, 
                                    report_spp1,
                                    spp_info) {
  
  list_tables0 <- list()
  
  nickname0 <- "tab_app_principal_fish_" 
  cnt_tables <- 0
  
  temp0 <- report_spp1 %>% 
    dplyr::filter(taxon == "fish" & 
                    text_spp == TRUE &
                    file_name != "pacific_halibut") %>% 
    dplyr::select(file_name, species_code) %>% 
    dplyr::distinct() 
  
  for (i in 1:nrow(temp)) {
    cnt_tables <- cnt_tables + 1
    newobj <- TRUE
    print(temp$file_name[i])
    
    nickname <- paste0(nickname0, 
                       temp$SRVY[i], 
                       "_",  
                       temp$file_name[i])
    
    spp_code <- temp0$species_code[temp0$file_name == temp$file_name[i]]
    
    header <- paste0("Population estimates by sex and size for ",
                     temp$print_name[i]," (",temp$species_name[i],") from the ", 
                     maxyr, " ", temp$SRVY_long[i], 
                     " bottom trawl survey.")
    
    table_raw <- sizecomp_maxyr %>% 
      dplyr::filter(species_code %in% spp_code &
                      SRVY == temp$SRVY[i]) 
    
    if (nrow(table_raw) != 0) { 
      
      table_raw <- table_raw %>% 
        dplyr::select(length, pop, sex) %>%
        tidyr::pivot_wider(data = ., id_cols = length, 
                           names_from = sex, 
                           values_from = pop) %>%
        dplyr::mutate(total = males + females + unsexed, 
                      prop = total/sum(total, na.rm = TRUE), 
                      cumprop = cumsum(prop)) %>%
        dplyr::arrange(length)
      
      table_raw <- 
        dplyr::bind_rows(table_raw %>% 
                           dplyr::mutate(length = as.character(length)), 
                         table_raw %>%
                           dplyr::summarise(across(everything(), ~ sum(., is.na(.), 0))) %>% 
                           dplyr::mutate(length = "Total", 
                                         cumprop = 1))  %>%
        dplyr::mutate(across((ends_with("prop")), 
                             formatC, big.mark=",", digits = 4, format = "f")) %>%
        dplyr::mutate(across(where(is.numeric), 
                             formatC, big.mark=",", digits = 0, format = "f"))
      
      table_print <- table_raw %>%
        flextable::flextable(data = .) %>% 
        flextable::set_header_labels(.,
                                     length = "Length (cm)",
                                     males = "Males",
                                     females = "Females",
                                     unsexed = "Unsexed", 
                                     total = "Total", 
                                     prop = "Proportion", 
                                     cumprop = "Cumulative proportion") %>%
        flextable::align(i = 1, align = "center", part = "header")  %>%  
        flextable::bold(x = ., i = nrow(table_raw), part = "body") %>%
        NMFSReports::theme_flextable_nmfstm(x = ., 
                                            font0 = font0, 
                                            row_lines = FALSE, 
                                            # body_size = 8, 
                                            # header_size = 9, 
                                            pad = 0, 
                                            pgwidth = full_page_portrait_width) %>%
        flextable::width(x = ., width = .9, unit = "in") %>% 
        flextable::hline_bottom(x = ., border = fp_border(width = 2), part = "header")

      
      # # save yo' stuff and do a lot of behind the scenes work
      # # alt: this does the same thing as calling "child = " in the chunk header
      # res <- knitr::knit_child(
      #   text = knitr::knit_expand(
      #     file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
      #   quiet = TRUE
      # )
      # 
      # list_tables[nickname][[1]]$res <- res
      # }
      # output from function
      list_tables0$temp <- list("table_print" = table_print, 
                                "table_raw" = table_raw, 
                                "header" = header, 
                                "nickname" = nickname, 
                                "newobj" = newobj)
      names(list_tables0)[names(list_tables0) == "temp"] <- nickname
    }
  }
  return(list_tables0)
}
```


## Appendix C (or B if EBS only) (EBS)

```{r tab_app_principal_fish_EBS}
temp <- tidyr::crossing(haul_cruises_maxyr %>% 
                          dplyr::select(SRVY_long, SRVY) %>% 
                          dplyr::filter(SRVY == "EBS"), 
                        report_spp1 %>% 
                          dplyr::filter(taxon == "fish" & text_spp == TRUE) %>% 
                          dplyr::select(file_name, print_name, common_name1, species_name, species_name1) %>% 
                          dplyr::distinct())

cnt_pre0 <- cnt_pre0 + 1; cnt_pre1 <- LETTERS[cnt_pre0]
list_tables0 <- tab_app_principal_fish_(
  temp = temp, 
  cnt_pre = cnt_pre, 
  maxyr = maxyr, 
  haul_cruises_maxyr = haul_cruises_maxyr, 
  report_spp1 = report_spp1,
  spp_info = spp_info)

cnt_tables <- 0
for (i in 1:length(list_tables0)) {
  cnt_pre <- cnt_pre1
  a <- list_tables0[[i]]
  for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
  
  # save yo' stuff and do a lot of behind the scenes work
  # alt: this does the same thing as calling "child = " in the chunk header
  res <- knitr::knit_child(
    text = knitr::knit_expand(
      file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
    quiet = TRUE
  )
  
  list_tables[nickname][[1]]$res <- res
}

```

## Appendix D (NBS)

```{r tab_app_principal_fish_NBS}
if (SRVY == "NEBS") {
  temp <- tidyr::crossing(haul_cruises_maxyr %>% 
                            dplyr::select(SRVY_long, SRVY) %>% 
                            dplyr::filter(SRVY == "NBS"), 
                          report_spp1 %>% 
                            dplyr::filter(taxon == "fish" & text_spp == TRUE) %>% 
                            dplyr::select(file_name, print_name, common_name1, species_name, species_name1) %>% 
                            dplyr::distinct())
  
  cnt_pre0 <- cnt_pre0 + 1; cnt_pre1 <- LETTERS[cnt_pre0]
  list_tables0 <- tab_app_principal_fish_(
    temp = temp, 
    cnt_pre = cnt_pre, 
    maxyr = maxyr, 
    haul_cruises_maxyr = haul_cruises_maxyr, 
    report_spp1 = report_spp1,
    spp_info = spp_info)
  
  cnt_tables <- 0
  for (i in 1:length(list_tables0)) {
    cnt_pre <- cnt_pre1
    a <- list_tables0[[i]]
    for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
    
    # save yo' stuff and do a lot of behind the scenes work
    # alt: this does the same thing as calling "child = " in the chunk header
    res <- knitr::knit_child(
      text = knitr::knit_expand(
        file = system.file("rmd/_child_save_tab.Rmd", package = "NMFSReports")),
      quiet = TRUE
    )
    
    list_tables[nickname][[1]]$res <- res
  }
  
}
```

