---
output:
  officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

# Introduction

```{r fig-survey-points-nostrata}
# for community highlights

nickname <- "fig-survey-points-nostrata"

header <- paste0("Map of ",maxyr," ",SURVEY," survey sampling stations. The areas enclosed within the dark and light gray lines contain the eastern and northern Bering Sea shelf stations, respectively. The dots within each area indicate station locations. Filled dots are completed stations; unfilled dots represent planned stations that were not sampled in ", maxyr, ".")

height <- ifelse(srvy == "NEBS", full_page_portrait_height, 6)
width <- full_page_portrait_width

reg_dat0 <- reg_dat
# if (length(cruises_race$data_in_final == "N")>0) {
#   reg_dat0 <- report_types$NEBS$reg_dat
# }
reg_dat0$survey.grid <- reg_dat0$survey.grid|> 
  # dplyr::mutate(station = ifelse(!grepl(pattern = "-", x = station), "", station))|> 
  dplyr::left_join(station)|> 
  dplyr::mutate(in_maxyr = ifelse(is.na(in_maxyr), FALSE, in_maxyr))
# reg_dat0$place.labels <- reg_dat0$place.labels|> 
#   dplyr::filter(type %in% c("mainland", "peninsula"))

figure_print <- plot_survey_stations(reg_dat = reg_dat0, 
                                     survey_outline = TRUE, 
                                     stratum_grid = FALSE, 
                                     stratum_no = FALSE, 
                                     station_pts = "pts", 
                                     place_labels = TRUE, 
                                     bathymetry = TRUE)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-survey-points-strata}
# for community highlights
nickname <- "fig-survey-points-strata"

header <- paste0("Map of ",maxyr," ",SURVEY," survey sampling stations. The areas enclosed within the dark and light gray lines contain the eastern and northern Bering Sea stations, respectively. The dots within each area indicate station locations. Filled dots are completed stations; unfilled dots represent planned stations that were not sampled in ", maxyr, ".")

height <- ifelse(srvy == "NEBS", full_page_portrait_height, 6)
width <- full_page_portrait_width

reg_dat0 <- reg_dat
# if (length(cruises_race$data_in_final == "N")>0) {
#   reg_dat0 <- report_types$NEBS$reg_dat
# }
reg_dat0$survey.grid <- reg_dat0$survey.grid|> 
  # dplyr::mutate(station = ifelse(!grepl(pattern = "-", x = station), "", station))|> 
  dplyr::left_join(station)|> 
  dplyr::mutate(in_maxyr = ifelse(is.na(in_maxyr), FALSE, in_maxyr))
# reg_dat0$place.labels <- reg_dat0$place.labels|> 
#   dplyr::filter(type %in% c("mainland", "peninsula"))

figure_print <- plot_survey_stations(reg_dat = reg_dat0, 
                                     survey_outline = ifelse(plural_surveys == "s", TRUE, FALSE), 
                                     stratum_grid = TRUE, 
                                     stratum_no = TRUE, 
                                     station_pts = "pts", 
                                     place_labels = TRUE, 
                                     bathymetry = FALSE)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-survey-sample-stations}
nickname <- "fig-survey-sample-stations"

vessels0 <- vessels 
if (sum(vessels0$vess_shape == "X")>0) {
  vessels0 <- vessels0|> 
    dplyr::mutate(vessel_ital = ifelse(vess_shape == "X", "stations that were not surveyed", vessel_ital))
}
header <- paste0("Stratification scheme used for data analysis of the ", maxyr," ",
                 text_list(haul_cruises_maxyr$srvy_long),
                 " shelf survey", plural_surveys, 
                 ". The map also depicts the stations sampled by the ",
                 text_list(paste0(vessels0$vessel_ital, " (",
                                  vessels0$vess_shape, ")")), 
                 ifelse(crab_resample == TRUE, " and where Bristol Bay crab resampling was conducted", ""), ". ")

height <- ifelse(srvy == "NEBS", full_page_portrait_height, 6) 
width <- full_page_portrait_width

reg_dat0 <- reg_dat
# if (length(cruises_race$data_in_final == "N")>0) {
#   reg_dat0 <- report_types$NEBS$reg_dat
# }

reg_dat0$survey.grid <- reg_dat0$survey.grid |> 
  dplyr::left_join(haul_maxyr |> 
                     dplyr::select(survey_definition_id, year, stratum, vessel_id, longitude_dd_start, longitude_dd_end, station, srvy)) |> # 
  dplyr::left_join(vessels) |>
  dplyr::ungroup() 

if (crab_resample){
  reg_dat0$survey.grid <- dplyr::left_join(
    x = reg_dat0$survey.grid, 
    y = haul_maxyr_crabretow|> 
      dplyr::mutate(study = "crab_resample", 
                    study_col = nmfspalette::nmfs_cols("medgray"),
                    study_long = "Red King Crab\nResample")|> 
      dplyr::select(station, study, study_col, study_long)|>
      dplyr::rename(station = station)|> 
      unique(), 
    by = ("station")) 
}

figure_print <- plot_survey_stations(
  reg_dat = reg_dat0, 
  survey_outline = ifelse(plural_surveys == "s", TRUE, FALSE), 
  stratum_grid = TRUE, 
  stratum_no = TRUE, 
  place_labels = TRUE, 
  bathymetry = FALSE, 
  station_pts = "vess", 
  study = crab_resample) # defined in data.r

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-survey-station-simple}
nickname <- "fig-survey-stations-simple"

vessels0 <- vessels 
if (sum(vessels0$vess_shape == "X")>0) {
  vessels0 <- vessels0|> 
    dplyr::mutate(vessel_ital = ifelse(vess_shape == "X", "stations that were not surveyed", vessel_ital))
}
header <- paste0("Stratification scheme used for data analysis of the ", maxyr," ",
                 text_list(haul_cruises_maxyr$srvy_long),
                 " shelf survey", plural_surveys, 
                 ". The map also depicts the stations sampled by the ",
                 text_list(paste0(vessels0$vessel_ital, " (",
                                  vessels0$vess_shape, ")")), 
                 ifelse(crab_resample == TRUE, " and where Bristol Bay crab resampling was conducted", ""), ". ")

height <- ifelse(srvy == "NEBS", full_page_portrait_height, 6) 
width <- full_page_portrait_width

reg_dat0 <- reg_dat

reg_dat0$survey.grid <- reg_dat0$survey.grid|> 
  dplyr::mutate(station = station)|> 
  dplyr::left_join(y = haul_maxyr)|> 
  dplyr::left_join(y = vessels)|>
  dplyr::ungroup() 

figure_print <- plot_survey_stations(
  reg_dat = reg_dat0, 
  survey_outline = ifelse(plural_surveys == "s", TRUE, FALSE), 
  stratum_grid = FALSE, 
  stratum_no = FALSE, 
  place_labels = TRUE, 
  bathymetry = TRUE, 
  station_pts = "vess") # defined in data.r

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-survey-sample-stations-1530, eval = FALSE}
# eval = tow1530
nickname <- "fig-survey-sample-stations-1530"
header <- ""

width <- full_page_portrait_width

reg_dat0 <- reg_dat
if (sum(cruises_race$data_in_final == "N")>0) {
  reg_dat0 <- report_types$NEBS$reg_dat
}
reg_dat0$survey.grid <-
  dplyr::left_join(x = reg_dat0$survey.grid,
                   y = dplyr::left_join(x = haul_maxyr,
                                        y = vessels)|>
                     dplyr::select(station, vessel_name, vess_shape))

reg_dat0$survey.grid <- dplyr::left_join(
  x = reg_dat0$survey.grid, 
  y = haul_maxyr_crabretow|> 
    dplyr::mutate(study = "15_30_minute_tows", 
                  study_col = nmfspalette::nmfs_cols("medgray"),
                  study_long = "15/30 minute tows")|> 
    dplyr::select(station, study, study_col, study_long)|>
    dplyr::rename(station = station)|> 
    unique(), 
  by = ("station")) 

figure_print <- plot_survey_stations(
  reg_dat = reg_dat0, 
  stratum_grid = FALSE, 
  stratum_no = TRUE, 
  bathymetry = FALSE, 
  station_pts = "vess", 
  place_labels = TRUE, 
  study = tow1530) # defined in data.r

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-survey-grid}
nickname <- "fig-survey-grid"

header <- paste0("Sampling grid and station identifiers for the ",maxyr," ",
                 text_list(haul_cruises_maxyr$srvy_long),
                 " shelf survey", plural_surveys, 
                 ". ") # , ifelse(srvy == "NBS", "", "Corner stations (denoted by circles) are not labeled for legibility. ")

height <- ifelse(srvy == "NEBS", full_page_portrait_height, 6)
width <- full_page_portrait_width

reg_dat0 <- reg_dat
# if (length(cruises_race$data_in_final == "N")>0) {
#   reg_dat0 <- report_types$NEBS$reg_dat
# }
reg_dat0$survey.grid <- reg_dat0$survey.grid|> 
  dplyr::mutate(station = ifelse(!grepl(pattern = "-", x = station), "", station))
reg_dat0$place.labels <- reg_dat0$place.labels|> 
  dplyr::filter(type %in% c("mainland", "peninsula"))

figure_print <- plot_survey_stations(reg_dat = reg_dat0, 
                                     stratum_grid = FALSE, 
                                     stratum_no = FALSE, 
                                     station_pts = "names", 
                                     bathymetry = FALSE,
                                     place_labels = TRUE)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

# Methods

```{r fig-vessels}
header <- paste0("Fishing vessels ",
                 text_list(paste0(vessels$vessel_ital[vessels$vessel_ital != "Not Surveyed"], 
                                  " (", c("left", "right"), ")")),
                 " contracted to conduct the ",maxyr," ",
                 SURVEY,
                 " survey.")

nickname <- "fig-vessels"

height <- 2.5
width <- full_page_portrait_width

figure_print <- cowplot::plot_grid(
  cowplot::ggdraw() +
    cowplot::draw_image(readPNG(paste0(dir_img, vessels$img[1])), 
                        scale = 0.9 ), 
  cowplot::ggdraw() +
    cowplot::draw_image(readPNG(paste0(dir_img, vessels$img[2])), 
                        scale = 0.9 ),  
  ncol = 2, rel_heights = c(0.1, 1))

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-trawl-gear}
header <- paste0("Schematic diagram of the 83-112 eastern otter trawl gear used during the ", 
                 maxyr ," ", SURVEY ," survey", 
                 ifelse(length(srvy1)>1, "s", ""), ".")
footnote<- NA
nickname <- "fig-trawl-gear-diagram"
alttext <- paste0(header)
height = 8
width <- full_page_portrait_width

# Select data and make plot
figure_print <- 
  cowplot::ggdraw() +
  cowplot::draw_image(readPNG(paste0(dir_img, "EASTERN83-112.png")) )

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-trawl-gear-alt}
# for community highlights
header <- paste0("Diagram of the 83-112 Eastern trawl net.")
nickname <- "fig-trawl-gear-alt"
height <- 4
width <- 6
bg <- 'transparent'

# Select data and make plot
figure_print <- 
  cowplot::ggdraw() +
  cowplot::draw_image(readPNG(paste0(dir_img, "bottom_trawl_net.png")), scale = 0.9 )

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-stratum-areas}
header <- paste0("Stratum areas and sampling densities used during the ", maxyr,
                 " ", SURVEY ," survey", 
                 ifelse(length(srvy1)>1, "s", ""),". Stratum area calculations were updated in ", 
                 strat_yr , ". ")

nickname <- "tab-stratum-areas" 

temp <- stratum|> 
  dplyr::mutate(depth_min_m = ifelse(depth_min_m  == 1, 0, depth_min_m ), 
                area_name = paste0(gsub(replacement = "Shelf", x = area_name, pattern = "Domain") , 
                                   "\n(",depth_min_m, "-", depth_max_m, " m)"))|> 
  dplyr::select(area_km2, stations_avail, stations_completed, stratum, area_name, srvy)

if (length(unique(station$srvy))>1) {
  totals_sub <- temp|>
    dplyr::group_by(srvy)|>
    dplyr::summarise(
      area_km2 = sum(area_km2, na.rm = TRUE),
      stations_completed = sum(stations_completed, na.rm = TRUE), 
      stations_avail = sum(stations_avail, na.rm = TRUE))|>
    dplyr::mutate(area_name = "Total") 
}

totals <- temp|> 
  dplyr::summarise(
    area_km2 = sum(area_km2, na.rm = TRUE), 
    stations_completed = sum(stations_completed, na.rm = TRUE), 
    stations_avail = sum(stations_avail, na.rm = TRUE))|> 
  dplyr::mutate(area_name = "Total", 
                srvy = paste0("Z", text_list(srvy1))) 

table_raw <- dplyr::bind_rows(
  temp, 
  if(exists("totals_sub")){totals_sub}, 
  totals)|> 
  dplyr::mutate(
    density = round(area_km2/stations_completed, 0), 
    area_km2 = round(area_km2, digits = 0))|>
  dplyr::arrange(srvy, area_name, stratum)|> 
  dplyr::relocate(srvy, area_name, stratum, area_km2, 
                  stations_avail, stations_completed, density)|> 
  dplyr::mutate(srvy = gsub(replacement = "", x = srvy, pattern = "Z"))|> 
  dplyr::left_join(
    y = data.frame(srvy = c(srvy1, "EBS and NBS"), 
                   srvy_long = c(stringr::str_to_title(srvy11), "Eastern and northern Bering Sea combined")))

table_print <- table_raw|>
  dplyr::select(-srvy)|> 
  flextable::as_grouped_data(groups = c("srvy_long"), columns = NULL) |>
  flextable::as_flextable(hide_grouplabel = TRUE)|>
  flextable::compose(i = 1, j = "area_km2", part = "header",
                     value = as_paragraph("Representative\narea (km", as_sup("2"), ")"))|>
  flextable::compose(i = 1, j = "density", part = "header",
                     value = as_paragraph("Sampling density\n(km", as_sup("2"), "/stations successfully sampled)"))|>  
  flextable::set_header_labels(area_name = "Stratum",
                               stratum = "Stratum",
                               stations_avail = "Stations\nin stratum",
                               stations_completed = "Stations\nsuccessfully sampled")|> 
  flextable::merge_h(i = 1, part = "header")|> 
  flextable::merge_v(j = "area_name")|>
  flextable::merge_h_range(i = ~ stratum == "", 
                           j1 = "area_name", 
                           j2 = "stratum", 
                           part = "body")|>
  flextable::valign(valign = "top")|>
  theme_flextable_nmfstm(row_lines = FALSE, 
                         pgwidth = full_page_portrait_width) |>
  flextable::width(width = c(1, .5, 1.1, 1.1, 1.1, 1.7))|> 
  flextable::align(j = c("stratum", "area_km2", "stations_completed", "density"), 
                   align = "right", part = "all") |> 
  flextable::bold(j = 1, i = ~ !is.na(srvy_long) )|>
  flextable::padding(j = 1, i = ~ is.na(srvy_long),
                     padding.left = 7)  |>
  flextable::hline(i = ~ !is.na(area_name), #j = srvy, #border = fp_border(width = 3), 
                   part = "body") |>
  flextable::hline(i = ~ (area_name == "Total"), #j = srvy, #border = fp_border(width = 3), 
                   part = "body",
                   border = fp_border(width = 2)) 

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-oto-collection-scheme-[srvy]}
nickname <- paste0("tab-oto-collection-scheme") 

table_raw <- readxl::read_excel(path = paste0(dir_out_rawdata, "/collection-scheme.xlsx"), 
                                sheet = "Sheet1", 
                                skip = 1)|> 
  dplyr::filter(srvy %in% srvy1 &
                  year == maxyr & 
                  !is.na(oto_target))|> 
  dplyr::mutate(
    oto_target = oto_target1, 
    # oto_target = paste0(oto_target, ifelse(oto_rules != 1, paste0("; collect when \u2265", oto_rules, " individuals caught in each haul"), "")), 
    print_name = paste0(toupper(substr(print_name, start = 1, stop = 1)), substr(print_name, start = 2, stop = nchar(print_name))))|> 
  dplyr::left_join(
    y = report_spp1|> 
      dplyr::select(print_name, order)|> 
      dplyr::distinct(), 
    by = "print_name")|> 
  dplyr::distinct()|>
  dplyr::arrange(srvy, print_name, order)|> 
  dplyr::select(srvy, print_name, oto_target, oto_samp_type)|> 
  dplyr::left_join(
    y = data.frame(srvy = srvy1, 
                   srvy_long = stringr::str_to_title(srvy11)))

header <- paste0("Otolith collection types and target counts during the ", 
                 maxyr, " ", 
                 text_list(haul_cruises_maxyr$srvy_long),
                 " shelf survey", ifelse(length(srvy1)>1, "s", ""),".")

table_print <- table_raw |> 
  dplyr::select(-srvy) 

# if (length(srvy1) > 1) {
  table_print <- table_print |> 
    flextable::as_grouped_data(
      groups = c("srvy_long", "oto_samp_type"), 
                               columns = NULL) 
# } else {
#   table_print <- table_print|> 
#     dplyr::select(-srvy_long)|> 
#     flextable::as_grouped_data(groups = c("oto_samp_type"), 
#                                columns = NULL) 
# }
table_print <- table_print |> 
  flextable::as_flextable(hide_grouplabel = TRUE) |>
    flextable::bold(j = 1, 
                    i = ~ !is.na(srvy_long) ) |> 
  flextable::bold(j = 1, i = ~ !is.na(oto_samp_type) )|> 
  flextable::set_header_labels(print_name = "Common name", 
                               oto_target = "Target collection number per haul")|>
  theme_flextable_nmfstm(row_lines = TRUE, 
                         pgwidth = full_page_portrait_width) |>
  flextable::padding(j = 1, 
                     i = ~ !is.na(oto_samp_type),
                     padding.left = 7)|>
  flextable::padding(j = 1, 
                     i = ~ !(is.na(print_name)),
                     padding.left = 10)|>
  flextable::width(j = "oto_target", width = 4.5, unit = "in")|>
  flextable::width(j = c("print_name"), width = 2)|> 
  flextable::hline(i = ~ !is.na(oto_samp_type), 
                   border = fp_border(color = "white"), 
                   part = "body") 

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-stomach-collection-scheme}
nickname <- paste0("tab-stomach-collection-scheme") 

header <- paste0("Stomach collection target size category bins (cm) used to collect each fish species during the ", 
                 maxyr, " ", 
                 text_list(paste0( 
                   haul_cruises_maxyr$srvy_long)),
                 " shelf survey.")

table_raw <- readxl::read_excel(path = paste0(dir_out_rawdata, "/collection-scheme.xlsx"), 
                                sheet = "Sheet1", 
                                skip = 1) |> 
  dplyr::filter(srvy %in% srvy1) |> 
  dplyr::filter(year == maxyr & !is.na(stomach_target)) |> 
  dplyr::left_join(
    y = report_spp1 |> 
      dplyr::select(print_name, order) |> 
      dplyr::distinct(), 
    by = "print_name") |> 
  dplyr::distinct() |>
  dplyr::arrange(srvy, print_name, order) |> 
  dplyr::select(srvy, print_name, stomach_target) |>
  # dplyr::mutate(stomach_target = as.character(round(as.numeric(stomach_target), digits = 0)))  |> 
  dplyr::mutate(#stomach_target = paste0(stomach_target, " cm"), 
    print_name = paste0(toupper(substr(print_name, start = 1, stop = 1)), substr(print_name, start = 2, stop = nchar(print_name)))) |>
  dplyr::left_join(
    y = data.frame(srvy = srvy1, 
                   srvy_long = stringr::str_to_title(srvy11))) |>
  dplyr::ungroup() |> 
  tidyr::pivot_wider(
                     id_cols = c("print_name"), 
                     names_from = "srvy_long", 
                     values_from = "stomach_target")

table_raw[is.na(table_raw)] <- "-"
thin_b <- officer::fp_border(width = 0.5, color = "grey10")

if (length(srvy1)==1) {
  names(table_raw)[2] <- "Target collection size categories per haul"
}

table_print <- table_raw |> 
  flextable::flextable() |> 
  flextable::set_header_labels(print_name = "Common name", 
                               stomach_target = "Target collection number per survey")  |>
  flextable::merge_at(j = "print_name", part = "header") |> 
  theme_flextable_nmfstm(row_lines = TRUE, 
                         pgwidth = full_page_portrait_width)  |>
  flextable::width(width = c((full_page_portrait_width - 4.5), 
                             rep_len(length.out = length(srvy1), (4.5/length(srvy1))))) |> 
  flextable::hline(border = thin_b, part = "header") |> 
  flextable::align(i = 1, align = "left", part = "header") 

if (length(srvy1)>1) {
  table_print <- table_print |>
    flextable::add_header_row(
      top = TRUE,
      values = c("",
                 "Target collection size categories per haul"),
      colwidths = c(1,length(srvy1)))
}

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-special-projects}
nickname <- "tab-special-projects" 
places <- readxl::read_excel(path = paste0(dir_out_rawdata, "/special-projects.xlsx"), 
                             sheet = "affiliations", 
                             skip = 1)

table_raw <- readxl::read_excel(path = paste0(dir_out_rawdata, "/special-projects.xlsx"), 
                                sheet = "projects", 
                                skip = 1)  |> 
  dplyr::filter(!is.na(`Project title`) & 
                  year == maxyr) 

if (length(srvy1)==1) {
  table_raw <- table_raw |> 
    dplyr::filter(grepl(x = srvy, pattern = srvy1)) 
  table_raw$srvy <- paste0(srvy1)
}

table_raw <- table_raw |> 
  dplyr::select(srvy, `Project title`, `Principal investigator`, Agency) |> 
  dplyr::left_join(
    y = data.frame(srvy = c(srvy1, "EBS & NBS"), 
                   srvy_long = c(stringr::str_to_title(srvy11), 
                                 "Eastern and northern Bering Sea"))) |> # " Combined"
  dplyr::mutate(
    srvy = gsub(pattern = "&", x = srvy, replacement = "and"), 
    srvy = factor(x = srvy, 
                  levels = c("EBS and NBS", "EBS", "NBS"), 
                  labels = c("EBS and NBS", "EBS", "NBS"), 
                  ordered = TRUE), 
    srvy_long = factor(x = srvy_long, 
                       levels = c("Eastern and northern Bering Sea", # " Combined"
                                  "Eastern Bering Sea", "Northern Bering Sea"), 
                       labels = c("Eastern and northern Bering Sea", # " Combined"
                                  "Eastern Bering Sea", "Northern Bering Sea"), 
                       ordered = TRUE)) |>
  dplyr::arrange(srvy, Agency, `Principal investigator`, `Project title`)

# howmanyitals <- max(stringr::str_count(table_raw$`Project title`, "\\*")/2)
# if (howmanyitals>0) {
#   temp <- tidyr::crossing(
#        temp2 = rep_len(length.out = howmanyitals, x = 1:howmanyitals), 
#        temp1 = c("italno", "ital")) |> 
#     data.frame() |>
#     dplyr::mutate(cols = paste0(temp1, temp2)) 
#   
# table_raw <- table_raw |> 
#   tidyr::separate(col = `Project title`, sep = "//*", 
#                   into = temp$cols, 
#                   remove = FALSE)
# }

header <- paste0("Non-core scientific collections and research projects undertaken during the ",
                 maxyr, " ", 
                 text_list(haul_cruises_maxyr$srvy_long), 
                 " shelf survey, sorted by principal investigator and agency.")

# find places
temp0 <- unlist(strsplit(x = table_raw$Agency, split = " & ", fixed = TRUE))
temp0 <- unlist(strsplit(x = temp0, split = ", ", fixed = TRUE))
temp1 <- places[places$Agency %in% unique(temp0), ]

footnote0 <- paste(paste(temp1$Agency, " - ", temp1$agency_long, sep = ""), collapse = "; ")

# eval(parse(text=paste0('flextable::compose(
#     j = "dummy", part = "body",', paste0(''))))


# table_print <- table_raw |>
#   dplyr::select(-srvy) |> 
#   flextable::as_grouped_data(groups = c("srvy_long"), columns = NULL) |> 
#   flextable::as_flextable(hide_grouplabel = TRUE)  |>
# flextable::compose(
#   j = "dummy", 
#   part = "body",
#   value = as_paragraph(
#     as_chunk(ifelse(is.na(italno1), "", italno1)),
#              props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)), 
#     as_chunk(ifelse(is.na(ital1), "", ital1),
#              props = fp_text_default(italic = TRUE, font.size = font_size0, font.family = font0))) |> 

if (plural_surveys == "") {
  table_print <- table_raw |>
    dplyr::select(-srvy, -dplyr::starts_with("ital"), -srvy_long) |> 
    flextable::flextable()
} else {
  table_print <- table_raw |>
    dplyr::select(-srvy, -dplyr::starts_with("ital")) |>
    flextable::as_grouped_data(groups = c("srvy_long"), columns = NULL) |>
    flextable::as_flextable(hide_grouplabel = TRUE) |>
    flextable::bold(j = 1, i = ~ !is.na(srvy_long) ) |> 
    flextable::padding(j = 1, i = ~ is.na(srvy_long),
                       padding.left = 7) |> 
    flextable::hline(i = ~ !is.na(srvy_long), 
                     border = fp_border(color = "white"), 
                     part = "body")
}

table_print <- table_print |>
  flextable::footnote(value = as_paragraph(footnote0), 
                      ref_symbols = "1",
                      part = "header", 
                      j = "Agency", 
                      i = 1)  |>
  theme_flextable_nmfstm(row_lines = TRUE, 
                         pgwidth = full_page_portrait_width) |> 
  flextable::width(width = c(full_page_portrait_width-2.5, 1.5, 1), unit = "in")

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-special-projects-pres, eval = FALSE}
nickname <- "tab-special-projects-pres" 

header <- paste0("Special projects and collections undertaken during the ",
                 maxyr, " ", 
                 text_list(haul_cruises_maxyr$srvy_long), 
                 " shelf survey, sorted by principal investigator and agency.")

table_raw <- readxl::read_excel(path = paste0(dir_out_rawdata, "/special-projects.xlsx"), 
                                sheet = "projects", 
                                skip = 1)  |> 
  dplyr::filter(!is.na(`Project title`) & 
                  year == maxyr) |> 
  dplyr::select(srvy, #`Project Title`, `Principal investigator`, Agency, 
                nickname, group) |> 
  dplyr::mutate(nickname = 
                  if_else((tolower(srvy) == "EBS & NBS" | is.na(srvy)), 
                          paste0(nickname), 
                          paste0(srvy, " ", nickname))) |> 
  dplyr::select(group, nickname) |>
  dplyr::arrange(nickname) |>
  dplyr::ungroup() |>
  dplyr::arrange(group, #srvy, 
                 nickname) |> 
  dplyr::rename("Special Projects" = nickname)

table_print <- table_raw |> 
  flextable::as_grouped_data(groups = c("group"), columns = NULL) |> 
  flextable::as_flextable(hide_grouplabel = TRUE) |> 
  flextable::bold(j = 1, 
                  i = ~ !is.na(group) ) |>
  theme_flextable_nmfstm(row_lines = FALSE)  |>
  flextable::padding(j = 1, 
                     i = ~ is.na(group), 
                     padding.left = 20)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

# Results

```{r tab-length-samples-pres, eval = FALSE}

nickname <- paste0("tab-length-samples-pres") 
header <- paste0("Lengths collected during the ", maxyr, " ",
                 SURVEY, 
                 " survey.")

table_raw <- lengths |> 
  dplyr::left_join(
    spp_info |> 
      dplyr::select(species_code, common_name), 
    by = "species_code") |>
  dplyr::filter(year %in% c(maxyr) &
                  !(species_code %in% c(68560, 68580, 68590, 69322, 
                                        69323, 69400, 69310, 68577, 68781) ))  |>  # no crab!
  dplyr::group_by(srvy, common_name) |>  
  dplyr::summarise(frequency = sum(frequency, na.rm = TRUE)) |>
  tidyr::pivot_wider(
                     id_cols = c("common_name"), 
                     names_from = c("srvy"),
                     values_from = "frequency") |> 
  dplyr::ungroup() |> 
  dplyr::arrange(common_name) |>
  dplyr::mutate(NBS = ifelse(is.na(NBS), 0, NBS),
                EBS = ifelse(is.na(EBS), 0, EBS),
                keep = ifelse((EBS>=1000 | NBS >=1000), T, F) )

table_raw0 <- table_raw |>
  dplyr::filter(keep == F) |>
  dplyr::select(-keep) |>
  dplyr::summarise(EBS = sum(EBS != 0, is.na = TRUE),
                   NBS = sum(NBS != 0, is.na = TRUE))

table_print0 <- dplyr::bind_rows(
    table_raw |>
      dplyr::filter(keep == TRUE) |>
      dplyr::select(-keep) |>
      dplyr::mutate(common_name = stringr::str_to_sentence(common_name)) |> 
      dplyr::arrange(common_name),
    table_raw |>
      dplyr::filter(keep == FALSE) |>
      dplyr::select(-keep) |>
      dplyr::summarise(EBS = sum(EBS, na.rm = TRUE),
                       NBS = sum(NBS, na.rm = TRUE)) |>
      dplyr::mutate(common_name = paste0("Other taxa (EBS: ", table_raw0$EBS, ", NBS: ", table_raw0$NBS, ")")),
    table_raw |>    # total
      dplyr::mutate(common_name = "TOTAL") |>
      dplyr::group_by(common_name) |> 
      dplyr::summarise(dplyr::across(dplyr::where(is.numeric), sum, na.rm = TRUE)) |>
      dplyr::ungroup())  |> 
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric), xunits, val_under_x_words = -1), 
                common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name))))

table_print0[table_print0==0]<- "-"

# h_r1 <- c("Common name", sapply(strsplit(x = names(table_print0)[-1], split = "_"), "[[", 1))
# h_r2 <- c("Common name", sapply(strsplit(x = names(table_print0)[-1], split = "_"), "[[", 2))
std_b <- officer::fp_border(width = 2, color = "grey10")

table_print <- table_print0 |> 
  flextable::flextable() |>
  flextable::set_header_labels(
    values = c("Common name", names(table_print0)[-1]) ) |>
  theme_flextable_nmfstm() |>
  flextable::merge_h(i = 1, part = "header") |> 
  flextable::merge_v(j = "common_name", part = "header") |>
  flextable::valign(valign = "top") |>
  flextable::bold(i = ~(common_name == "TOTAL") ) |>
  flextable::align(i = 1, j = 2:ncol(table_print0), align = "center", part = "header") |> 
  flextable::hline(border = std_b, part = "header")  

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-age-samples-pres}
nickname <- paste0("tab-age-samples-pres") 
header <- paste0("Otoliths collected during the ", maxyr, " ", 
                 text_list(haul_cruises_maxyr$srvy_long), 
                 " shelf survey.")

a <- report_spp1 |> 
  dplyr::filter(!is.na(order)) |> 
  dplyr::select(print_name, species_code, species_name1, plot_sizecomp, order) |> 
  dplyr::distinct() |> 
  dplyr::mutate(include  = ifelse(is.na(plot_sizecomp ) | isFALSE(plot_sizecomp ), 
                                  FALSE, TRUE)) |> 
  dplyr::filter(include == TRUE) 

table_raw <- specimen |> 
  dplyr::filter(year %in% c(maxyr, compareyr) &
                  specimen_subsample_method %in% c(19, 6, 1) & 
                  specimen_sample_type == 1) |>
  dplyr::select(srvy, specimen_subsample_method, species_code, year) |> 
  dplyr::mutate(specimen_subsample_method = dplyr::case_when(
    specimen_subsample_method %in% c(1, 19) ~ "random-by-haul",
    specimen_subsample_method == 6 ~ "length/region-stratified (cm/sex/southeast and northwest regions)" )) |>
  dplyr::left_join(
    y = spp_info |> 
      dplyr::select(species_code, common_name), 
    by = "species_code") |> 
  dplyr::left_join(
    y = a |>
      dplyr::select(order, species_code) |>
      distinct(),
    by = "species_code") |>
  dplyr::group_by(common_name, srvy, order, year, specimen_subsample_method) |> 
  dplyr::summarise(ages = n()) |> 
  dplyr::ungroup() |> 
  tidyr::pivot_wider(id_cols = c("common_name", "order", "specimen_subsample_method"), 
                     values_from = "ages", 
                     names_from = c("srvy", "year")) |>
  dplyr::arrange(order) |>
  dplyr::select(-order) |>
  dplyr::arrange(specimen_subsample_method) |> 
  dplyr::relocate(specimen_subsample_method) |> 
  dplyr::ungroup() |> 
  dplyr::mutate(common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name))))

table_print0 <- dplyr::bind_rows(
  table_raw, 
  # summed total
  table_raw |> 
    dplyr::mutate(common_name = "TOTAL") |> 
    dplyr::group_by(specimen_subsample_method , common_name) |> 
    dplyr::summarise(dplyr::across(dplyr::where(is.numeric), sum, na.rm = TRUE))) |>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric), xunits, val_under_x_words = -1))
table_print0[is.na(table_print0)] <- "-"

h_r1 <- c("Common name", sapply(strsplit(x = names(table_print0)[-(1:2)], split = "_"), "[[", 1))
h_r2 <- c("Common name", sapply(strsplit(x = names(table_print0)[-(1:2)], split = "_"), "[[", 2))
std_b <- officer::fp_border(width = 2, color = "grey10")

table_print <- table_print0 |> 
  flextable::as_grouped_data(groups = c("specimen_subsample_method")) |> 
  flextable::as_flextable(hide_grouplabel = TRUE) |> 
  flextable::bold(j = 1, i = ~ !is.na(specimen_subsample_method) ) |>
  flextable::bold(i = ~(common_name == "TOTAL") ) |>
  flextable::add_header(
    values = eval(parse(text = paste0("list(",
                                      text_list(paste0(names(table_print0)[-1], " = '", h_r1, "'"),
                                                sep_last = ", ", sep_last2 = ", "), ") " ) ) ),
    top = TRUE) |>
  flextable::set_header_labels(
                               values = eval(parse(text = paste0("list(",
                                                                 text_list(paste0(names(table_print0)[-1], " = '", h_r2, "'"),
                                                                           sep_last = ", ", sep_last2 = ", "), ") " ) ) )
  ) |> 
  theme_flextable_nmfstm() |>
  flextable::merge_h(i = 1, part = "header") |> 
  flextable::merge_v(j = "common_name", part = "header") |>
  flextable::valign(valign = "top") |>
  flextable::align(i = 1, j = 2:(ncol(table_print0)-1), align = "center", part = "header") |> 
  flextable::padding(j = 1, 
                     i = ~ is.na(specimen_subsample_method), 
                     padding.left = 20) |>   
  flextable::hline(border = std_b, part = "header") 

if (srvy == "NEBS") {
  table_print <- table_print |> 
    flextable::vline(j = paste0("EBS_", compareyr))
}

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-mean-temperature-prep}
# code orig from sean rohan's coldpool package! Jan 23 2021 
nickname <- "fig-mean-temperature"
header <- paste0("Average summer surface and bottom (points and solid lines), and time series average surface and bottom (dashed lines) temperatures (°C) on the eastern Bering Sea shelf, based on data collected during the eastern Bering Sea shelf survey from 1982–",
                 maxyr, " (left), and northern Bering Sea shelf based on data collected during standardized summer surveys (right). ")

height <- 3.25
width <- full_page_portrait_width # 6.5

plot_mean_temperatures <- function(maxyr, srvy){
  
  # EBS
  sebs_temperatures <- coldpool::cold_pool_index |>
    dplyr::filter(YEAR <= maxyr) |>
    dplyr::select(YEAR, MEAN_GEAR_TEMPERATURE, MEAN_SURFACE_TEMPERATURE) |>
    dplyr::rename(Bottom = MEAN_GEAR_TEMPERATURE, 
                  Surface = MEAN_SURFACE_TEMPERATURE) |>
    dplyr::mutate(region = "Eastern Bering Sea") |> 
    tidyr::pivot_longer(cols = c("Bottom", "Surface"), 
                        names_to = "variable", 
                        values_to = "value")
  
  temp0 <- setdiff(min(sebs_temperatures$YEAR):max(sebs_temperatures$YEAR), unique(sebs_temperatures$YEAR))
  temp <- data.frame(matrix(data = NA, 
                            ncol = ncol(sebs_temperatures), 
                            nrow = length(temp0)*2 )) 
  names(temp) <- names(sebs_temperatures)
  temp <- temp |> 
    dplyr::mutate(YEAR = c(temp0, temp0), 
                  region = "Eastern Bering Sea", 
                  variable = c(rep_len(x = "Bottom", length.out = length(temp0)), 
                               rep_len(x = "Surface", length.out = length(temp0))))
  
  sebs_temperatures <- dplyr::bind_rows(sebs_temperatures, temp)
  
  # NBS
  nbs_temperatures <- coldpool::nbs_mean_temperature |>
    dplyr::filter(YEAR <= maxyr) |>
    dplyr::select(YEAR, MEAN_GEAR_TEMPERATURE, MEAN_SURFACE_TEMPERATURE) |>
    dplyr::rename(Bottom = MEAN_GEAR_TEMPERATURE, 
                  Surface = MEAN_SURFACE_TEMPERATURE) |>
    dplyr::mutate(region = "Northern Bering Sea") |> 
    tidyr::pivot_longer(cols = c("Bottom", "Surface"), 
                        names_to = "variable", 
                        values_to = "value")  
  
  temp0 <- setdiff(min(nbs_temperatures$YEAR):max(nbs_temperatures$YEAR), unique(nbs_temperatures$YEAR))
  temp <- data.frame(matrix(data = NA, 
                            ncol = ncol(nbs_temperatures), 
                            nrow = length(temp0)*2 )) 
  names(temp) <- names(nbs_temperatures)
  temp <- temp |> 
    dplyr::mutate(YEAR = c(temp0, temp0), 
                  region = "Northern Bering Sea", 
                  variable = c(rep_len(x = "Bottom", length.out = length(temp0)), 
                               rep_len(x = "Surface", length.out = length(temp0))))
  
  nbs_temperatures <- dplyr::bind_rows(nbs_temperatures, temp)
  
  # mean temp
  mean_temp <- data.frame(region = c(rep("Eastern Bering Sea", 2),
                                     rep("Northern Bering Sea", 2)),
                          variable = rep(c("Bottom", "Surface"), 2),
                          value = c(mean(sebs_temperatures$value[sebs_temperatures$variable == "Bottom"], 
                                         na.rm = TRUE),
                                    mean(sebs_temperatures$value[sebs_temperatures$variable == "Surface"],
                                         na.rm = TRUE),
                                    mean(nbs_temperatures$value[nbs_temperatures$variable == "Bottom"], 
                                         na.rm = TRUE),
                                    mean(nbs_temperatures$value[nbs_temperatures$variable == "Surface"], 
                                         na.rm = TRUE)))
  
  if (srvy == "NEBS") {
    all_temperatures <- dplyr::bind_rows(sebs_temperatures,
                                         nbs_temperatures)
  } else if (srvy == "EBS") {
    all_temperatures <- dplyr::bind_rows(sebs_temperatures)
    mean_temp <- mean_temp[mean_temp$region == "Eastern Bering Sea",]
  } else if (srvy == "NBS") {
    all_temperatures <- dplyr::bind_rows(nbs_temperatures)
    mean_temp <- mean_temp[mean_temp$region == "Northern Bering Sea",]
  }
  
  all_temperatures$variable <- factor(all_temperatures$variable, 
                                      levels=c('Surface','Bottom'))
  
  col <- viridis::mako(2, direction = -1, begin = .3, end = .5)
  color_sst <- col[2] 
  color_bt <- col[1] 
  
  figure <- ggplot2::ggplot(data = all_temperatures,
                   mapping = aes(x = YEAR,
                                 y = value,
                                 color = variable,
                                 shape = variable, 
                                 group = paste0(variable))) +
    facet_wrap(~region, scales = "free") +
    geom_point(size = rel(2)) +
    geom_line() +
    geom_hline(data = mean_temp,
               aes(yintercept = value,
                   color = variable),
               linetype = 2) +
    scale_color_manual(values = c(color_bt, color_sst)) +
    scale_y_continuous(name = "Average temperature (°C)", #expression(bold("Average temperature "~(degree*C))), 
                       expand = c(0, 0),
                       limits = c(0,11.2),
                       breaks = seq(0,12,2)#,
                       # expand = c(0,0)
                       )  + 
    scale_x_continuous(breaks = scales::pretty_breaks(), 
                       name = "Year") +
    guides(
      fill = guide_legend(title.position = "top", 
                          label.position = "bottom",
                          title.hjust = 0.25,
                          nrow = 1)) +
    theme_bw() +
    theme(
      panel.background = element_rect(fill = "white", 
                                      colour = NA), 
      panel.border = element_rect(fill = NA, 
                                  colour = "grey20"), 
      panel.grid.minor = element_blank(),
      strip.background = element_blank(), 
      strip.text = element_text(size = 12), 
      legend.title = element_blank(), 
      legend.text = element_text(size = 10),
      legend.background = element_rect(colour = "transparent", 
                                       fill = "transparent"),
      legend.key = element_rect(colour = "transparent", 
                                fill = "transparent"),
      legend.position = "bottom",
      legend.box = "horizontal")
  
  header <- paste0("Average summer surface and bottom (points and solid lines), and time series average surface and bottom (dashed lines) temperatures (°C) on the eastern Bering Sea shelf, based on data collected during the eastern Bering Sea shelf survey from 1982–",maxyr,
                 ifelse(srvy == "NEBS", 
                        paste0(" (left), and northern Bering Sea shelf based on data collected during standardized summer surveys (right)"), ""), 
                 ". ")
  
  return(list("figure_print" = figure, 
              "table_raw" = all_temperatures, 
              "header" = header))
}
```

```{r fig-mean-temperature-ebs}
nickname <- "fig-mean-temperatur-ebs"
a <- plot_mean_temperatures(maxyr, srvy = "EBS")
for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-mean-temperature-nebs}
nickname <- "fig-mean-temperature"
a <- plot_mean_temperatures(maxyr, srvy = c("NEBS"))
for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-cold-pool-area}
header <- paste0("Annual extent of the summer cold pool on the eastern Bering Sea, based on observations from the eastern Bering Sea shelf survey. The extent of the cold pool is shown as a percentage of the total survey area.",
                 ifelse(srvy == "NEBS", 
                        paste0(" Note that northern Bering Sea areas are not included in this figure.") , ""),
                 " Shading denotes near-bottom temperatures \u2264 2°C, \u2264 1°C, \u2264 0°C, and \u2264 -1°C.")

footnote <- "Areas were summarized from areas in inverse distance weighted rasters."
nickname <- "fig-cold-pool-area"

height <- 3.5
width <- full_page_portrait_width

plot_coldpool_area <- function(coldpool_ebs_bin_area, maxyr, minyr = 1982) {
  
  # maxyr <- 2021
  # 
  # > coldpool_ebs_bin_area
  # year variable  value area_km2  label   proportion        perc
  # 1   1982   ≤ -1°C    425      425 ≤ -1°C 0.0008611844  0.08611844
  # 2   1983   ≤ -1°C    750      750 ≤ -1°C 0.0015197372  0.15197372
  # 3   1984   ≤ -1°C  17650    17650 ≤ -1°C 0.0357644815  3.57644815
  
  table_raw <- coldpool_ebs_bin_area #[!(coldpool_ebs_bin_area$year %in% 1990:1992),]
  
  yr_missing <- setdiff((min(table_raw$year):max(table_raw$year)), unique(table_raw$year))
  
  if (length(yr_missing)>0) {
    temp <- unique(table_raw[,c("variable", "label")])
    
    temp1 <- data.frame(matrix(data = NaN, nrow = nrow(temp)*length(yr_missing), ncol = ncol(table_raw)))
    names(temp1) <- names(table_raw)
    temp1$variable <- temp$variable
    temp1$label <- temp$label
    temp1 <- dplyr::arrange(temp1, label)
    temp1$year <- yr_missing
    
    table_raw <- dplyr::bind_rows(temp1, table_raw)
  }
  
  table_raw$ymax <-table_raw$proportion
  table_raw$ymin <- 0
  zl <- rev(levels(table_raw$variable))
  
  for (i in 2:length(zl)) {
    zi <- table_raw$variable==zl[i]
    zi_1 <- table_raw$variable==zl[i-1]
    table_raw$ymin[zi] <- table_raw$ymax[zi_1]
    table_raw$ymax[zi] <- table_raw$ymin[zi] + table_raw$ymax[zi]
  }
  
  if (is.na(table_raw$proportion[table_raw$year == (maxyr-1)][1])) {
    table_raw <- dplyr::bind_rows( 
      table_raw[table_raw$year == (maxyr),] |> 
        dplyr::mutate(year = maxyr+.5), 
      table_raw)
  }
  
  # table_raw1 <- table_raw |> 
  #   dplyr::arrange(desc(variable)) |>
  #   dplyr::mutate(
  #        variable =  factor(x = as.character(variable), 
  #        levels = unique(as.character(variable)), 
  #        labels = unique(as.character(variable)), ordered = TRUE))
  
  
  # ggplot(table_raw, aes(x=x,ymax=ymax,ymin=ymin, fill=z)) + geom_ribbon()
  
  figure_plot <- ggplot2::ggplot(data = table_raw, 
                            mapping = aes(x = year,
                                          ymax = ymax, 
                                          ymin = ymin, 
                                          fill = variable)) + 
    ggplot2::geom_ribbon() + 
    ggplot2::scale_fill_manual(name = "", # "Temperature", 
                      values = viridis::mako(4, direction = -1, begin = 0.2, end = .8)) +  
    ggplot2::scale_y_continuous(name = "Proportion of Survey Area",
                       expand = c(0, 0),
                       limits = c(0, 1),
                       # expand = c(0, 0),
                       breaks = seq(0,1,0.1)) +
    ggplot2::scale_x_continuous(name = "Year", 
                       limits = c(min(table_raw$year)-0.5,
                                  maxyr + ifelse((is.na(table_raw$proportion[table_raw$year == (maxyr-1)][1])), 1, .5)), 
                       # expand = c(0, 0),
                       breaks = c(seq(1980, maxyr, 5))) +
    # ggplot2::guides(
    #   fill = guide_legend(title.position = "top",
    #                       title.hjust = 0.5,
    #                       title.vjust = -0.5)) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      panel.background = element_rect(fill = "white", colour = NA), 
      panel.border = element_rect(fill = NA, colour = "grey20"), 
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5, size = 12), 
      legend.text = element_text(size = 10),
      legend.background = element_rect(colour = "transparent", 
                                       fill = "transparent"),
      legend.key = element_rect(colour = "transparent",
                                fill = "transparent"),
      legend.position = "bottom",
      legend.box = "horizontal", 
      legend.box.spacing = unit(0, "pt")) +
    ggplot2::ggtitle("Eastern Bering Sea")
  
  return(figure_plot)
}

figure_print <- plot_coldpool_area(coldpool_ebs_bin_area = coldpool_ebs_bin_area, maxyr = maxyr)

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-temperature-[st/bt]-prep}
temp <- function(yrs, 
                 row0, 
                 case, 
                 title0 = NULL, 
                 temperature_zscore = FALSE) {
  
  if (case == "surface") {
    raster_nebs <- terra::rast(coldpool::nbs_ebs_surface_temperature)
    raster_ebs <- terra::rast(coldpool::ebs_surface_temperature)
    colorbar_breaks <- c(-Inf, seq(2, 14, 2), Inf)
  } else if (case == "bottom") {
    raster_nebs <- terra::rast(coldpool::nbs_ebs_bottom_temperature)
    raster_ebs <- terra::rast(coldpool::ebs_bottom_temperature)
    # colorbar_breaks <- c(-Inf, -1, 0, 1, seq(2, 8, 2), Inf)
    colorbar_breaks <- c(-Inf, seq(-1, 8, 1), Inf)
  }
  
  header <- paste0(stringr::str_to_title(case)," temperatures (°C) during the ", 
                   range_text(yrs), " ", 
                   SURVEY, " survey",
                   ifelse(srvy=="NEBS", "s", ""),
                   ". ") 
  if (temperature_zscore) {
    header <- paste0(header, "Years in which the mean ", case,
                     " temperature is one or more standard deviations above or below the time series mean ", case,
                     " temperature are denoted with '+' and '-' in the upper right-hand corner of each subplot. ")
  }
  
  # Create figure_print
  key.title <- ifelse(case == "bottom", 
                      "Bottom temperature (°C)\n", 
                     "Surface temperature (°C)\n")
  
  if (is.null(title0)) {
    title0 <- paste0("Eastern", ifelse(srvy == "NEBS", " and northern", ""),
                     " Bering Sea\n",
                     case, " temperature (", range_text(yrs), ")")
  }
  
  figure_print <- plot_temperature_map(
    raster_nebs = raster_nebs, 
    raster_ebs = raster_ebs, 
    colorbar_breaks = colorbar_breaks, 
    yrs = yrs, 
    yrs_nbs = nbsyr[nbsyr %in% names(raster_nebs)], # in case data isn't ready yet at time of run 
    key.title = key.title, 
    reg_dat = report_types$NEBS$reg_dat,  
    row0 = row0, 
    title0 = title0, 
    temperature_zscore = temperature_zscore) 
  
  return(list("figure_print" = figure_print, 
              "header" = header))
}
```

```{r fig-temperature-[st/bt]}
height <- 3 # full_page_portrait_height
width <- full_page_portrait_width
yrs <- c(maxyr-2):maxyr
row0 <- 1
case_yr0 <- 1

for (case in c("bottom", "surface")) {
    nickname <- paste0("fig-temperature-", ifelse(case=="bottom", "bt", "st"), "-data")
    a <- temp(yrs = yrs, 
              row0 = row0, 
              title0 = "", 
              case = case)
    figure_print <- a$figure_print
    header <- a$header
    
    res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r fig-temperature-[st/bt]-old, eval = FALSE}
height <- full_page_portrait_height+0.25
width <- full_page_portrait_width
yrs0 <- (maxyr-17):maxyr
row0 <- 3
case_yr0 <- 1:2

for (case in c("bottom", "surface")) {
  for (case_yr in case_yr0) {
    
    if (case_yr == 1) {
      yrs <- yrs0[1:(length(yrs0)/2)]
    } else if (case_yr == 2) {
      yrs <- yrs0[((length(yrs0)/2)+1):length(yrs0)]
    }
    nickname <- paste0("fig-temperature-", ifelse(case=="bottom", "bt", "st"), paste0("-", case_yr), "-data")
    a <- temp(yrs = yrs, 
              row0 = row0, 
              title0 = "", 
              case = case)
    figure_print <- a$figure_print
    header <- a$header
    
    res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
  }
}
```

```{r fig-temperature-[st/bt]-comm, eval = FALSE}
temperature_zscore <- FALSE
height <- full_page_portrait_height+0.5
width <- full_page_portrait_width
yrs0 <- (maxyr-17):maxyr
row0 <- 3
case_yr0 <- 1:2

for (case in c("bottom", "surface")) {
  for (case_yr in case_yr0) {
    
    if (case_yr == 1) {
      yrs <- yrs0[1:(length(yrs0)/2)]
    } else if (case_yr == 2) {
      yrs <- yrs0[((length(yrs0)/2)+1):length(yrs0)]
    }
    nickname <- paste0("fig-temperature-", ifelse(case=="bottom", "bt", "st"), paste0("-", case_yr), "-comm")
    a <- temp(yrs = yrs, 
              row0 = row0, 
              case = case, 
              temperature_zscore = temperature_zscore, 
              title0 = "")
    figure_print <- a$figure_print
    header <- a$header
    
    res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
  }
}
```

```{r fig-temperature-[st/bt]-pres}
height <- 8
width <- 8
yrs <- sort(unique(haul$year), decreasing = TRUE)
yrs <- yrs[yrs != 2020][1:8]
row0 <- 2
reg_dat0 <- report_types$NEBS$reg_dat
case_yr <- 1#:2

for (case in c("bottom", "surface")) {
  nickname <- paste0("fig-temperature-", ifelse(case=="bottom", "bt", "st"), paste0("-", case_yr), "-pres")
  title0 = paste0("Eastern", ifelse(srvy == "NEBS", " and northern", ""), " ",  
                  case, " temperature (", range_text(yrs), ")")
  a <- temp(yrs = yrs, 
            row0 = row0, 
            case = case, 
            title0 = title0)
  figure_print <- a$figure_print
  header <- a$header
  
  res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r tab-specimen-samples-}
nickname0 <- paste0("tab-specimen-samples-") 

# length data - from oracle
l <- lengths_maxyr |> 
  dplyr::filter(!(species_code %in% c(68580, 68590, 68560))) |>
  dplyr::select(srvy, species_code, frequency) |> 
  dplyr::group_by(srvy, species_code) |> 
  dplyr::summarise(length = sum(frequency, na.rm = TRUE)) |> 
  dplyr::ungroup() 

# age oto data - from oracle
a <- specimen_maxyr |> 
  dplyr::filter(!is.na(species_code) & specimen_sample_type == 1) |>
  dplyr::select("srvy", species_code) |> 
  dplyr::group_by("srvy" = srvy, species_code) |> 
  dplyr::summarise(age = as.numeric(n())) |> 
  dplyr::ungroup()

# s <- foodlab_predprey0 |>
#   dplyr::left_join(foodlab_haul0, 
#                    by = c("year", "vessel", "cruise", "haul")) |> # , "hauljoin"
#   # dplyr::filter(region == "BS" & 
#   #                 cruise_type == "Race_Groundfish") |> 
#   dplyr::select(year, vessel, cruise, haul, predjoin, nodc = pred_nodc, region, cruise_type) |> # , hauljoin
# dplyr::left_join(foodlab_nodc0 |> dplyr::select(nodc, race, name)) |>
# dplyr::left_join(haul |> dplyr::select(haul, cruise, year, vessel = vessel_id, hauljoin, srvy)) |>
#   dplyr::filter()
#  |> 
#   # dplyr::select(year, type, hauljoin, sta_id_let, sta_id_num, haul) |>
#   dplyr::filter(sta_id_num != 0) |>
#   dplyr::left_join(haul |>
#                      dplyr::select(hauljoin, survey_definition_id, srvy, year)) |>
#   dplyr::filter(!is.na(survey_definition_id)) |>
#   dplyr::mutate(
#     type_desc = dplyr::case_when(
#       type == 1 ~ "Unknown",
#       type == 2 ~ "REEM personnel shipboard scans",
#       type == 3 ~ "representing laboratory scans",
#       type == 4 ~ "representing non-REEM personnel shipboard scans and all shipboard scans performed prior to 2004",
#       type == 6 ~ "representing quantitative laboratory analysis (pred-prey form or all prey weighed)",
#       type == 9 ~ "representing plant collected (observer) data"
#       ))

# other collections not in oracle
temp <- readxl::read_excel(path = paste0(dir_out_rawdata, "/other-field-collections.xlsx"), 
                           sheet = "Sheet1", 
                           skip = 1) |>
  dplyr::filter(year == maxyr) |> 
  dplyr::select(srvy, print_name, dplyr::starts_with("count_")) |> 
  dplyr::select(where(~sum(!is.na(.x)) > 0)) 
names(temp) <- gsub(pattern = "count_", replacement = "", x = names(temp))

# Combine
table_raw0 <- 
  dplyr::full_join(x = l, y = a, 
                   by = c("srvy", "species_code")) |> 
  dplyr::left_join(y = spp_info |> 
                     dplyr::mutate(
                       common_name = gsub(pattern = " (juvenile)", 
                                          replacement = "", x = common_name, fixed = TRUE), 
                       common_name = dplyr::case_when(
                         species_code == 10111 ~ "arrowtooth flounder and Kamchatka flounder", 
                         is.na(common_name) ~ species_name, 
                         common_name == "shorthorn (=warty) sculpin" ~ "shorthorn sculpin", 
                         TRUE ~ common_name)) |> 
                     dplyr::select(species_code, common_name), 
                   by = "species_code") |> 
  dplyr::group_by(srvy, common_name) |> 
  dplyr::summarise_if(is.numeric, sum, na.rm = TRUE) |> 
  dplyr::ungroup() |> 
  dplyr::full_join(y = temp, 
                   by = c("srvy", "common_name" = "print_name")) |> 
  dplyr::mutate(dplyr::across(where(is.numeric), ~replace(., is.na(.), 0)), 
                common_name0 = common_name, 
                common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name)))
  ) |>
  dplyr::select(-species_code) |> 
  dplyr::arrange(common_name) |> 
  dplyr::filter(!grepl(pattern = " crab", x = common_name, ignore.case = TRUE))

# table_raw0$common_name[is.na(table_raw0$common_name)] <- "other" # TOLEDO

table_raw0 <- 
  dplyr::bind_rows(table_raw0, 
                   table_raw0 |> 
                     dplyr::group_by(srvy) |> 
                     dplyr::summarise_if(is.numeric, sum, na.rm = TRUE) |> 
                     dplyr::mutate(common_name = "ZZZTotal") ) |> 
  dplyr::relocate(srvy, common_name, length, age) |> 
  dplyr::rename("length_measurements" = length,
                "otolith_age_structure_samples" = age) |> 
  dplyr::ungroup() |>
  dplyr::arrange(common_name)

# Shouldn't have to do this but idk how else to solve this alphabetization issue
table_raw0 <- table_raw0[order(table_raw0$common_name),]
table_raw0$common_name[table_raw0$common_name == "ZZZTotal"] <- "Total"
table_raw0 <- table_raw0[!grepl(x = table_raw0$common_name, pattern = "NA"),]

for (i in 1:nrow(haul_cruises_maxyr)) {
  nickname <- paste0(nickname0, haul_cruises_maxyr$srvy[i]) 
  header <- paste0("Biological data collected during the ", maxyr, " ", 
                   haul_cruises_maxyr$srvy_long[i],
                   " shelf survey. ") # See \\@SAPcrab", maxyr, " for crab collection summaries. 
  
  table_raw <- table_raw0 |> 
    dplyr::filter(srvy == haul_cruises_maxyr$srvy[i]) |> 
    dplyr::select(where(~ any(. != 0)))
  
  names(table_raw)[!(names(table_raw) %in% c("srvy", "common_name", "common_name0"))] <-
    stringr::str_to_sentence(names(table_raw)[!(names(table_raw) %in% c("srvy", "common_name", "common_name0"))])
  
  names(table_raw)[!(names(table_raw) %in% c("srvy", "common_name", "common_name0"))] <- 
    (gsub(pattern = "_",
          replacement = "\n", 
          x = names(table_raw)[!(names(table_raw) %in% 
                                   c("srvy", "common_name", "common_name0"))], 
          fixed = TRUE))
  names(table_raw)[names(table_raw) == "Otolith\nage\nstructure\nsamples"] <- 
    "Otolith age\nstructure samples"
  names(table_raw)[names(table_raw) == "Pathobiology\nblood\nsamples"] <- 
    "Pathobiology\nblood samples"
  names(table_raw)[names(table_raw) == "Genetic\nfin\nclip\nsamples"] <- 
    "Genetic\nfin clip\nsamples"
  
  table_print <- table_raw |> 
    dplyr::select(-common_name0) |>
    dplyr::mutate(across(where(is.numeric), 
                         formatC, big.mark=",", digits = 0, format = "f")) |> 
    dplyr::ungroup() |> 
    dplyr::filter(srvy == haul_cruises_maxyr$srvy[i]) |> 
    dplyr::select(-"srvy") 
  
  table_print[is.na(table_print) | table_print == "0"] <- "-"
  
  table_print <- table_print |> 
    flextable::flextable() |>
    flextable::set_header_labels(
      common_name = stringr::str_to_title(haul_cruises_maxyr$srvy_long[i])) |> 
    flextable::bold(i = which(table_print$common_name == "Total")) |>
    flextable::valign(valign = "top") |>
    theme_flextable_nmfstm(pgwidth = full_page_portrait_width) |>
    flextable::align(j = 2:ncol(table_print), 
                     align = "right", part = "all")  |>
    flextable::width(width = (5/(ncol(table_raw)-2)), unit = "in") |>
    flextable::width(j = "common_name", width = 1.5, unit = "in")
  
  res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r tab-species-composition, eval = (srvy == "NEBS")}
nickname <- "tab-species-composition" 
height <- full_page_portrait_height # 7
width <- full_page_portrait_width # 6.5
header <- paste0("List of fish taxa encountered in the ",
                 text_list(paste0(haul_cruises_maxyr$srvy_long, " (", 
                                  paste0(haul_cruises_maxyr$srvy, ")")))," survey catches. ")

# Select data and make plot
table_raw <- catch_haul_cruises_maxyr |> 
  dplyr::select(species_code, srvy) |> 
  dplyr::mutate(occured = TRUE) |>
  dplyr::distinct() |>
  tidyr::pivot_wider(id_cols = species_code,
                     names_from = srvy, 
                     values_from = occured, 
                     values_fill = FALSE) |> 
  dplyr::mutate(where = dplyr::case_when(
    (EBS & NBS) ~ "both", 
    (EBS & !NBS) ~ "ebs", 
    (NBS & !EBS) ~ "nbs")) |> 
  dplyr::left_join(
    spp_info |> 
      dplyr::select(species_code, 
                    common_name, 
                    taxon, 
                    species_name_ital, 
                    species_name_noital) |> 
      dplyr::distinct()) |>
  dplyr::filter(taxon == "fish" & 
                  !grepl(x = common_name, pattern = " unid.", fixed = TRUE) &
                  !grepl(x = common_name, pattern = " egg", fixed = TRUE) & 
                  !is.na(common_name)) |> 
  dplyr::mutate(species_name_ital = ifelse(species_name_ital == "", NA, species_name_ital), 
                species_name_noital = ifelse(species_name_noital == "", NA, species_name_noital) ) |>
  dplyr::distinct() |> 
  dplyr::arrange(common_name) |> 
  dplyr::mutate(common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name))))

temp_ebs <- table_raw |> 
  dplyr::filter(where == "ebs")

temp_nbs <- table_raw |> 
  dplyr::filter(where == "nbs")

names(temp_nbs) <- paste0(names(temp_nbs), "_")

# make the same length so they can be bound together
if (nrow(temp_ebs)>nrow(temp_nbs)) {
  temp_nbs <- dplyr::bind_rows(
    temp_nbs, 
    data.frame(common_name_ = rep_len(NA, (nrow(temp_ebs)-nrow(temp_nbs)) ) ) )
} else  if (nrow(temp_nbs)>nrow(temp_ebs)) {
  temp_ebs <- dplyr::bind_rows(
    temp_ebs, 
    data.frame(common_name = rep_len(NA, (nrow(temp_nbs)-nrow(temp_ebs)) ) ) )
}

temp0 <- dplyr::bind_cols(temp_ebs, temp_nbs) |> 
  dplyr::select(-where, -NBS, -EBS) 


table_print <- flextable::flextable(
  data = temp0,
  col_keys = c("dummy_ebs","dummy_nbs"))  |>
  flextable::compose(
    j = "dummy_nbs", part = "body",
    value = as_paragraph(
      # common name and first ( if there are sci names
      as_chunk(paste0(ifelse(is.na(common_name_), "", common_name_), 
                      ifelse((!is.na(species_name_ital_) | !is.na(species_name_noital_)), " (", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)), 
      # italic sci name
      as_chunk(ifelse(!is.na(species_name_ital_), species_name_ital_, ""),
               props = fp_text_default(italic = TRUE, font.size = font_size0, font.family = font0)), 
      # non-italic sci name and/or )
      as_chunk(paste0(ifelse((!is.na(species_name_ital_) & !is.na(species_name_noital_)), " ", ""),
                      ifelse(!is.na(species_name_noital_), species_name_noital_, ""),
                      ifelse((!is.na(species_name_ital_) | !is.na(species_name_noital_)), ")", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)))) |>  
  flextable::compose(
    j = "dummy_ebs", part = "body",
    value = as_paragraph(
      # common name and first ( if there are sci names
      as_chunk(paste0(ifelse(is.na(common_name), "", common_name), 
                      ifelse((!is.na(species_name_ital) | !is.na(species_name_noital)), " (", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)), 
      # italic sci name
      as_chunk(ifelse(!is.na(species_name_ital), species_name_ital, ""),
               props = fp_text_default(italic = TRUE, font.size = font_size0, font.family = font0)), 
      # non-italic sci name and/or )
      as_chunk(paste0(ifelse((!is.na(species_name_ital) & !is.na(species_name_noital)), " ", ""),
                      ifelse(!is.na(species_name_noital), species_name_noital, ""),
                      ifelse((!is.na(species_name_ital) | !is.na(species_name_noital)), ")", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)))) |> 
  flextable::compose(i = 1, j = "dummy_ebs", part = "header",
                     as_paragraph("Encountered in EBS, not in NBS\nCommon name ",
                                  as_chunk(paste0("(scientific name)"),
                                           props = fp_text_default(italic = TRUE, bold = TRUE, font.family = font0)))) |>
  flextable::compose(i = 1, j = "dummy_nbs", part = "header",
                     as_paragraph("Encountered in NBS, not in EBS\nCommon name ", 
                                  as_chunk(paste0("(scientific name)"),
                                           props = fp_text_default(italic = TRUE, bold = TRUE, font.family = font0)))) |>  
  theme_flextable_nmfstm(row_lines = FALSE, 
                         pgwidth = full_page_portrait_width) |>
  flextable::width(width = c(full_page_portrait_width/2, full_page_portrait_width/2), unit = "in") |> 
  flextable::vline(j = "dummy_ebs", part = "all") |> 
  flextable::valign(valign = "top", part = "body")

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-biomass-est-[srvy]-[taxon]}
nickname0 <- "tab-biomass-est-"

table_raw0 <- biomass  |> 
  dplyr::filter(year == maxyr &
                  # place species codes into groups and major species
                  common_name %in% unlist(report_spp |> 
                                      dplyr::filter(table_est) |> 
                                      dplyr::select(print_name)) )  |> 
  dplyr::left_join(total_biomass) |> 
  dplyr::mutate(taxon0 = taxon, 
                # dplyr::mutate(ci = biomass_mt - biomass_dw) # NO, DO NOT DO! - biomass_dw can be 0 if negative! 
                ci = biomass_up - biomass_mt) |> 
  tidyr::separate(
    col = common_name, 
    into = c("group", "taxon"), 
    sep = "_", 
    remove = FALSE) |> 
  dplyr::select(srvy, stratum, year, biomass_mt, ci, 
                group, taxon, taxon0, total)  |>
  tidyr::pivot_wider(id_cols = c("group", "taxon", "taxon0", "srvy", "total"), 
                     names_from = c("stratum"), 
                     values_from = c("biomass_mt", "ci"))  |> 
  dplyr::arrange(taxon)

table_raw0 <- table_raw0 |> 
  dplyr::mutate(order = as.numeric(factor((table_raw0$group))), 
                order = ifelse(grepl(x = taxon, pattern = "other"), order+.1, order), 
                order = ifelse(grepl(x = taxon, pattern = "total"), order+.2, order)) 

table_raw0$order[grepl(pattern = "other", x = table_raw0$group, ignore.case = TRUE)] <- nrow(table_raw0)+10
table_raw0$order[grepl(pattern = "total", x = table_raw0$group, ignore.case = TRUE)] <- nrow(table_raw0)+20

table_raw0 <- table_raw0  |> 
  dplyr::arrange(taxon) |>
  dplyr::arrange(srvy, taxon0, order) |>
  dplyr::mutate(
    CL95 = ci_999, 
    a = "±",
    prop = biomass_mt_999/total, 
    prop0 = prop) |> 
  dplyr::relocate(srvy, group, taxon, biomass_mt_999, a, CL95, prop) |> 
  dplyr::select(-order, -total, -dplyr::starts_with("ci_"))

names(table_raw0) <- gsub(pattern = "biomass_mt_", replacement = "", x = names(table_raw0))

comb <- tidyr::crossing(taxon = c("fish", "invert"), 
                        data.frame(srvy = srvy1, 
                                   srvy_long = srvy11))

for (i in 1:nrow(comb)) {
  
  nickname <- paste0(nickname0, comb$srvy[i], "-", comb$taxon[i]) 
  
  total <- total_biomass |>
    dplyr::filter(year == maxyr &
                    taxon == comb$taxon[i] &
                    srvy == comb$srvy[i]) |> 
    dplyr::left_join(y = data.frame(taxon = c("fish", "invert"), 
                                    taxon_long = c("fish", "invertebrate")))  
  
  header <- paste0("Total taxon biomass estimates (t), ± 95% confidence limits (CL), and biomass estimates by stratum for ", 
                   ifelse(comb$taxon[i] =="invert", "invertebrate", "fish") ,
                   " taxa collected during the ", 
                   maxyr, " ", 
                   comb$srvy_long[i],
                   " survey. The 'proportion' column represents the estimated taxon biomass divided by the total ", 
                   ifelse(comb$taxon[i] =="invert", "invertebrate", "fish") ,
                   " estimated biomass (", 
                   text_list(formatC(x = total$total, digits = 0, format = "f", big.mark = ",")),
                   " t).")
  # Select data and make plot --------------------------------------------------
  table_raw <- table_raw0  |> 
    dplyr::filter(taxon0 == comb$taxon[i] &
                    srvy == comb$srvy[i]) # |> 
    # janitor::remove_empty(which = "cols") 
  
  table_raw1 <- table_raw |> 
    dplyr::mutate_if(is.numeric, replace_na, replace = 0) |> 
    dplyr::mutate(
      prop = ifelse(prop < 0.0001, "<0.0001", 
                    formatC(x = prop, digits = 4, 
                            format = "f", big.mark = ",")), 
      dplyr::across(where(is.numeric), 
                    formatC, big.mark=",", digits = 0, format = "f")) |> 
    dplyr::select(-taxon0, -srvy) |>
    dplyr::select(-prop0) |>  
    dplyr::select_if(~ !all(. == 0))
  
  strat <- names(table_raw1)[7:ncol(table_raw1)]
  
  # Make table_print -------------------------------------------------------------
  pgwidth <- ifelse(comb$srvy[i] == "EBS", 
                    full_page_landscape_width+1, full_page_portrait_width)
  
  table_print <- table_raw1 |> 
    dplyr::mutate(spacer = "") |> 
    dplyr::relocate("group", "taxon", "999", "a", "CL95", "prop", "spacer") |> 
    flextable::flextable()  |>
    flextable::merge_v(j = ~ group) |>
    flextable::merge_h_range(i = ~ is.na(taxon), 
                             j1 = "group", j2 = "taxon", part = "body") |>
    flextable::add_header_row(
      top = TRUE,
      values = c("Taxon", #"", 
                 paste0("Estimated ", ifelse(comb$taxon[i] =="invert", "invertebrate", "fish"), " biomass across survey"),
                 "", # spacer
                 paste0("Estimated ", ifelse(comb$taxon[i] =="invert", "invertebrate", "fish"), " biomass by stratum")),
      colwidths = c(1,5,#1,4,
                    1,(length(strat)))) |>
    flextable::width(width = ((pgwidth-.15-.05-1-1-.6)/(length(strat)+2)), 
                     unit = "in") |>
    flextable::width(j = c("prop"), width = 0.6, unit = "in") |>   
    flextable::width(j = c("a"), width = 0.15, unit = "in") |>   
    flextable::width(j = c("spacer"), width = 0.05, unit = "in") |>   
    flextable::width(j = c("group"), width = 1, unit = "in") |>    
    flextable::width(j = c("taxon"), width = 1, unit = "in") |> 
    
    flextable::bold(i = ~ (grepl(pattern = "Total", x = group) )) |>
    flextable::set_header_labels(
      "group" = "Taxon", 
      "taxon" = "",
      "999" = "Biomass", # ± 95% CI",
      "a" = "±",
      "CL95" = "95% CL",
      "prop" = "Proportion",
      "spacer" = "") |>
    flextable::merge_at(j = c("spacer"), part = "header") |>
    flextable::merge_at(j = c("group"), part = "header") #, "taxon"
  # flextable::merge_at(j = c("999", "a", "CL95"), i = 2, part = "header") 
  row_lines <- TRUE
  pad <- 0
  body_size = 10
  header_size = 10
  spacing = 0.6
  std_b <- officer::fp_border(width = 2, color = "grey10")
  thin_b <- officer::fp_border(width = 0.5, color = "grey10")
  
  x <- flextable::border_remove(x = table_print)
  table_print <- flextable::hline(x = table_print, border = thin_b, part = "body")
  
  table_print <- table_print |> 
    flextable::hline(border = std_b, part = "header") |> 
    flextable::hline_bottom(border = std_b, part = "body") |> 
    flextable::bold(bold = TRUE, part = "header") |> 
    flextable::align_text_col(align = "left", header = TRUE) |> 
    flextable::align_nottext_col(align = "right", header = TRUE) |> 
    flextable::padding(padding = pad, part = "all") |> 
    flextable::font(fontname = font0, part = "all") |> 
    flextable::fontsize(size = body_size - 2, part = "footer") |> 
    flextable::fontsize(size = body_size, part = "body") |> 
    flextable::fontsize(size = header_size, part = "header") |> 
    flextable::fix_border_issues() |> 
    flextable::align(j = c("999", "prop", strat), # , "CL95", strat
                     align = "right", part = "all") |>
    flextable::align(j = c("taxon"), i = 2, 
                     align = "center", part = "header") |>    
    flextable::align(j = c("taxon", strat), i = 1, 
                     align = "center", part = "header") |>
    flextable::align(align = "right", j = "999", i = 2, part = "header") |>
    flextable::align(align = "center", j = "a", i = 2, part = "header") |>
    flextable::align(align = "left", j = "CL95", i = 2, part = "header") |>
    flextable::padding(padding.left = 3, padding.right = 3, j = "a", part = "body")
  
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r tab-majortaxa-pchange-[srvy]}

nickname0 <- "tab-majortaxa-pchange-" 
yrs <- analysisyrs[(length(analysisyrs)-3):length(analysisyrs)]

table_raw0 <- 
  dplyr::left_join(
    y = biomass |> 
      dplyr::filter(stratum == 999 & 
                      srvy %in% srvy1 &
                      year %in% yrs) |> 
      dplyr::select(species_code, year, srvy, biomass_mt), 
    x = report_spp1 |> 
      dplyr::select(print_name, species_name = species_name1, species_code, taxon, table_bio_spp), 
    relationship = "many-to-many",
    by = c("species_code")) |>
  dplyr::filter(table_bio_spp & 
                  !is.na(print_name) & 
                  !is.na(year)) |>
  dplyr::group_by(print_name, srvy, year, taxon) |> 
  dplyr::summarise(biomass_mt = sum(biomass_mt, na.rm = TRUE)) |> 
  dplyr::ungroup() |>
  tidyr::pivot_wider(id_cols = c(srvy, print_name, taxon), 
                     names_from = year, 
                     values_from = biomass_mt) |> 
  dplyr::mutate(
    print_name = gsub(pattern = "smelts (*Osmeridae*) include eulachon, capelin, and rainbow smelt",
                      replacement = "smelts",
                      x = print_name, fixed = TRUE), 
    print_name1 = print_name, 
    print_name = paste0(toupper(substr(print_name, start = 1, stop = 1)), substr(print_name, start = 2, stop = nchar(print_name))))

table_raw0 <- table_raw0 |>   
  dplyr::mutate(
    maxyr = !!sym(paste0(maxyr)), 
    compareyr = dplyr::case_when(
      srvy == "EBS" ~ !!sym(paste0(compareyr[names(compareyr) == "EBS"])),
      srvy == "NBS" ~ !!sym(paste0(compareyr[names(compareyr) == "NBS"]))
    ), 
    # dplyr::across(where(dplyr::starts_with("compareyr")), pchange, end = maxyr, value_only = TRUE),
    change = pchange(start = compareyr, end = maxyr, value_only = TRUE),
    change0 = change,
    change = paste0(formatC(x = change, big.mark=",", digits = 1, format = "f"), "%"),
            dplyr::across(dplyr::starts_with("change"), # where(is.character), 
                      ~ifelse(grepl(x = .x, pattern = "NA"), "", .x))
    # dplyr::across(where(is.character), gsub, pattern = "NA", replacement = "") 
    ) |>
  dplyr::ungroup()  |>
  dplyr::arrange(desc(change0))

# identify which species complexes you need
temp <- dplyr::left_join(
  report_spp1 |> 
      dplyr::select(print_name, species_name = species_name1, species_code, taxon, table_bio_spp), 
  catch_haul_cruises |> 
    dplyr::select(srvy, year, species_code, count) |> 
    dplyr::filter(srvy %in% srvy1) |> 
    dplyr::filter(year %in% c(maxyr, compareyr))) |> 
  dplyr::group_by(print_name, srvy, year) |> 
  dplyr::summarise(count = sum(count, na.rm = TRUE)) |> 
  dplyr::group_by(print_name, srvy) |> 
  dplyr::summarise(count_min = min(count, na.rm = TRUE)) |> 
    dplyr::filter(!is.na(srvy)) |> 
  dplyr::rename(print_name1 = print_name)

table_raw0 <- dplyr::left_join(table_raw0, temp)
# table_raw  <- table_raw0

table_print0 <- table_raw0 |> 
  dplyr::select(-print_name1) |> 
  dplyr::mutate(
    dplyr::across(dplyr::starts_with("20"), formatC, big.mark=",", digits = 0, format = "f"), 
    dplyr::across(dplyr::starts_with("20"), gsub, pattern = "NA%", replacement = ""), 
    dplyr::across(dplyr::ends_with("yr"), formatC, big.mark=",", digits = 0, format = "f"), 
    dplyr::across(dplyr::ends_with("yr"), gsub, pattern = "NA%", replacement = "") , 
    dplyr::across(dplyr::everything(), gsub, pattern = "NA", replacement = "-") )  |>
  dplyr::filter(!is.na(`change0`)) |>
  dplyr::relocate(print_name, as.character(yrs)) |> 
  dplyr::mutate(change = ifelse(as.numeric(count_min) < 100, "-", change))

# reorder table to accommodate "-" %'s
table_print0 <- dplyr::bind_rows(
  table_print0 |> dplyr::filter(change0 > 0 & change != "-"),
  table_print0 |> dplyr::filter(change0 <= 0 & change != "-"), 
  table_print0 |> dplyr::filter(change == "-"),
)

for (i in 1:c(nrow(haul_cruises_maxyr))) {
  nickname <- paste0(nickname0, haul_cruises_maxyr$srvy[i]) 
  header <- paste0(
    "Total estimated biomasses (t) in ", range_text(yrs)," and the percent change between the ",
    compareyr[names(compareyr) == haul_cruises_maxyr$srvy[i]]," and ",maxyr," ", 
    haul_cruises_maxyr$srvy_long[i], 
    ' shelf surveys for predominant fish and invertebrate taxa. Taxa are listed in descending order of percent change from ', compareyr[names(compareyr) == haul_cruises_maxyr$srvy[i]],' to ',maxyr,'. ', 
    ifelse("-" %in% table_print0$change, paste0("Percent changes denoted with '-' indicate that fewer than 100 individuals were caught on the survey", plural_surveys," in ", compareyr[names(compareyr) == haul_cruises_maxyr$srvy[i]]," or ",maxyr, ". "), "")) 
  # Crab data are summarized under other crabs and discussed in detail in the annual crab Technical Memorandum produced by the Shellfish Assessment Program. 
  
  table_raw  <- table_raw0 |> 
    dplyr::filter(srvy == haul_cruises_maxyr$srvy[i]) |> 
    dplyr::select_if(~ !all(is.na(.)))
  
  table_print <- table_print0  |> 
    dplyr::filter(srvy == haul_cruises_maxyr$srvy[i]) |> 
    dplyr::select(-srvy, -change0) |>  
    dplyr::select_if(~ !all(. == "-")) |>
    flextable::flextable(col_keys = c("print_name",
                                      yrs, 
                                      "change")) |>
    flextable::color(color = "red", # https://stackoverflow.com/questions/57474647/italic-and-color-in-an-r-flextable
                     i = ~ grepl(pattern = "-[0-9]+", x = change), 
                     j = "change") |> 
    flextable::width(j = "change", width = 1) |> 
    flextable::set_header_labels(.,
                                 print_name = "Common name", 
                                 dummy = "Scientific name", 
                                 change = paste0("Change (", maxyr, ", ", compareyr[names(compareyr) == haul_cruises_maxyr$srvy[i]], ")" )) |> 
    theme_flextable_nmfstm(row_lines = TRUE, 
                           pgwidth = full_page_portrait_width) |> 
    flextable::align(part = "all", align = "right") |>
    flextable::align(part = "all", align = "left", j = c("print_name"))
  
  res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r tab-est-spp-[srvy]}
nickname0 <- paste0("tab-est-spp-") 

temp <- biomass |> 
  dplyr::filter(year == maxyr &
                  stratum == 999) |> 
  dplyr::filter(srvy %in% srvy1) |> 
  dplyr::select(species_code, srvy, 
                cpue_kgkm2_mean, cpue_kgkm2_sd, 
                biomass_mt, biomass_sd, 
                biomass_up, biomass_dw, 
                cpue_nokm2_mean, cpue_nokm2_sd, 
                population_count, population_sd, 
                population_up, population_dw, 
                n_weight, n_count) |> 
  dplyr::left_join(
    y = report_spp1 |> 
      dplyr::select(species_code, print_name, order, taxon), 
    by = "species_code") |> 
  dplyr::filter(taxon == "fish" &
                  (n_weight != 0) & # if there were none in that survey, don't include
                  order > 0) |> 
  dplyr::ungroup() |> 
  # dplyr::arrange(order) |> 
  dplyr::arrange(print_name) |>
  dplyr::select(-species_code, -order, -taxon) |> 
  dplyr::relocate(print_name) |> 
  dplyr::mutate(print_name = paste0(toupper(substr(print_name, start = 1, stop = 1)), substr(print_name, start = 2, stop = nchar(print_name)))
  )

# Shouldn't have to do this to make this alphabetical, but I give up
temp <- temp[order(temp$print_name), ]

type <- c("wt", "num")
for (i in 1:length(type)) {
  
  nickname <- paste0(nickname0, type[i]) 
  
  if (i == 1) { # CPUE (WT/km²) and BIOMASS
    
    header <- paste0("Total mean CPUE (kg/km²) with standard deviation (SD; kg/km²), estimated biomass (t) with SD (t), 95% lower (LCL; t) and upper (UCL; t) confidence limits, and number of hauls where weights ")
    
    table_raw <- temp |> 
      dplyr::select(print_name, srvy, 
                    cpue_kgkm2_mean, cpue_kgkm2_sd, 
                    biomass_mt, biomass_sd, 
                    biomass_dw, biomass_up, 
                    n_weight) 
    
    table_print <- table_raw |> 
      dplyr::mutate(cpue_kgkm2_mean = formatC(x = cpue_kgkm2_mean, 
                                              digits = 2, 
                                              format = "f", big.mark = ","), 
                    cpue_kgkm2_sd = formatC(x = cpue_kgkm2_sd, 
                                            digits = 2, 
                                            format = "f", big.mark = ","), 
                    biomass_mt = formatC(x = biomass_mt, 
                                         digits = 0, 
                                         format = "f", big.mark = ",") , 
                    biomass_up = formatC(x = biomass_up,
                                         digits = 0,
                                         format = "f", big.mark = ",") ,
                    biomass_dw = formatC(x = biomass_dw,
                                         digits = 0,
                                         format = "f", big.mark = ",") ,
                    biomass_sd = formatC(x = biomass_sd, 
                                         digits = 0, 
                                         format = "f", big.mark = ","))
    
    if (srvy != "NEBS") {
      table_print <- table_print |>
        dplyr::select(-"srvy")
    }
    
    table_print <- table_print |> 
      flextable::flextable() |> 
      flextable::set_header_labels(
        print_name = "Species", 
        # srvy = "Shelf area", 
        cpue_kgkm2_mean = paste0("CPUE mean (kg/km²)"), 
        cpue_kgkm2_sd = paste0("CPUE SD (kg/km²)"), 
        biomass_mt = paste0("Biomass (t)"), 
        biomass_sd = paste0("Biomass SD (t)"), 
        biomass_dw = paste0("95% LCL"),
        biomass_up = paste0("95% UCL"),
        n_weight = "Hauls w/weights") 
    
  } else { # CPUE No/km² and population_count
    
    header <- paste0("Total mean count CPUE (no/km²) with standard deviation (SD; no/km²), estimated population (count) with SD (t), 95% lower (LCL) and upper (UCL) confidence limits, and number of hauls where species counts ")
    
    table_raw <- temp |> 
      dplyr::select(print_name, srvy, 
                    cpue_nokm2_mean, cpue_nokm2_sd, 
                    population_count, population_sd, 
                    population_dw,population_up,  
                    n_count)
    
    population_count0 <- find_units(unit = "", unt = "", dat = table_raw$population_count)
    population_sd0 <- find_units(unit = "", unt = "", dat = table_raw$population_sd)
    
    table_print <- table_raw |> 
      dplyr::mutate(cpue_nokm2_mean = formatC(x = cpue_nokm2_mean, 
                                              digits = 2, 
                                              format = "f", big.mark = ","),
                    cpue_nokm2_sd = formatC(x = cpue_nokm2_sd, 
                                            digits = 2, 
                                            format = "f", big.mark = ","), 
                    population_count = formatC(x = population_count, 
                                               digits = 0, 
                                               format = "f", big.mark = ",") , 
                    population_up = formatC(x = population_up,
                                            digits = 0,
                                            format = "f", big.mark = ",") ,
                    population_dw = formatC(x = population_dw,
                                            digits = 0,
                                            format = "f", big.mark = ",") ,
                    population_sd = formatC(x = population_sd, 
                                            digits = 0, 
                                            format = "f", big.mark = ","))
    
    if (srvy != "NEBS") {
      table_print <- table_print |>
        dplyr::select(-"srvy")
    }
    table_print <- table_print |> 
      # dplyr::select(-srvy) |>
      flextable::flextable() |> 
      flextable::set_header_labels(
        print_name = "Species", 
        cpue_nokm2_mean = paste0("CPUE mean (no/km²)"), 
        cpue_nokm2_sd = paste0("CPUE SD (no/km²)"), 
        population_count = paste0("Population"), 
        population_sd = paste0("Population SD"), 
        population_dw = paste0("95% LCL"),
        population_up = paste0("95% UCL"),
        n_count = "Hauls w/counts") 
  }
  
  table_print <- table_print |> 
    flextable::merge_v(target = "print_name", 
                       j = "print_name", part = "body") |> 
    flextable::valign(valign = "top") |>  
    theme_flextable_nmfstm(row_lines = TRUE, 
                           pgwidth = full_page_portrait_width)  
  
  if (srvy == "NEBS") {
    table_print <- table_print |> 
      flextable::width(j = "srvy", width = .25) |>
      flextable::set_header_labels(
        srvy = "Shelf area") 
  }
  
  header <- paste0(header, "were collected for common groundfish species by survey region during the ",
                   maxyr," ", text_list(paste0(haul_cruises_maxyr$srvy_long, 
                                               " (", haul_cruises_maxyr$srvy, "; ", 
                                               haul_cruises_maxyr$stations_completed, " stations completed)")), 
                   " shelf survey",plural_surveys,". ")
  
  table_print <- table_print |> 
    flextable::width(j = "print_name", width = .8) |>
    flextable::width(j = ifelse(srvy == "NEBS", 3, 2):(length(dim(table_print)$widths)), 
                     width = (full_page_portrait_width-.8-ifelse(srvy == "NEBS", .25, 0))/(length(dim(table_print)$widths)-ifelse(srvy == "NEBS", 2, 1))) |>
    flextable::align(align = "right", 
                     part = "all") |>
    flextable::align(j = "print_name", 
                     align = "left", 
                     part = "all") 
  
  res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r tab-biomass-pchange-pres}

nickname <- "tab-biomass-pchange-pres"
header <- paste0("Biomass and abundance change for species in ", 
                 maxyr, " and ", compareyr," ", SURVEY, 
                 " survey.")

table_raw <- dplyr::bind_rows(biomass_maxyr, biomass_compareyr) |>
  dplyr::left_join(
    #   x = biomass, 
    y = report_spp1 |>
      dplyr::filter(!is.na(order) & table_bio_portion ) |>
      dplyr::select(species_code, order) |>
      dplyr::distinct(),
    by = "species_code") |>
  dplyr::filter(year %in% c(maxyr, compareyr) &
                  stratum == 999 & 
                  !is.na(order) &
                  !is.na(common_name)
  ) |> 
  dplyr::group_by(common_name, year, srvy, order) |> 
  dplyr::summarise(biomass = sum(biomass_mt, na.rm = TRUE), 
                   population = sum(population_count, na.rm = TRUE)) |> 
  # calculate pchange
  dplyr::mutate(year0 = ifelse(year == maxyr, "maxyr", "compareyr")) |> 
  tidyr::pivot_wider(id_cols = c("order", "common_name", "srvy"), 
                     names_from = "year0", 
                     values_from = c("biomass", "population")) |> 
  dplyr::mutate(
    biomass_pchange = pchange(end = biomass_maxyr, 
                              start = biomass_compareyr, 
                              value_only = TRUE), 
    population_pchange = pchange(end = population_maxyr, 
                                 start = population_compareyr, 
                                 value_only = TRUE), 
    population_maxyr = population_maxyr/1000, 
    population_compareyr = population_compareyr/1000, 
    dplyr::across(dplyr::where(is.numeric), formatC, format = "f", big.mark = ",", digits = 0), 
    dplyr::across(dplyr::ends_with("_pchange"), gsub, pattern = "-0", replacement = "0"), 
    dplyr::across(dplyr::ends_with("yr"), gsub, pattern = "NA", replacement = ""), 
    biomass_maxyr = paste0(biomass_maxyr, "", ifelse(biomass_pchange %in% c("NA"), "", paste0(" (", biomass_pchange, "%)"))), 
    population_maxyr = paste0(population_maxyr, ifelse(population_pchange %in% c("NA"), "", paste0(" (", population_pchange, "%)"))), 
    order = as.numeric(order), 
    biomass = paste0(biomass_compareyr, "\n", biomass_maxyr), 
    population = paste0(population_compareyr, "\n", population_maxyr), 
    year = dplyr::case_when(
      srvy == "EBS" ~ paste0(compareyr[names(compareyr) == "EBS"], "\n", maxyr), 
      srvy == "NBS" ~ paste0(compareyr[names(compareyr) == "NBS"], "\n", maxyr))) |> 
  dplyr::select(order, common_name, srvy, year, biomass, population) |>
  # tidyr::pivot_longer(names_to = "var", 
  #                     values_to = "val", 
  #                     cols = c("biomass_compareyr", "population_compareyr", "biomass_maxyr", "population_maxyr")) |> 
  # dplyr::mutate(year = dplyr::case_when(
  #   grepl(x = var, pattern = "pchange") ~ 1, 
  #   grepl(x = var, pattern = "maxyr") ~ maxyr, 
  #   grepl(x = var, pattern = "compareyr") ~ compareyr), 
  #   var = sapply((strsplit(x = var, split = "_")),"[[",1)) |> 
  # # final format
  tidyr::pivot_wider(id_cols = c("order", "common_name"),
                     names_from = c("srvy"), # , "year"
                     values_from = c("biomass", "population", "year")) |>
  dplyr::arrange((order)) |>
  dplyr::select(-order) |>
  dplyr::ungroup() |> 
  dplyr::relocate(common_name, dplyr::starts_with("year")) |>  # year, 
  dplyr::relocate(common_name, dplyr::ends_with("_EBS"), dplyr::ends_with("_NBS")) # year, 

h_r1 <- rep_len(x = " ", length.out = ncol(table_raw))
h_r1[grepl(pattern = "EBS", x = names(table_raw))] <- "EBS"
h_r1[grepl(pattern = "NBS", x = names(table_raw))] <- "NBS"

h_r2 <- stringr::str_to_sentence(names(table_raw))
h_r2 <- gsub(pattern = "_", replacement = " ", x = h_r2)
h_r2[grepl(pattern = "Biomass", x = h_r2)] <- "Biomass (mt)"
h_r2[grepl(pattern = "Population", x = h_r2)] <- "Population (x1,000)"
h_r2[grepl(pattern = "Year", x = h_r2)] <- "Years"

table_print <- table_raw |> 
  flextable::flextable()  |>  
  theme_flextable_nmfstm(row_lines = TRUE, 
                         pgwidth = full_page_landscape_width) |> 
  flextable::merge_v(j = "common_name", part = "body") |>
  flextable::bold(j = 1, i = ~ !is.na(common_name) ) |> 
  flextable::add_header(
    values = eval(parse(text = paste0("list(", 
                                      text_list(paste0(names(table_raw), " = '", h_r1, "'"), 
                                                sep_last = ", ", sep_last2 = ", "), ") " ) ) ), 
    top = TRUE) |>
  flextable::set_header_labels(
    values = eval(parse(
      text = paste0("list(", 
                    text_list(paste0(names(table_raw), " = '", h_r2, "'"), 
                              sep_last = ", ", sep_last2 = ", "), ") " ) ) ) ) |>
  flextable::merge_h(i = 1, part = "header") |>
  flextable::align(i = 1, align = "center", part = "header") |> 
  flextable::vline(j = "population_EBS", part = "all") |> 
  # make all biomass and population columns green
  flextable::bg(bg = positive, 
                j = c(which(grepl(x = names(table_raw), pattern = "biomass")),
                      which(grepl(x = names(table_raw), pattern = "population")))) |>
  # EBS biomass
  flextable::bg(bg = negative,
                i = ~ grepl(pattern = "-", x = biomass_EBS),
                j = c("biomass_EBS")) |>
  flextable::bg(bg = "white",
                i = ~ (is.na(biomass_EBS) | 
                         grepl(pattern = "\\(0%)", x = biomass_EBS) | 
                         !grepl(pattern = "%)", x = biomass_EBS)) ,
                j = c("biomass_EBS")) |> 
  # EBS population
  flextable::bg(bg = negative,
                i = ~ grepl(pattern = "-", x = population_EBS),
                j = c("population_EBS")) |>
  flextable::bg(bg = "white",
                i = ~ (is.na(population_EBS) | 
                         grepl(pattern = "\\(0%)", x = population_EBS) | 
                         !grepl(pattern = "%)", x = population_EBS)) ,
                j = c("population_EBS")) |> 
  flextable::valign(valign = "top", part = "body", 
                    j = c(which(grepl(x = names(table_raw), pattern = "biomass")),
                          which(grepl(x = names(table_raw), pattern = "population"))) ) |>
  flextable::fontsize(size = 14, part = "header") |>
  flextable::fontsize(size = 12, part = "body") |>
  flextable::fontsize(size = 14, part = "body", j = 1) |>
  flextable::hline_bottom(part = "body",
                          border = fp_border(color = "transparent", style = "solid", width = 1))

if (srvy == "NEBS") {
  table_print <- table_print  |> 
    # NBS biomass
    flextable::bg(bg = negative,
                  i = ~ grepl(pattern = "-", x = biomass_NBS),
                  j = c("biomass_NBS")) |>
    flextable::bg(bg = "white",
                  i = ~ (is.na(biomass_NBS) | 
                           grepl(pattern = "\\(0%)", x = biomass_NBS) | 
                           !grepl(pattern = "%)", x = biomass_NBS)) ,
                  j = c("biomass_NBS")) |> 
    # NBS biomass
    flextable::bg(bg = negative,
                  i = ~ grepl(pattern = "-", x = population_NBS),
                  j = c("population_NBS")) |>
    flextable::bg(bg = "white",
                  i = ~ (is.na(population_NBS) | 
                           grepl(pattern = "\\(0%)", x = population_NBS) | 
                           !grepl(pattern = "%)", x = population_NBS)) ,
                  j = c("population_NBS"))
}
res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

# Endmatter

```{r tab-glossary}

nickname <- "tab-glossary"
header <- "Glossary of terms. "

table_raw <- readxl::read_excel(path = paste0(dir_out_rawdata, "/glossary-of-terms.xlsx"), 
                                sheet = "Sheet1") |>
  dplyr::mutate(include = ifelse(is.na(include), TRUE, include)) |> 
  dplyr::filter(include) |> 
  dplyr::select(-include) |> 
  dplyr::arrange(term)

names(table_raw) <- stringr::str_to_title(names(table_raw))

table_print <- table_raw |> 
  flextable::flextable()  |>
  theme_flextable_nmfstm(pgwidth = full_page_portrait_width) |> 
  flextable::width(width = c(2, full_page_portrait_width-2)) |> 
  flextable::theme_zebra()

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

# Appendix A and B

```{r tab_app_taxa_found_*_prep}

tab_taxa_found_ <- function(temp, 
                            nickname0, 
                            maxyr, 
                            catch_haul_cruises_maxyr, 
                            spp_info) {
  
  list_tables0 <- list()
  
  cnt_tables <- 0
  nickname0 <- "tab-app-taxa-found-" 
  
  for (i in 1:nrow(temp)) {
    cnt_tables <- cnt_tables + 1
    newobj <- TRUE
    nickname <- paste0(nickname0, 
                       temp$srvy[i], 
                       "-",  
                       temp$taxon[i])
    
    header <- paste0(stringr::str_to_sentence(temp$taxon[i]), 
                     " taxa encountered during the ", 
                     maxyr, " ", temp$srvy_long[i], 
                     " shelf survey listed alphabetically by ", 
                     ifelse(temp$taxon[i] == "fish", "family", "phylum"), ".")
    
    table_raw <- 
      dplyr::left_join(
        x = catch_haul_cruises_maxyr |> 
          dplyr::filter(year == maxyr &
                          srvy == temp$srvy[i]) |> 
          dplyr::select(station, latitude_dd_start, longitude_dd_start, depth_gear_m, species_code), 
        y = spp_info |> 
          dplyr::rename(taxon0 = ifelse(temp$taxon[i] == "fish", "family", "phylum")) |>
          dplyr::select(species_name, common_name, taxon, species_code, taxon0), 
        by = "species_code") |> 
      dplyr::filter(taxon == temp$taxon0[i]) |> 
      dplyr::mutate(taxon = taxon0) |> 
      dplyr::group_by(taxon, species_name, common_name ) |> 
      dplyr::summarise(stations_n = n(), 
                       depth_min = min(depth_gear_m, na.rm = TRUE), 
                       depth_max = max(depth_gear_m, na.rm = TRUE), 
                       depth_mean = mean(depth_gear_m, na.rm = TRUE), 
                       lat_min = min(latitude_dd_start, na.rm = TRUE), 
                       lat_max = max(latitude_dd_start, na.rm = TRUE)) |> 
      dplyr::ungroup() |> 
      dplyr::arrange(species_name)  |>
      dplyr::arrange(taxon)  |>
      dplyr::mutate(stations_n = formatC(stations_n, big.mark=",", digits = 0, format = "f"))  |>
      dplyr::mutate(across(c("lat_min", "lat_max", "depth_mean"), 
                           formatC, big.mark=",", digits = 1, format = "f"), 
                    taxon = ifelse(is.na(taxon), "Other", taxon), 
                    across(c("depth_min", "depth_max"), 
                           formatC, big.mark=",", digits = 0, format = "f"))
    
    table_print <- table_raw |> 
      dplyr::mutate(species_name1 = species_name) |>
      dplyr::mutate(spp = dplyr::case_when(
        grepl(pattern = "sp.", x = species_name1, fixed = TRUE) ~ "sp.", 
        grepl(pattern = "spp.", x = species_name1, fixed = TRUE) ~ "spp.", 
        grepl(pattern = "egg case", x = species_name1, fixed = TRUE) ~ "egg case", 
        grepl(pattern = "Naticidae egg", x = species_name1, fixed = TRUE) ~ "gastropod egg", 
        grepl(pattern = "gastropod egg", x = species_name1, fixed = TRUE) ~ "gastropod egg", 
        grepl(pattern = "hybrid", x = species_name1, fixed = TRUE) ~ "hybrid", 
        grepl(pattern = "Polychaete tubes", x = species_name1, fixed = TRUE) ~ "Polychaete tubes", 
        TRUE ~ "")) |>
      dplyr::mutate(
        spacer = "",
        species_name = species_name1, 
        species_name1 = 
          gsub(pattern = " sp.", replacement = "", 
               x = species_name1, fixed = TRUE), 
        species_name1 =
          gsub(pattern = " spp.", replacement = "",
               x = species_name1, fixed = TRUE),
        species_name1 =
          gsub(pattern = " egg case", replacement = "",
               x = species_name1, fixed = TRUE),          
        species_name1 =
          gsub(pattern = "Naticidae egg", replacement = "",
               x = species_name1, fixed = TRUE),  
        species_name1 =
          gsub(pattern = "gastropod egg", replacement = "",
               x = species_name1, fixed = TRUE),          
        species_name1 =
          gsub(pattern = " hybrid", replacement = "",
               x = species_name1, fixed = TRUE),    
        species_name1 =
          gsub(pattern = "Polychaete tubes", replacement = "",
               x = species_name1, fixed = TRUE),      
        species_name2 = dplyr::case_when(
          !grepl(pattern = " ", x = species_name, fixed = TRUE) ~ species_name1), 
        species_name1 = dplyr::case_when(
          grepl(pattern = " ", x = species_name, fixed = TRUE) ~ species_name1))
    
    std_b <- officer::fp_border(width = 2, color = "grey10")
    
    table_print <- table_print |>
      flextable::flextable(
        col_keys = c("taxon" ,
                     "species_name",
                     "common_name", "stations_n", 
                     "depth_min", "depth_max", "depth_mean", 
                     "spacer", "lat_min", "lat_max"))  |>
      flextable::merge_v(j = ~ taxon) |>
      flextable::merge_h_range(i = ~ is.na(taxon), j1 = "species_name", j2 = "taxon", part = "body") |>
      flextable::compose(j = "species_name",
                         value = as_paragraph(as_i(species_name1), species_name2, " ", spp)) |> 
      flextable::set_header_labels(
        values = list(
          taxon = "", #ifelse(temp$taxon[i] == "fish", "Family", "Phylum"),
          species_name = "", #"Scientific name",
          common_name = "", #"Common name",
          stations_n = "", #"Number stations present", 
          depth_min = "Min.", 
          depth_max = "Max.", 
          depth_mean = "Avg.", 
          spacer = " ", 
          lat_max = "S", 
          lat_min = "N")) |>
      flextable::add_header_row(top = TRUE,
                                values = c(ifelse(temp$taxon[i] == "fish", "Family", "Phylum"),
                                           "Scientific name", "Common name", "#Hauls",
                                           "Bottom depth (m)", "", "Latitude"),
                                colwidths = c(1,1,1,1,3,1,2)) |>
      flextable::align(i = 1, align = "center", part = "header")  |>  
      flextable::merge_at(j = c("taxon"), part = "header") |>
      flextable::merge_at(j = c("species_name"), part = "header") |>
      flextable::merge_at(j = c("common_name"), part = "header") |>
      flextable::merge_at(j = c("spacer"), part = "header") |>
      flextable::merge_at(j = c("stations_n"), part = "header") |>
      theme_flextable_nmfstm(row_lines = TRUE, 
                             pgwidth = full_page_portrait_width) |>
      flextable::width(width = .5, unit = "in") |>
      flextable::width(width = .5, j = c("stations_n"), unit = "in") |>
      flextable::width(width = .05, j = c("spacer"), unit = "in") |>
      flextable::width(width = 1.3, j = c("taxon"), unit = "in") |>
      flextable::width(width = 1, j = c("common_name"), unit = "in") |>
      flextable::width(width = 1.25, j = c("species_name"), unit = "in") |>
      flextable::padding(padding = .6, part = "all") |> 
      flextable::align(
        j = c("stations_n", "depth_min", "depth_max", "depth_mean", "lat_max", "lat_min"), 
        align = "right", part = "all") |>
      flextable::align(
        j = c("depth_max", "depth_min", "depth_mean", "lat_max", "lat_min"), 
        align = "center", i = 1, part = "header") |> 
      flextable::hline(border = std_b, part = "header") 
    
    # output from function
    list_tables0$temp <- list("table_print" = table_print, 
                              "table_raw" = table_raw, 
                              "header" = header, 
                              "nickname" = nickname)
    names(list_tables0)[names(list_tables0) == "temp"] <- nickname
  }
  
  return(list_tables0)
}

```


## Appendix A (EBS)

```{r tab-app-taxa-found-EBS}
temp <- tidyr::crossing(data.frame(taxon = c("invertebrate", "fish"), 
                                   taxon0 = c("invert", "fish")), 
                        haul_cruises_maxyr |> 
                          dplyr::select(srvy_long, srvy) |> 
                          dplyr::filter(srvy == "EBS"))

# cnt_pre0 <- cnt_pre0 + 1; cnt_pre1 <- LETTERS[cnt_pre0]
list_tables0 <- tab_taxa_found_(temp = temp, 
                                # cnt_pre = cnt_pre, #paste0("Appendix ", cnt_pre), 
                                maxyr = maxyr, 
                                catch_haul_cruises_maxyr = catch_haul_cruises_maxyr, 
                                spp_info = spp_info) 
cnt_tables <- 0
for (i in 1:length(list_tables0)) {
  # cnt_pre <- cnt_pre1 # paste0("Appendix ", cnt_pre1)
  a <- list_tables0[[i]]
  for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
  
  # Save table
  res <- knitr::knit_child(
    text = knitr::knit_expand(
      file = paste0(dir_code, "_child_save_figtab.Rmd")), 
    quiet = TRUE
  )
}

```

## Appendix B (NBS)

```{r tab-app-taxa-found-NBS}
if (srvy == "NEBS") {
  temp <- tidyr::crossing(data.frame(taxon = c("invertebrate", "fish"), 
                                     taxon0 = c("invert", "fish")), 
                          haul_cruises_maxyr |> 
                            dplyr::select(srvy_long, srvy) |> 
                            dplyr::filter(srvy == "NBS"))
  if (nrow(temp) != 0) {   
    list_tables0 <- tab_taxa_found_(temp = temp, 
                                    # cnt_pre = cnt_pre, #paste0("Appendix ", cnt_pre), 
                                    maxyr = maxyr, 
                                    catch_haul_cruises_maxyr = catch_haul_cruises_maxyr, 
                                    spp_info = spp_info) 
    
    cnt_tables <- 0
    for (i in 1:length(list_tables0)) {
      # cnt_pre <- cnt_pre1 # paste0("Appendix ", cnt_pre1)
      a <- list_tables0[[i]]
      for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
      
      # Save table
      res <- knitr::knit_child(
        text = knitr::knit_expand(
          file = paste0(dir_code, "_child_save_figtab.Rmd")), 
        quiet = TRUE
      )
    }
  }
}
```

# Appendix C and D

## tab_fish_*_prep

```{r tab_app_fish_*_prep}

tab_app_fish_ <- function(temp, 
                          maxyr, 
                          haul_cruises_maxyr, 
                          report_spp1,
                          spp_info) {
  list_tables0 <- list()
  
  nickname0 <- "tab-app-fish-" 
  cnt_tables <- 0
  
  temp0 <- report_spp1 |> 
    dplyr::filter(taxon == "fish" & 
                    text_spp == TRUE &
                    file_name != "pacific_halibut") |> 
    dplyr::select(file_name, species_code) |> 
    dplyr::distinct() 
  
  for (i in 1:nrow(temp)) {
    cnt_tables <- cnt_tables + 1
    print(temp$file_name[i])
    
    nickname <- paste0(nickname0, 
                       temp$srvy[i], 
                       "-",  
                       temp$file_name[i])
    
    spp_code <- temp0$species_code[temp0$file_name == temp$file_name[i]]
    
    header <- paste0("Population estimates by sex and size for ",
                     temp$print_name[i], " (", temp$species_name[i], ")", 
                     " from the ", 
                     maxyr, " ", temp$srvy_long[i], 
                     " shelf survey.")
    
    table_raw <- sizecomp_maxyr |> 
      dplyr::filter(species_code %in% spp_code &
                      srvy == temp$srvy[i]) |> 
      dplyr::distinct() |>
      dplyr::ungroup()
    
    if (nrow(table_raw) != 0) { 
      
      table_raw <- table_raw |> 
        dplyr::select(length_mm, population_count, sex) |>
        tidyr::pivot_wider(
          id_cols = length_mm, 
          names_from = sex, 
          values_from = population_count, 
          values_fill = 0) 
      
      if (!("males" %in% names(table_raw))) {
        table_raw$males <- 0
      }
      if (!("females" %in% names(table_raw))) {
        table_raw$females <- 0
      }
      if (!("unsexed" %in% names(table_raw))) {
        table_raw$unsexed <- 0
      }
      
      table_raw <- table_raw |>
        dplyr::mutate(
          total = males + females + unsexed) |>
        dplyr::arrange(length_mm) |> 
        dplyr::ungroup() |> 
        dplyr::mutate(
          prop = total/sum(total, na.rm = TRUE), 
          cumprop = cumsum(prop))
      
      table_raw <- 
        dplyr::bind_rows(table_raw |> 
                           dplyr::mutate(length_mm = as.character(length_mm)), 
                         table_raw |>
                           dplyr::summarise(across(everything(), ~ sum(., is.na(.), 0))) |> 
                           dplyr::mutate(length_mm = "Total", 
                                         cumprop = 1))  |>
        dplyr::mutate(across((ends_with("prop")), 
                             formatC, big.mark=",", digits = 4, format = "f")) |>
        dplyr::mutate(across(where(is.numeric), 
                             formatC, big.mark=",", digits = 0, format = "f"))
      
      table_print <- table_raw |>
        flextable::flextable() |> 
        flextable::set_header_labels(
          length_mm = "Length (cm)",
          males = "Males",
          females = "Females",
          unsexed = "Unsexed", 
          total = "Total", 
          prop = "Proportion", 
          cumprop = "Cumulative proportion") |>
        flextable::align(i = 1, align = "center", part = "header")  |>  
        flextable::bold(i = nrow(table_raw), part = "body") |>
        theme_flextable_nmfstm(row_lines = FALSE, 
                               pgwidth = full_page_portrait_width) |>
        flextable::width(width = 1, unit = "in") |> 
        flextable::width(j = "length_mm", width = .5, unit = "in") |> 
        flextable::hline_bottom(border = fp_border(width = 2), part = "header")
      
      list_tables0$temp <- list("table_print" = table_print, 
                                "table_raw" = table_raw, 
                                "header" = header, 
                                "nickname" = nickname)
      names(list_tables0)[names(list_tables0) == "temp"] <- nickname
    }
  }
  return(list_tables0)
}
```


## Appendix C (or B if EBS only) (EBS)

```{r tab-app-fish-EBS}
temp <- tidyr::crossing(haul_cruises_maxyr |> 
                          dplyr::select(srvy_long, srvy) |> 
                          dplyr::filter(srvy == "EBS"), 
                        report_spp1 |> 
                          dplyr::filter(taxon == "fish" & text_spp == TRUE) |> 
                          dplyr::select(file_name, print_name, common_name1, species_name)  |> 
                          dplyr::mutate(species_name = gsub(species_name, pattern = " larva", replacement = "")) |> 
                          dplyr::distinct())

list_tables0 <- tab_app_fish_(
  temp = temp, 
  maxyr = maxyr, 
  haul_cruises_maxyr = haul_cruises_maxyr, 
  report_spp1 = report_spp1,
  spp_info = spp_info)

cnt_tables <- 0
for (i in 1:length(list_tables0)) {
  a <- list_tables0[[i]]
  for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
  
  # Save table
  res <- knitr::knit_child(
    text = knitr::knit_expand(
      file = paste0(dir_code, "_child_save_figtab.Rmd")), 
    quiet = TRUE
  )
}
```

## Appendix D (NBS)

```{r tab-app-fish-NBS}
if (srvy == "NEBS") {
  temp <- tidyr::crossing(haul_cruises_maxyr |> 
                            dplyr::select(srvy_long, srvy) |> 
                            dplyr::filter(srvy == "NBS"), 
                          report_spp1 |> 
                            dplyr::filter(taxon == "fish" & text_spp == TRUE) |> 
                            dplyr::select(file_name, print_name, common_name1, species_name) |> 
                            dplyr::mutate(species_name = gsub(species_name, pattern = " larva", replacement = "")) |> 
                            dplyr::distinct())
  if (nrow(temp) != 0) {   
    list_tables0 <- tab_app_fish_(
      temp = temp, 
      maxyr = maxyr, 
      haul_cruises_maxyr = haul_cruises_maxyr, 
      report_spp1 = report_spp1,
      spp_info = spp_info)
    
    cnt_tables <- 0
    for (i in 1:length(list_tables0)) {
      a <- list_tables0[[i]]
      for (jjj in 1:length(a)) { assign(names(a)[jjj], a[[jjj]]) }
      
      # Save table
      res <- knitr::knit_child(
        text = knitr::knit_expand(
          file = paste0(dir_code, "_child_save_figtab.Rmd")), 
        quiet = TRUE
      )
    }
  }
}
```

# Data changes

```{r tab-taxon-changes, eval = FALSE}
nickname <- "tab-taxon-changes"
header <- paste0(maxyr, " changes to taxon species names and species codes (if changed), along with specific action taken and reason for update. ")

table_raw <- gap_products_taxonomic_changes0 |>
  dplyr::filter(year_changed == maxyr) |> 
  dplyr::arrange(new_species_name) |> 
  dplyr::mutate(dplyr::across(dplyr::everything(), as.character))

# separate text to italize and not ---------------------------------------------
table_raw$new_species_name_noi <- table_raw$old_species_name_noi <- ""
table_raw$new_species_name_i <- table_raw$new_species_name
table_raw$old_species_name_i <- table_raw$old_species_name
table_raw$new_species_name <- paste0(table_raw$new_species_name, " ")
table_raw$old_species_name <- paste0(table_raw$old_species_name, " ")
cases <- c(" larvae", " n.", " sp.", " spp.", " egg case", " (", " egg") # , " n."
which0_old <- which0_new <- c()
for (ii in cases) {
  # new names
  which0 <- which(sapply(strsplit(x = table_raw$new_species_name, split = ii, fixed = TRUE), length) == 2)
  which0 <- which0[!(which0 %in% which0_new)]
  table_raw$new_species_name_i[which0] <- 
    paste0(sapply(strsplit(x = table_raw$new_species_name[which0], split = ii, fixed = TRUE), "[[", 1))
  table_raw$new_species_name_noi[which0] <- 
    paste0(ii, sapply(strsplit(x = table_raw$new_species_name[which0], split = ii, fixed = TRUE), "[[", 2))
  which0_new <- c(which0_new, which0)
  
  # old names
  which0 <- which(sapply(strsplit(x = table_raw$old_species_name, split = ii, fixed = TRUE), length) == 2)
  which0 <- which0[!(which0 %in% which0_old)]
  table_raw$old_species_name_i[which0] <- 
    paste0(sapply(strsplit(x = table_raw$old_species_name[which0], split = ii, fixed = TRUE), "[[", 1))
  table_raw$old_species_name_noi[which0] <- 
    paste0(ii, sapply(strsplit(x = table_raw$old_species_name[which0], split = ii, fixed = TRUE), "[[", 2))
  which0_old <- c(which0_old, which0)
}
table_raw$new_species_name_noi <- trimws(paste0(trimws(table_raw$new_species_name_noi), 
                                                ifelse(is.na(table_raw$new_species_code), "", paste0(" (", table_raw$new_species_code, ")")) ))
table_raw$old_species_name_noi <- trimws(paste0(trimws(table_raw$old_species_name_noi), 
                                                ifelse(is.na(table_raw$old_species_code), "", paste0(" (", table_raw$old_species_code, ")")) ))

# Prepare final table ----------------------------------------------------------
table_print <- table_raw |> 
  flextable::flextable(col_keys = c("dummy_old", "dummy_new", "action", "reason")) |>
  flextable::compose(
    j = "dummy_new", 
    value = flextable::as_paragraph(
      flextable::as_i(new_species_name_i), " ", new_species_name_noi)) |> 
  flextable::compose(
    j = "dummy_old", 
    value = flextable::as_paragraph(
      flextable::as_i(old_species_name_i), " ", old_species_name_noi)) |> 
  flextable::set_header_labels(dummy_new = "New",
                               dummy_old = "Previous",
                               action = "Action",
                               reason = "Reason") |> 
  theme_flextable_nmfstm(pgwidth = full_page_portrait_width) |> 
  flextable::width(width = c(2, 2, 1.5, 1) )

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r tab-species-year, eval = FALSE}
# May only be relevant in the 2023 year
nickname <- "tab-species-year"
header <- paste0("Established species time-series cutoff guidelines for when the time series of some species should begin. These cutoffs were formally established in 2023. ")

table_raw <- gap_products_species_year0 |>
  dplyr::left_join(spp_info |> 
                     dplyr::select(common_name, species_name, species_code)) |> 
  dplyr::arrange(species_code) |> 
  dplyr::mutate(dplyr::across(dplyr::everything(), as.character)) |> 
  dplyr::select(common_name, species_name, year_started)  |> 
  dplyr::mutate(common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name))) )

# separate text to italize and not ---------------------------------------------
table_raw$species_name_noi <- ""
table_raw$species_name_i <- table_raw$species_name
table_raw$species_name <- paste0(table_raw$species_name, " ")
cases <- c(" larvae", " n.", " sp.", " spp.", " egg case", " (", " egg") # , " n."
which00 <- c()
for (ii in cases) {
  which0 <- which(sapply(strsplit(x = table_raw$species_name, split = ii, fixed = TRUE), length) == 2)
  which0 <- which0[!(which0 %in% which00)]
  table_raw$species_name_i[which0] <- 
    paste0(sapply(strsplit(x = table_raw$species_name[which0], split = ii, fixed = TRUE), "[[", 1))
  table_raw$species_name_noi[which0] <- 
    paste0(ii, sapply(strsplit(x = table_raw$species_name[which0], split = ii, fixed = TRUE), "[[", 2))
  which00 <- c(which00, which0)
}

table_raw <- table_raw[order(table_raw$common_name),]
table_raw$species_name <- trimws(table_raw$species_name)
table_raw$species_name_noi <- trimws(table_raw$species_name_noi)

# Prepare final table ----------------------------------------------------------
table_print <- table_raw |> 
  flextable::flextable(col_keys = c("common_name", "dummy", "year_started")) |>
  flextable::compose(
    j = "dummy", 
    value = flextable::as_paragraph(
      flextable::as_i(species_name_i), " ", species_name_noi)) |> 
  flextable::set_header_labels(dummy = "Species Name",
                               common_name = "Common Name",
                               year_started = "First Year") |> 
  theme_flextable_nmfstm(pgwidth = full_page_portrait_width) |> 
  flextable::width(width = c(2.5, 2.5, 1) )

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-diversity-[type]-prep}
dist_plot <- function(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add = 0) {
  
  viridis_palette_option <- "cividis"
  yrs <- sort(yrs, decreasing = TRUE)
  header <- paste0(key_title, " from the ",
                   range_text(yrs), " ", 
                   SURVEY, 
                   " survey", 
                   plural_surveys, ". ")
  
  # prepare data
  table_raw <- diversity
  table_raw$CPUE_KGHA <- unlist(table_raw[,col])
  table_raw <- table_raw  |>
    dplyr::filter(
      srvy %in% srvy1 &
        year %in% yrs) |> 
    dplyr::arrange(desc(year)) |>
    dplyr::mutate(srvy = dplyr::case_when(
      survey_definition_id == 98 ~ "EBS",
      survey_definition_id == 143 ~ "NBS"), 
      YEAR = year, 
      LATITUDE = latitude_dd_start,
      LONGITUDE = longitude_dd_start, 
      CPUE_KGHA <- CPUE_KGHA + set.breaks_add, 
      # CPUE_KGHA = ifelse(is.na(CPUE_KGHA), 0, CPUE_KGHA), 
      COMMON_NAME = "Diversity") |> 
    dplyr::select(srvy, YEAR, LATITUDE, LONGITUDE, COMMON_NAME, CPUE_KGHA) |> 
    dplyr::ungroup() |> 
    data.frame()
  
  for (ii in 1:length(unique(table_raw$YEAR))) {
     # Create shapefile of species IDW ----------------------------------------------
    yr0 <- unique(table_raw$YEAR)[ii]
    
  idw0 <- make_idw_stack(
    x = table_raw |> 
      dplyr::filter(YEAR == yr0),
    # COMMON_NAME = table_raw$COMMON_NAME,
    #                        LATITUDE = table_raw$LATITUDE,
    #                        LONGITUDE = table_raw$LONGITUDE,
    #                        CPUE_KGHA = table_raw$CPUE_KGHA,
    region = reg_dat$region, 
    grouping.vars = "YEAR", 
    set.breaks = set.breaks,
    extrapolation.grid.type = "sf")
  
  idw0$extrapolation.stack$var1.pred <-
    factor(x = idw0$extrapolation.stack$var1.pred, 
           levels = levels(idw0$extrapolation.stack$var1.pred), 
           labels = set.breaks-set.breaks_add,
           ordered = TRUE)
  
    
    gg <- ggplot() +
      ggplot2::geom_sf(data = reg_dat$akland,
                       color = NA,
                       fill = "grey90")  +
      ggplot2::geom_sf(data = reg_dat$graticule,
                       color = "grey80",
                       alpha = 0.2) +
      ggplot2::scale_y_continuous(name = "", #"Latitude",
                                  expand = c(0, 0),
                                  limits = reg_dat$plot.boundary$y,
                                  breaks = reg_dat$lat.breaks) +
      ggplot2::scale_x_continuous(name = "", #"Longitude",
                                  limits = reg_dat$plot.boundary$x,
                                  breaks = reg_dat$lon.breaks) + 
      ggplot2::geom_sf(data = idw0$extrapolation.stack[idw0$extrapolation.stack$YEAR == yr0,],
                       mapping = aes(fill = var1.pred),
                       na.rm = FALSE,
                       show.legend = TRUE, 
                       color = NA) +
      # ggplot2::facet_wrap( ~ YEAR, nrow = row0) + 
      ggplot2::geom_sf(
        data = reg_dat$survey.area, 
        mapping = aes(color = SURVEY, 
                      geometry = geometry), 
        fill = "transparent", 
        linewidth = 1, # ifelse(row0 > 2, 1.5, 1), 
        show.legend = FALSE) +
      ggplot2::scale_color_manual(
        name = " ", 
        values = reg_dat$survey.area$color,
        breaks = reg_dat$survey.areasrvy_long,
        labels = reg_dat$survey.area$srvy) + 
      ggplot2::guides(
        fill = guide_legend(
          order = 1,
          title.position = "top",
          label.position = "bottom",
          title.hjust = 0.5,
          override.aes = list(color = NA),
          nrow = 1),
        color = "none")  +
      ggplot2::coord_sf(expand = FALSE) + # coord_sf() + 
      ggplot2::theme( 
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16, face = "bold"),
        panel.background = element_rect(fill = "white", colour = NA), 
        panel.border = element_rect(fill = NA, colour = "grey20"), 
        axis.text = element_text(size = 12),
        
        strip.background = element_blank(), 
        # strip.text = element_text(size = 20, face = "bold"),
        legend.background = element_rect(colour = "transparent", 
                                         fill = "transparent"),
        legend.key = element_rect(colour = "transparent", 
                                  fill = "transparent"),
        legend.position = "bottom", 
        legend.box = "horizontal",
        legend.box.spacing = unit(0, "pt"), # reduce space between legend & plot
        legend.margin=margin(0, 0, 0, 0) ) # +
    # ggtitle(#label = spp_print, 
    #   subtitle = yr0)
    
    if (set.breaks[1]+set.breaks_add == 0) {
         gg <- gg +
           ggplot2::scale_fill_manual(
        name = paste0(yr0, " ", key_title),
        values =  c("gray90",
                    viridis::viridis(
                      option = viridis_palette_option,
                      direction = -1,
                      n = length(set.breaks)-1,
                      begin = 0.20,
                      end = 0.80)),
        na.translate = FALSE, # Don't use NA
        drop = FALSE) 
    } else {
               gg <- gg +
           ggplot2::scale_fill_manual(
        name = paste0(yr0, " ", key_title),
        values =  c(#"gray90",
                    viridis::viridis(
                      option = viridis_palette_option,
                      direction = -1,
                      n = length(set.breaks), # -1,
                      begin = 0.20,
                      end = 0.80)),
        na.translate = FALSE, # Don't use NA
        drop = FALSE) 
    }
    
    ggsave(filename = paste0(nickname, "-", yr0, '.png'), 
           path = paste0(dir_out_figtab, "gif/"),
           height = height, 
           width = width,
           plot = gg, 
           dpi = 300,
           bg = "white", 
           device = "png") 
    
  }
  
  # prepare animation ----------------------------------------------------------
  img_gif <- sort(list.files(path = paste0(dir_out_figtab, "gif/"), 
                             pattern = paste0(nickname, "-"), 
                             full.names = TRUE) )
  
  img_gif <- lapply(img_gif, 
                    magick::image_read)
  
  img_gif <- lapply(img_gif, 
                    image_resize, 
                    geometry = "1280")
  
  ## join the images together
  img_gif <- magick::image_join(img_gif)
  
  ## animate at 2 frames per second
  figure_print <- magick::image_animate(img_gif, 
                                        fps = 2)
  
  ## view animated image
  # figure_print
  
  ## save to disk
  magick::image_write(
    image = figure_print, 
    path = paste0(paste0(dir_out_figtab, "gif/"), nickname, ".gif") )

return(list("figure_print" = figure_print, 
            "header" = header, 
            "height" = height, 
            "width" = width, 
            "nickname" = nickname))
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```

```{r fig-diversity-shannon-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-shannon-gif")
report_title0 <- "gif"
col <- "shannon"
key_title <- 'Shannon Diversity Index'
set.breaks <- c(0,1,2,3,4)
# set.breaks <- c(0,.5,1,1.5,2,2.5,3,3.5) # c(0,1,2,3,4)

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-diversity-simpson-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-simpson-gif")
report_title0 <- "gif"
col <- "simpson"
key_title <- "Simpson's Diversity Index"
set.breaks <- c(0,5,10, 15, 20)
# set.breaks <- c(0,2.5,5,7.5,10, 12.5, 15, 18.5)

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-diversity-shannon-z-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-shannon-z-gif")
report_title0 <- "gif"
col <- "shannon_z"
key_title <- 'Shannon Diversity Index (z-score)'
set.breaks <- c(floor(min(diversity$shannon_z, na.rm = TRUE)):ceiling(max(diversity$shannon_z, na.rm = TRUE)))
set.breaks_add <- (min(set.breaks)*-1)+.1
set.breaks <- set.breaks + set.breaks_add

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-diversity-simpson-z-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-simpson-z-gif")
report_title0 <- "gif"
col <- "simpson_z"
key_title <- "Simpson's Diversity Index (z-score)"
set.breaks <- c(floor(min(diversity$simpson_z, na.rm = TRUE)):ceiling(max(diversity$simpson_z, na.rm = TRUE)))
set.breaks_add <- (min(set.breaks)*-1)+.1
set.breaks <- set.breaks + set.breaks_add

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r tab-participants}
nickname <- "tab-participants" 
places <- readxl::read_excel(path = paste0(dir_out_rawdata, "/special-projects.xlsx"), 
                             sheet = "affiliations", 
                             skip = 1)

table_raw0 <- readxl::read_excel(path = paste0(dir_out_rawdata, "/special-projects.xlsx"), 
                                 sheet = "participants", 
                                 skip = 1)  |> 
  dplyr::filter(year == maxyr) |> 
  dplyr::left_join(places |> dplyr::rename(affiliation = combined))  |>
  dplyr::arrange(Agency) |>
  dplyr::left_join(
    y = data.frame(srvy = c(srvy1, "EBS & NBS"), 
                   srvy_long = c(stringr::str_to_title(srvy11), 
                                 "Eastern and northern Bering Sea"))) |> # " Combined"
  dplyr::left_join(places) |> 
  dplyr::mutate(
    key = paste0(vessel, "-", leg), 
    srvy = gsub(pattern = "&", x = srvy, replacement = "and"),
    srvy = factor(x = srvy, 
                  levels = c("EBS and NBS", "EBS", "NBS"), 
                  labels = c("EBS and NBS", "EBS", "NBS"), 
                  ordered = TRUE), 
    srvy_long = factor(x = srvy_long, 
                       levels = c("Eastern and northern Bering Sea", # " Combined"
                                  "Eastern Bering Sea", "Northern Bering Sea"), 
                       labels = c("Eastern and northern Bering Sea", # " Combined"
                                  "Eastern Bering Sea", "Northern Bering Sea"), 
                       ordered = TRUE) , 
    order = dplyr::case_when(
      role == "Field Party Chief" ~ 1,
      role == "Deck Lead" ~ 2,
      role == "Crab Lead" ~ 3,
      role == "Crab Assist" ~ 4,
      role == "General Biologist" ~ 5,
      role == "IPHC Secretariat" ~ 6,
      role == "Stomach Collector" ~ 7),
    col_title = paste0("Leg ", leg, ": ", srvy, "\n", 
                       date_formatter(date = date_start, date_format = "%B %d"), 
                       " -\n", 
                       date_formatter(date = date_end, date_format = "%B %d")), 
    affiliation = ifelse(is.na(affiliation), "-", affiliation), 
    footorder = as.numeric(factor(x = affiliation, 
                                  labels = unique(affiliation),
                                  levels = unique(affiliation),
                                  ordered = TRUE))) |>
  dplyr::arrange(key) |>
  dplyr::arrange(order)

table_raw <- table_raw0 |>
  tidyr::pivot_wider(id_cols = role, names_from = key, values_from = name) 

table_raw_footnotes_1 <- table_raw0 |>
  tidyr::pivot_wider(id_cols = role, names_from = key, values_from = footorder) 

header <- paste0("Survey participants on the ", maxyr, " ", text_list(haul_cruises_maxyr$srvy_long), 
                 " shelf survey. ")

aa <- table_raw0 |> 
  dplyr::select(key, vessel, col_title) |> 
  unique() 

table_print <- table_raw |>
  flextable::flextable() |> 
  flextable::delete_part(part = "header") |> 
  flextable::add_header_row(top = TRUE, values = c("", aa$vessel)) |>
  flextable::merge_h(part = "header") |>
  flextable::add_header_row(top = FALSE, values = c("", aa$col_title)) |>
  flextable::bold(j = 1) |>
  theme_flextable_nmfstm(row_lines = TRUE, 
                         pgwidth = full_page_landscape_width)  |>
  flextable::italic(i = 2, part = "header") |>
  flextable::bold(i = 2, part = "header", bold = FALSE) |>
  flextable::vline(j = 5, part = "all") |> 
  flextable::width(width = rep_len(x = full_page_landscape_width/ncol(table_raw), length.out = ncol(table_raw)))

for (i in sort(unique(table_raw0$footorder[table_raw0$affiliation != "-"]))) {
  
  temp1 <- table_raw0 |>
    dplyr::filter(footorder == i) |>
    dplyr::select(affiliation, footorder) |> 
    dplyr::slice(1)
  
  temp <- which(table_raw_footnotes_1 == i, arr.ind = TRUE) |> data.frame()
  
  table_print <- table_print |> 
    flextable::footnote(
      i = temp$row,  # Rows where the footnote applies
      j = temp$col,  # Columns where the footnote applies
      value = as_paragraph(temp1$affiliation),
      ref_symbols = as.character(i),
      part = "body") |> 
    flextable::fontsize(size = 8, part = "footnote")
}

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```



