```{r tab-species-composition, eval = (srvy == "NEBS")}
nickname <- "tab-species-composition" 
height <- full_page_portrait_height # 7
width <- full_page_portrait_width # 6.5
header <- paste0("List of fish taxa only encountered in the ",
                 paste0(haul_cruises_maxyr$srvy_long, collapse = " or "#, 
                        # " (", paste0(haul_cruises_maxyr$srvy, ")")
                 ),
                 " in ", maxyr, " survey catches. ")

# Select data and make plot
table_raw <- catch_haul_cruises_maxyr |> 
  dplyr::select(species_code, srvy) |> 
  dplyr::mutate(occured = TRUE) |>
  dplyr::distinct() |>
  tidyr::pivot_wider(id_cols = species_code,
                     names_from = srvy, 
                     values_from = occured, 
                     values_fill = FALSE) |> 
  dplyr::mutate(where = dplyr::case_when(
    (EBS & NBS) ~ "both", 
    (EBS & !NBS) ~ "ebs", 
    (NBS & !EBS) ~ "nbs")) |> 
  dplyr::left_join(
    spp_info |> 
      dplyr::select(species_code, 
                    common_name, 
                    taxon, 
                    species_name_ital, 
                    species_name_noital) |> 
      dplyr::distinct()) |>
  dplyr::filter(taxon == "fish" & 
                  !grepl(x = common_name, pattern = " unid.", fixed = TRUE) &
                  !grepl(x = common_name, pattern = " egg", fixed = TRUE) & 
                  !is.na(common_name)) |> 
  dplyr::mutate(species_name_ital = ifelse(species_name_ital == "", NA, species_name_ital), 
                species_name_noital = ifelse(species_name_noital == "", NA, species_name_noital) ) |>
  dplyr::distinct() |> 
  dplyr::arrange(common_name) |> 
  dplyr::mutate(common_name = paste0(toupper(substr(common_name, start = 1, stop = 1)), substr(common_name, start = 2, stop = nchar(common_name))))

temp_ebs <- table_raw |> 
  dplyr::filter(where == "ebs")

temp_nbs <- table_raw |> 
  dplyr::filter(where == "nbs")

names(temp_nbs) <- paste0(names(temp_nbs), "_")

# make the same length so they can be bound together
if (nrow(temp_ebs)>nrow(temp_nbs)) {
  temp_nbs <- dplyr::bind_rows(
    temp_nbs, 
    data.frame(common_name_ = rep_len(NA, (nrow(temp_ebs)-nrow(temp_nbs)) ) ) )
} else  if (nrow(temp_nbs)>nrow(temp_ebs)) {
  temp_ebs <- dplyr::bind_rows(
    temp_ebs, 
    data.frame(common_name = rep_len(NA, (nrow(temp_nbs)-nrow(temp_ebs)) ) ) )
}

temp0 <- dplyr::bind_cols(temp_ebs, temp_nbs) |> 
  dplyr::select(-where, -NBS, -EBS) 


table_print <- flextable::flextable(
  data = temp0,
  col_keys = c("dummy_ebs","dummy_nbs"))  |>
  flextable::compose(
    j = "dummy_nbs", part = "body",
    value = as_paragraph(
      # common name and first ( if there are sci names
      as_chunk(paste0(ifelse(is.na(common_name_), "", common_name_), 
                      ifelse((!is.na(species_name_ital_) | !is.na(species_name_noital_)), " (", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)), 
      # italic sci name
      as_chunk(ifelse(!is.na(species_name_ital_), species_name_ital_, ""),
               props = fp_text_default(italic = TRUE, font.size = font_size0, font.family = font0)), 
      # non-italic sci name and/or )
      as_chunk(paste0(ifelse((!is.na(species_name_ital_) & !is.na(species_name_noital_)), " ", ""),
                      ifelse(!is.na(species_name_noital_), species_name_noital_, ""),
                      ifelse((!is.na(species_name_ital_) | !is.na(species_name_noital_)), ")", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)))) |>  
  flextable::compose(
    j = "dummy_ebs", part = "body",
    value = as_paragraph(
      # common name and first ( if there are sci names
      as_chunk(paste0(ifelse(is.na(common_name), "", common_name), 
                      ifelse((!is.na(species_name_ital) | !is.na(species_name_noital)), " (", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)), 
      # italic sci name
      as_chunk(ifelse(!is.na(species_name_ital), species_name_ital, ""),
               props = fp_text_default(italic = TRUE, font.size = font_size0, font.family = font0)), 
      # non-italic sci name and/or )
      as_chunk(paste0(ifelse((!is.na(species_name_ital) & !is.na(species_name_noital)), " ", ""),
                      ifelse(!is.na(species_name_noital), species_name_noital, ""),
                      ifelse((!is.na(species_name_ital) | !is.na(species_name_noital)), ")", "")),
               props = fp_text_default(bold = FALSE, font.size = font_size0, font.family = font0)))) |> 
  flextable::compose(i = 1, j = "dummy_ebs", part = "header",
                     as_paragraph("Only Encountered in Eastern Bering Sea\nCommon name ",
                                  as_chunk(paste0("(scientific name)"),
                                           props = fp_text_default(italic = TRUE, bold = TRUE, font.family = font0)))) |>
  flextable::compose(i = 1, j = "dummy_nbs", part = "header",
                     as_paragraph("Only Encountered in Northern Bering Sea\nCommon name ", 
                                  as_chunk(paste0("(scientific name)"),
                                           props = fp_text_default(italic = TRUE, bold = TRUE, font.family = font0)))) |>  
  theme_flextable_nmfstm(row_lines = FALSE, 
                         pgwidth = full_page_portrait_width) |>
  flextable::width(width = c(full_page_portrait_width/2, full_page_portrait_width/2), unit = "in") |> 
  flextable::vline(j = "dummy_ebs", part = "all") |> 
  flextable::valign(valign = "top", part = "body")

res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

# Diversity

```{r fig-diversity-[type]-prep}
dist_plot <- function(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add = 0) {
  
  viridis_palette_option <- "cividis"
  yrs <- sort(yrs, decreasing = TRUE)
  header <- paste0(key_title, " from the ",
                   range_text(yrs), " ", 
                   SURVEY, 
                   " survey", 
                   plural_surveys, ". ")
  
  # prepare data
  table_raw <- diversity
  table_raw$CPUE_KGHA <- unlist(table_raw[,col])
  table_raw <- table_raw  |>
    dplyr::filter(
      srvy %in% srvy1 &
        year %in% yrs) |> 
    dplyr::arrange(desc(year)) |>
    dplyr::mutate(srvy = dplyr::case_when(
      survey_definition_id == 98 ~ "EBS",
      survey_definition_id == 143 ~ "NBS"), 
      YEAR = year, 
      LATITUDE = latitude_dd_start,
      LONGITUDE = longitude_dd_start, 
      CPUE_KGHA <- CPUE_KGHA + set.breaks_add, 
      # CPUE_KGHA = ifelse(is.na(CPUE_KGHA), 0, CPUE_KGHA), 
      COMMON_NAME = "Diversity") |> 
    dplyr::select(srvy, YEAR, LATITUDE, LONGITUDE, COMMON_NAME, CPUE_KGHA) |> 
    dplyr::ungroup() |> 
    data.frame()
  
  for (ii in 1:length(unique(table_raw$YEAR))) {
    # Create shapefile of species IDW ----------------------------------------------
    yr0 <- unique(table_raw$YEAR)[ii]
    
    idw0 <- make_idw_stack(
      x = table_raw |> 
        dplyr::filter(YEAR == yr0),
      # COMMON_NAME = table_raw$COMMON_NAME,
      #                        LATITUDE = table_raw$LATITUDE,
      #                        LONGITUDE = table_raw$LONGITUDE,
      #                        CPUE_KGHA = table_raw$CPUE_KGHA,
      region = reg_dat$region, 
      grouping.vars = "YEAR", 
      set.breaks = set.breaks,
      extrapolation.grid.type = "sf")
    
    idw0$extrapolation.stack$var1.pred <-
      factor(x = idw0$extrapolation.stack$var1.pred, 
             levels = levels(idw0$extrapolation.stack$var1.pred), 
             labels = set.breaks-set.breaks_add,
             ordered = TRUE)
    
    
    gg <- ggplot() +
      ggplot2::geom_sf(data = reg_dat$akland,
                       color = NA,
                       fill = "grey70")  +
      ggplot2::geom_sf(data = reg_dat$graticule,
                       color = "grey80",
                       alpha = 0.2) +
      ggplot2::scale_y_continuous(name = "", #"Latitude",
                                  expand = c(0, 0),
                                  limits = reg_dat$plot.boundary$y,
                                  breaks = reg_dat$lat.breaks) +
      ggplot2::scale_x_continuous(name = "", #"Longitude",
                                  limits = reg_dat$plot.boundary$x,
                                  breaks = reg_dat$lon.breaks) + 
      ggplot2::geom_sf(data = idw0$extrapolation.stack[idw0$extrapolation.stack$YEAR == yr0,],
                       mapping = aes(fill = var1.pred),
                       na.rm = FALSE,
                       show.legend = TRUE, 
                       color = NA) +
      # ggplot2::facet_wrap( ~ YEAR, nrow = row0) + 
      ggplot2::geom_sf(
        data = reg_dat$survey.area, 
        mapping = aes(color = SURVEY, 
                      geometry = geometry), 
        fill = "transparent", 
        linewidth = 1, # ifelse(row0 > 2, 1.5, 1), 
        show.legend = FALSE) +
      ggplot2::scale_color_manual(
        name = " ", 
        values = reg_dat$survey.area$color,
        breaks = reg_dat$survey.areasrvy_long,
        labels = reg_dat$survey.area$srvy) + 
      ggplot2::guides(
        fill = guide_legend(
          order = 1,
          title.position = "top",
          label.position = "bottom",
          title.hjust = 0.5,
          override.aes = list(color = NA),
          nrow = 1),
        color = "none")  +
      ggplot2::coord_sf(expand = FALSE) + # coord_sf() + 
      ggplot2::theme( 
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16, face = "bold"),
        panel.background = element_rect(fill = "white", colour = NA), 
        panel.border = element_rect(fill = NA, colour = "grey20"), 
        axis.text = element_text(size = 12),
        
        strip.background = element_blank(), 
        # strip.text = element_text(size = 20, face = "bold"),
        legend.background = element_rect(colour = "transparent", 
                                         fill = "transparent"),
        legend.key = element_rect(colour = "transparent", 
                                  fill = "transparent"),
        legend.position = "bottom", 
        legend.box = "horizontal",
        legend.box.spacing = unit(0, "pt"), # reduce space between legend & plot
        legend.margin=margin(0, 0, 0, 0) ) # +
    # ggtitle(#label = spp_print, 
    #   subtitle = yr0)
    
    if (set.breaks[1]+set.breaks_add == 0) {
      gg <- gg +
        ggplot2::scale_fill_manual(
          name = paste0(yr0, " ", key_title),
          values =  c("gray90",
                      viridis::viridis(
                        option = viridis_palette_option,
                        direction = -1,
                        n = length(set.breaks)-1,
                        begin = 0.20,
                        end = 0.80)),
          na.translate = FALSE, # Don't use NA
          drop = FALSE) 
    } else {
      gg <- gg +
        ggplot2::scale_fill_manual(
          name = paste0(yr0, " ", key_title),
          values =  c(#"gray90",
            viridis::viridis(
              option = viridis_palette_option,
              direction = -1,
              n = length(set.breaks), # -1,
              begin = 0.20,
              end = 0.80)),
          na.translate = FALSE, # Don't use NA
          drop = FALSE) 
    }
    
    ggsave(filename = paste0(nickname, "-", yr0, '.png'), 
           path = paste0(dir_out_figtab, "gif/"),
           height = height, 
           width = width,
           plot = gg, 
           dpi = 300,
           bg = "white", 
           device = "png") 
    
  }
  
  # prepare animation ----------------------------------------------------------
  img_gif <- sort(list.files(path = paste0(dir_out_figtab, "gif/"), 
                             pattern = paste0(nickname, "-"), 
                             full.names = TRUE) )
  
  img_gif <- lapply(img_gif, 
                    magick::image_read)
  
  img_gif <- lapply(img_gif, 
                    image_resize, 
                    geometry = "1280")
  
  ## join the images together
  img_gif <- magick::image_join(img_gif)
  
  ## animate at 2 frames per second
  figure_print <- magick::image_animate(img_gif, 
                                        fps = 2)
  
  ## view animated image
  # figure_print
  
  ## save to disk
  magick::image_write(
    image = figure_print, 
    path = paste0(paste0(dir_out_figtab, "gif/"), nickname, ".gif") )
  
  return(list("figure_print" = figure_print, 
              "header" = header, 
              "height" = height, 
              "width" = width, 
              "nickname" = nickname))
  # res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
}
```



```{r fig-diversity-shannon-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-shannon-gif")
report_title0 <- "gif"
col <- "shannon"
key_title <- 'Shannon Diversity Index'
set.breaks <- c(0,1,2,3,4)
# set.breaks <- c(0,.5,1,1.5,2,2.5,3,3.5) # c(0,1,2,3,4)

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-diversity-simpson-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-simpson-gif")
report_title0 <- "gif"
col <- "simpson"
key_title <- "Simpson's Diversity Index"
set.breaks <- c(0,5,10, 15, 20)
# set.breaks <- c(0,2.5,5,7.5,10, 12.5, 15, 18.5)

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```


```{r fig-diversity-shannon-z-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-shannon-z-gif")
report_title0 <- "gif"
col <- "shannon_z"
key_title <- 'Shannon Diversity Index (z-score)'
set.breaks <- c(floor(min(diversity$shannon_z, na.rm = TRUE)):ceiling(max(diversity$shannon_z, na.rm = TRUE)))
set.breaks_add <- (min(set.breaks)*-1)+.1
set.breaks <- set.breaks + set.breaks_add

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

```{r fig-diversity-simpson-z-gif, eval = FALSE}
yrs <- sort(unique(diversity$year))

width <- full_page_portrait_width # 6.5  
height <- full_page_portrait_height # + ifelse(srvy == "EBS", 0, - 1)
nickname <- paste0("fig-diversity-simpson-z-gif")
report_title0 <- "gif"
col <- "simpson_z"
key_title <- "Simpson's Diversity Index (z-score)"
set.breaks <- c(floor(min(diversity$simpson_z, na.rm = TRUE)):ceiling(max(diversity$simpson_z, na.rm = TRUE)))
set.breaks_add <- (min(set.breaks)*-1)+.1
set.breaks <- set.breaks + set.breaks_add

temp <- dist_plot(yrs, height, nickname, report_title0, col, key_title, set.breaks, set.breaks_add)
for (jjj in 1:length(temp)) { assign(names(temp)[jjj], temp[[jjj]]) }
# res <- knitr::knit_child(text = knitr::knit_expand( file = paste0(dir_code, "_child_save_figtab.Rmd")), quiet = TRUE)
```

