---
title: ""
author: ""
date: ""
output: 
   word_document:
     df_print: kable
     reference_docx: word-styles-reference.docx
---

### Abstract

From June to July `r maxyr`, the National Marine Fisheries Service’s Alaska Fisheries Science Center Resource Assessment and Conservation Engineering Division conducted its `r yrofsurvey ``r stndth` annual `r SURVEY` (`r survey`) continental shelf bottom trawl survey of groundfish and invertebrate fauna. The standard study area encompasses a major portion of the `r SURVEY` shelf (depths between `r min(dat$BOT_DEPTH[dat$YEAR %in% maxyr])` and `r max(dat$BOT_DEPTH[dat$YEAR %in% maxyr])` m) from the Alaska Peninsula north to approximately the latitude of St. Matthew Island (60º 50' N). In addition, a rapid response survey of a portion of the Northern Bering Sea (NBS) was conducted in response to warmer than average seafloor water temperatures and changes in historical fish and invertebrate distribution patterns observed during the EBS survey. Two stern trawlers, the `r funct_list(paste0(unique(dat$VESSEL_M[dat$YEAR %in% maxyr]), "-m ", unique(dat$VESSEL_NAME[dat$YEAR %in% maxyr])))`, were chartered for sampling during the `r survey` surveys. Demersal populations of fishes and invertebrates were sampled by trawling for 30 minutes at 37.04 × 37.04 km (20 × 20 nmi) stations centered within a stratified systematic grid consisting of a total of `r length(unique(dat$STATION))` stations in the `r survey` survey. At each station, species composition of the catch was determined, and length distributions and age structure samples were collected from ecologically and commercially important species. All survey stations were sampled successfully in the EBS. 

> removed NBS

> How do I know if all stations were sampled successfully? Data-wise?

For the fifth consecutive year, average surface (7.6°C) and bottom (4.2 °C) water temperatures for the EBS shelf were well above the long-term means from 1982 to 2018 for the surface (6.6°C) and for the bottom (2.5°C). In the EBS and NBS, there were a total of `r paste0("___")` species representing `r paste0("___")` families and `r paste0("___")` genera, as well as `r paste0("___")` invertebrate taxa representing `r paste0("___")` phyla, identified in the catches.


Survey results presented herein include abundance estimates for fishes and invertebrates, geographic distributions and abundance-at-length of the more common fish species, and summary surface and bottom temperature data during the summer survey period. Appendices provide station data, summarized catch data by station, species listings, and detailed analyses of abundance and biological data of the sampled populations.
