---
title: ""
author: ""
date: ""
output: 
   word_document:
     df_print: kable
     reference_docx: word-styles-reference.docx
---

### Introduction

In `r maxyr`, the National Marine Fisheries Service’s (NMFS) Resource Assessment and Conservation Engineering (RACE) Division of the Alaska Fisheries Science Center (AFSC) conducted two contiguous bottom trawl surveys on the Bering Sea continental shelf: the 2018 “Eastern Bering Sea” (EBS) survey was the `r yrofsurvey ``r stndth` in an annual time series that began in 1982 (Conner and Lauth 2017), and the 2018 “Northern Bering Sea Rapid Response” (NBS) survey was conducted for the first time in response to warmer than average seafloor water temperatures and changes in historical fish and invertebrate distribution patterns observed during the EBS survey (Lauth 2011) The NBS standardized 20 x 20 nautical mile (nmi) sampling grid and survey station plan implemented in 2010 and 2017 was reduced in scope and resolution for `r maxyr` to a 30 x 30 nmi grid and the survey extent was reduced by eliminating sampling in Norton Sound and near the Alaska coastline from near Nome, AK south towards Nunivak Island, AK. (Figure 1). The modified station grid resulted in 49 northern Bering Sea stations for sampling in 2018. The NBS is a region of critical importance for increased scientific monitoring because it is a transitional zone between the EBS and Arctic Ocean that is transforming with the changing climate (Sigler et al. `r 2013?`). In this document, we provide snapshots of survey results from 2018 for the EBS and rapid response NBS and compare EBS results with those from previous years.



