---
title: ""
author: ""
date: ""
output: 
   word_document:
     df_print: kable
     reference_docx: word-styles-reference.docx
---

### History of Bering Sea Bottom Trawl Surveys

The involvement of the U.S. government in Bering Sea BT surveys dates back to the 1940’s when effort was engaged primarily in exploratory work for commercial fisheries resources (Zimmermann et al. 2009). Early efforts led to the development of a valuable single-species fishery in Alaska for red king crab (Paralithodes camtschaticus), and continued U.S. BT surveys into the 1970’s focused on cooperative arrangements with private industry to study the biology, distribution, abundance, and best fishing practices for red king crab (Zimmermann 
et al. 2009). 

The first large-scale systematic survey of the EBS shelf was conducted in 1975 under contract from the U.S. Bureau of Land Management to collect baseline data for assessing the potential impact of the growth in the offshore oil industry on the development of Bering Sea groundfish and crab fishery resources (Pereyra et al. 1976). During the 1975 baseline survey, sampling was conducted over the EBS shelf between the 20-m and 200-m isobaths from the Alaska Peninsula north to approximately 62N. In 1979, a more comprehensive survey of the Bering Sea shelf was undertaken in cooperation with the Japan Fisheries Agency (Bakkala and Wakabayashi 1985). That survey encompassed the entire region sampled in the 1975 baseline study plus the upper continental slope waters and part of the NBS shelf. A hydroacoustic survey was also initiated in 1979 to assess the midwater component of the walleye pollock population. 

Following the expansive 1979 effort, annual BT surveys continued in the EBS shelf, and a triennial survey was initiated combining the upper continental slope and different parts of the NBS shelf. The spatio-temporal scale, trawl gear and sampling methods of the EBS shelf survey lacked consistency until 1982 when they were all standardized to include 356 stations (Bakkala 1993). Beginning in 1987, survey coverage of the EBS shelf was expanded northwest to include 20 more stations along the U.S.-Russian Maritime Boundary (Strata 82 and 90; Figure 2). 

The triennial surveys of the NBS and EBS slope were discontinued after 1991 due to lack of funding; however, starting in 2000, the slope BT survey resumed on a biennial basis as a new time series using standard AFSC gear and methods (Stauffer 2004, Hoff and Britt 2011). In 2010 and 2017, the EBS shelf survey grid was extended into the NBS (Lauth 2011). The 2018 survey extension into the NBS did not employ the same sampling design as 2010 and 2017, and therefore the survey results from the 2018 rapid response NBS survey cannot be compared to the results from the 2010 and 2017 NBS surveys.
