---
output:
  word_document:
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: word-styles-reference.docx
csl: "../citationStyles/citationstyle.csl"
bibliography: "../data/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE)
counter.inside<-0
```


### Results and Discussion

All 376 of the `r SRVY ` stations and 49 rapid response NBS stations were successfully sampled in `r maxyr` (Figure 2). Summarized haul and raw catch sample data for successfully trawled stations used in the analyses are listed in Appendix A by vessel along with date, time, start and end positions, mean bottom depth, tow duration, distance fished over ground, mean net width, and trawl performance.	

#### Ocean Conditions

Sea surface temperatures recorded during the survey ranged from 4.5° to 13.7° (Figure 4). Surface temperatures were warmest in the northwest region of the survey area. Near-bottom temperatures (measured as the temperature at the depth of the headrope while the trawl was on-bottom) ranged from 0.7°C to 9.6°C (Figure 5), with warmer near-bottom temperatures (> 3.0°C) occurring throughout a majority of the southern extent of the survey area, ranging to approximately 90 nmi north of the Pribilof Islands, approximately 60 nmi west of Nunivak Island and following the coastline north to the Anadyr Strait.

The 2018 mean surface temperature was 7.6°C, which was 0.3°C lower than 2017 and 1°C above the time-series mean (6.6°C). The mean bottom temperature was 4.2°C, which was 1.3°C higher than 2017 and 1.6°C above the time-series mean (2.5°C) (Figure 6).
During the last 16 years, 2006 – 2013 (Fig. 6a) were colder than average (“cold stanza”), and 2002 – 2005 and 2014 – 2017 (Fig. 6b) were warmer than average (“warm stanza”). The highly variable survey bottom temperatures in the `r SRVY ` shelf are related to the area occupied by the summer cold pool (Fig. 7), defined by the extent of bottom temperatures below 2° C. Over the period of the 36-year time series, the areal coverage of the summer survey cold pool varied in size from 48,000 to 394,000 km2, occupying from 10% to 80% of `r SRVY ` shelf area (Fig. 7). 

The size of the cold pool each summer depends on sea ice coverage from the previous winter, the timing of its retreat during the spring and early summer as well as other oceanographic and meteorological conditions [@RN941]. During the coldest years, sea ice extended farther south and lasted later into spring resulting in cold pools that extended farther south down the middle domain into Bristol Bay and near the Alaska Peninsula (Fig. 6a). Interannual variability in the dynamics of seasonal ice is a major environmental driver on the Bering Sea shelf (Stabeno et al. 2001, 2012a, b) that can change recruitment and migration patterns and cause major distributional shifts in groundfishes and crabs [@RN905; @RN913; @RN977]. The 2018 cold pool occupied the smallest percentage of the `r SRVY ` shelf in the survey’s 37 year time series and was confined to a small area of the upper middle shelf (50 -100 m depth) north of latitude 61° N (Figure 5). 

#### Survey Data and Specimen Collections 

From the combined `r SRVY ` (Tables 2a) and NBS Rapid Response (Table 2b) trawl surveys, a total of 293,154 individual length measurements representing 45 taxa were collected. Additional collections (see Table 3 for list of projects) included 8,038 age structures (otoliths) from 11 fish taxa, 7,969 stomach samples from 4 fish taxa, and 1,279 pathobiology (blood) samples from two different crab taxa.

#### Species Composition

A total of 114 fish species representing 20 families and 65 genera were identified in the survey catches from both the `r SRVY ` and NBS (Appendix B, Table 6). The `r SRVY ` had a total of 93 fish species, 49 of which did not occur in the NBS. In comparison, the NBS had 70 total fish species (in 15 families), 12 of which did not occur in the `r SRVY ` (Table 4). Seven of the 12 species only occurring in the NBS (Table 4) have only been documented north of 60°N (Mecklenburg et al. 2002). Six flatfish species that were present in the `r SRVY ` were absent from the NBS including English sole (Parophrys vetulus), dover sole (Microstomus pacificus), butter sole (Isopsetta isolepis), rex sole (Glyptocephalus zachirus), hybrid starry flounder X Alaska plaice (Platichthys stellatus X Pleuronectes quadrituberculatus) and southern rock sole (Table 4).

#### Relative Abundance

The top 12 fish taxa in the `r SRVY ` accounted for 73% (243 kg/ha) of total catch CPUE (335 kg/ha) and 97% of total fish CPUE (252 kg/ha), compared with the NBS where the top 12 fish taxa accounted for only 61% (140 kg/ha) of the total catch CPUE (228 kg/ha) and 98% of total fish CPUE (143 kg/ha). 

The lower fish biomass in the NBS is consistent with results of a broader analysis of all survey years showing decreasing fish biomass with increasing latitude on the Bering Sea continental shelf (Stevenson and Lauth 2012). The relative abundance of flatfishes and gadids were high in both the `r SRVY ` and NBS, but the species comprising each taxonomic group and their proportion of the total biomass were different between the two areas. In the `r SRVY `, there were 15 different flatfish species that together comprised almost half of the total fish biomass (48%) with yellowfin sole (22%) and northern rock sole (11%) having the greatest proportions. This contrasted with the NBS where there were twelve flatfish species with yellowfin sole (15%) and Alaska plaice (12%) making up a majority of the total fish biomass. Four flatfish species that were present in the `r SRVY ` were absent from catches in the NBS including arrowtooth flounder, butter sole (*Isopsetta isolepis*), rex sole (*Glyptocephalus zachirus*) and southern rock sole (Table 4). One flatfish species, the Arctic flounder (Liopsetta glacialis), was only present in the NBS.
	
Walleye pollock and Pacific cod together comprised 44% of the total fish biomass in the `r SRVY ` compared to only 57% in the NBS. The abundance of walleye pollock was relatively high in the `r SRVY ` middle and outer shelf compared to the inner shelf and in the NBS where bottom depths are generally less than 50 m (Figure 7). Unlike the `r SRVY `, saffron cod (*Eleginus gracilis*), was among the 12 most abundant fish species in the NBS, and Arctic cod (Boreogadus saida) was the 18th most abundant. For a descending rank of all organisms caught in each area, see Appendix B1 ( `r SRVY `) and Appendix B2 (NBS).


#### Biomass, Abundance, Distribution, CPUE, and Size Composition of Principal Species and Species Groups

Total demersal animal biomass for the `r SRVY ` was estimated at 16.5 million metric tons (t) and for the NBS at 4.6 million t. In the `r SRVY `, the proportion of fishes (75%; Table 5a) was three times higher than invertebrates (25%; Table 5b). This trend was similarly true in the NBS where the proportion of fishes (63%; Table 6a) was greater than invertebrates (37%; Table 6b). Pleuronectids dominated the fish biomass in both the `r SRVY ` (6.0 million t) and NBS (0.9 million t), and gadids were the second most abundant fish group in both areas. Walleye pollock were the most abundant gadid in both the `r SRVY ` and NBS (Table 5a and 6a). Echinoderms and crustaceans were the major invertebrate taxa comprising 16% of the total animal biomass in the `r SRVY ` (Table 5b) and 25% in the NBS (Table 6b).

Survey results for major fish fauna are presented in maps of geographic distribution and abundance, plots of total abundance-at-size, and tables with estimates of biomass and population number. Major species presented include walleye pollock (Figures 7-8 and Table 7a, b), Pacific cod (Figures 9-10 and Table 8a, b), yellowfin sole (Figures 11-12 and Table 9a, b), northern rock sole (Figures 13-14 and Table 10a, b), flathead sole (Figures 15-16 and Table 11a, b), Bering flounder (Figures 17-18 and Table 12a, b), Alaska plaice (Figures 19-20 and Table 13a, b), Greenland turbot (Figures 21-22 and Table 14a, b), arrowtooth flounder (Figures 23-24 and Table 15a, b), Kamchatka flounder (Figures 25-26 and Table 16a, b), and Pacific halibut (Figures 27-28 and Table 17a, b). Mean CPUE by weight and number and maps of geographic distribution for many other species are also included (Tables 18-19, Figures 29-61). Appendix D contains population estimates by sex and size class for all 11 of these fish species. 


#### Summary of Results for Selected Major Eastern and Northern Bering Sea Fish Fauna


