---
output:
  word_document:
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: word-styles-reference.docx
csl: "../citationStyles/citationstyle.csl"
bibliography: "../data/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

### `r spp.common` (*`r spp.sci`*)


```{r}
# find basic info about species
dat.maxyr.spp<-dat.maxyr[toupper(dat.maxyr$COMMON) %in% toupper(spp.common),]

cols<-c("LATITUDE", "LONGITUDE", 
        "WTCPUE", "NUMCPUE", 
        "BOT_DEPTH", "BOT_TEMP", "SURF_TEMP")
COLS<-c("latitude", "longitude", 
        "CPUE Weight", "CPUE Abundance", 
        "Bottom Depth", "Bottom Temperature", "Surface Temperature")

basiccontent<-c()

for (ii in 1:length(cols)) {
  basiccontent<-c(basiccontent, 
                  paste0(" - Minimum ", COLS[ii],": ", min(dat.maxyr.spp[cols[ii]]), "
                  
                          - Maximum ", COLS[ii],": ", max(dat.maxyr.spp[cols[ii]]), "
                          
                          "))
}


```


`r basiccontent `


```{r}

out.new<-paste0(dir.output.todaysrun, "/rawdata/", SRVY, "-", tolower(spp.common), ".zip")

temp <- tempfile(fileext = ".zip")
dl <- drive_download(file = paste0(SRVY, "-", tolower(spp.common)), 
  path = temp, overwrite = TRUE)

out <- unzip(temp, exdir = tempdir())

file.rename(from = out,
            to = out.new)

spp.content<-htmlTreeParse(out.new, useInternal = TRUE)

spp.content <- xpathApply(spp.content, "//body//text()[not(ancestor::script)][not(ancestor::style)][not(ancestor::noscript)]", xmlValue)

spp.content <- cat(unlist(spp.content))

```


`r spp.content `


```{r fig.width=8, fig.height = 6, fig.cap=paste0("Figure 1. -- Sampling grid and station identifiers for the ", maxyr, " eastern and northern Bering Sea continental shelf bottom trawl surveys.")}

# S`r SRVY ` <- get_base_layers(select.region = "bs.south", set.crs = "auto")
# # class(S`r SRVY `)
# # names(S`r SRVY `)
# 
# temp<-dat[dat$YEAR %in% maxyr, ]
# temp<-unique(temp[,c("VESSEL", "STATION", "LATITUDE", "LONGITUDE", "STRATUM")])
# 
# 
# (S`r SRVY `_plot <- ggplot() +
#  geom_sf(data = S`r SRVY `$akland) +
#  geom_sf(data = S`r SRVY `$bathymetry) +
#  geom_sf(data = S`r SRVY `$survey.area, fill = NA) +
#  geom_sf(data = S`r SRVY `$graticule, color = "grey70", alpha = 0.5) +
#  coord_sf(xlim = S`r SRVY `$plot.boundary$x, 
#  ylim = S`r SRVY `$plot.boundary$y) +
#  scale_x_continuous(name = "Longitude", 
#  breaks = S`r SRVY `$lon.breaks) + 
#  scale_y_continuous(name = "Latitude", 
#  breaks = S`r SRVY `$lat.breaks) + 
#  geom_point(data = temp, mapping = aes(x = temp$LONGITUDE, y = temp$LATITUDE, 
#  colour = factor(temp$VESSEL), shape = factor(temp$VESSEL))) +
#  theme_bw())
# 
# # my_label <- data.frame(x = -165, y = 58, label = "Thar be\ndragons")
# # S`r SRVY `_plot + geom_text(data = my_label, 
# # mapping = aes(x = x, 
# # y = y, 
# # label = label), 
# # color = "red")
# # 
# # my_label <- data.frame(x = -165, y = 58, label = "Thar be\ndragons") %>% 
# # akgfmaps::transform_data_frame_crs(in.crs = "+proj=longlat", out.crs = S`r SRVY `$crs)
# # S`r SRVY `_plot + geom_text(data = my_label, 
# # mapping = aes(x = x, 
# # y = y, 
# # label = label), 
# # color = "red")
# 
# 
# akgfmaps::YFS2017 %>% 
#  make_idw_map(region = "bs.all",
#  set.breaks = "jenks",
#  grid.cell = c(0.02, 0.02)) %>%
#  add_map_labels() %>% 
#  change_fill_color(new.scheme = "purple2", show.plot = TRUE) %>%
#  create_map_file(file.prefix = NA, 
#  file.path = NA, 
#  try.change_text_size = TRUE, # 12x9 is a pre-defined size
#  width = 12, 
#  height = 9, 
#  units = "in", 
#  res = 300, 
#  bg = "transparent")
# 
# yfs2017 <- akgfmaps::YFS2017
# 
# opt1 <- make_idw_map(x = yfs2017, # Pass data as a data frame
#  region = "bs.all", # Predefined bs.all area
#  set.breaks = "jenks", # Gets Jenks breaks from classint::classIntervals()
#  grid.cell = c(0.02, 0.02), # 0.2x0.2 degree grid cells
#  key.title = "yellowfin sole") # Include yellowfin sole in the legend title
# 
# 
# 
# 
# eval_plot_breaks(CPUE = yfs2017$CPUE_KGHA, n.breaks = 5)
# 
# yfs.opt1 <- make_idw_map(x = yfs2017,
#  region = "bs.all",
#  set.breaks = "jenks",
#  grid.cell = c(0.05, 0.05), # Coarse grid
#  key.title = "yellowfin sole")
# 
# yfs.opt2 <- make_idw_map(x = yfs2017,
#  region = "bs.all",
#  set.breaks = "kmeans", 
#  grid.cell = c(0.05, 0.05), # Coarse grid
#  key.title = "yellowfin sole")
# 
# yfs.opt3 <- make_idw_map(x = yfs2017,
#  region = "bs.all",
#  set.breaks = c(0, 25, 100, 250, 500, 1000),
#  grid.cell = c(0.05, 0.05), # Coarse grid
#  key.title = "yellowfin sole")
# yfs.opt3$plot

```


 
