---
output:
  word_document:
    pandoc_args: ["--metadata-file=header.yaml"]
    reference_docx: word-styles-reference.docx
csl: "../citationStyles/citationstyle.csl"
bibliography: "../data/bibliography.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE)
counter.inside<-0
```

#### Acknowledgments

Recognition and appreciation is extended to the captains and crew of the *FV Alaska Knight* and *FV Vesteraalen*. Without their expertise, goodwill, and sacrifice, this survey would not be possible. Thank you to the United States Seafoods and Vesteraalen LLC for making the vessels available and always maintaining safety as a top priority. Great appreciation is also extended to all the scientists, researchers, contractors, interns, and volunteers who worked tirelessly aboard each vessel to complete the survey in a safe and successful manner. Thanks also to Norton Sound Economic Development Corporation and Kawerak, Inc. The survey would not have been possible without the major contributions from other AFSC groups including the Net Shed, Research Survey Support Team, Data Management Group, and the Administrative team. Finally, appreciation is extended to the reviewers of this document whose excellent comments and suggestions greatly improved it. 
